### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by andrewkdinh** [anonaddy/anonaddy#1]
Any plans on a docker image, either built through a Dockerfile or as one on [Docker Hub](https://hub.docker.com)?

**Comment by anonaddy** [comment]
Only just seen this, sorry. Not at the moment I'm afraid.

I haven't used docker before so would need to learn how to use it and how to create an image.

I'll be adding more details on setting up the server and Postfix for self hosting shortly though.

**Comment by irazasyed** [comment]
Yeah, Docker image / setup would be very cool. We recently started using for a bunch of our projects.

I can help you with this if you're open for it. We could make use of Docker Compose to have multiple images.

My recent custom image for a project:
https://github.com/ougco/docker-laravel-php

**Comment by anonaddy** [comment]
Thanks, that would be great.

I'll have a read about Docker Compose as I agree it would be great to able to spin up a VPS and self-host quickly instead of having to manually configure everything.

I've got a few things on my to do list at the moment but I'll try to make a start on this as soon as I can.

**Comment by ra-pha** [comment]
+1 for that idea

**Comment by slurdge** [comment]
Hey @anonaddy would you need help for the docker image ? I guess the main difficulty is that the services are intertwined in each other so it's needed to create a big docker image with everything...
Let me know if you want me to have a look at it.

**Comment by anonaddy** [comment]
@slurdge yes, thank you. I have a fair bit on my to do list at the moment so don't currently have time to look into learning Docker and to set this image up myself.

I can provide you with a list of all software required and basic configuration, feel free to contact me via email if you think that would be easier.

**Comment by crazy-max** [comment]
I have a working Docker image but I haven't tested all the features. I can publish it right now but I prefer #12 and #13 to be fixed.

![image](https://user-images.githubusercontent.com/1951866/70856354-5884f100-1edb-11ea-9b8a-d99acfc965db.png)

![image](https://user-images.githubusercontent.com/1951866/70856357-60dd2c00-1edb-11ea-9566-19c967b22a27.png)

![image](https://user-images.githubusercontent.com/1951866/70856368-997d0580-1edb-11ea-8ff6-71ea145f6f7a.png)

![image](https://user-images.githubusercontent.com/1951866/70856363-81a58180-1edb-11ea-83f4-c0af45ad9abf.png)

**Comment by slurdge** [comment]
Terrific! Would you mind sharing it even if it's not stable yet, I'm willing to guinea-pig and reinstall once #12 and #13 are fixed.

**Comment by crazy-max** [comment]
> Terrific! Would you mind sharing it even if it's not stable yet

@slurdge Image available at https://github.com/crazy-max/docker-anonaddy/

**Comment by slurdge** [comment]
@crazy-max I took a look at it, seems great. I only have one remark, shouldn't the web part and the postfix part be two separate containers ? They share some php code but I believe they have no dependencies on each other ?

Also, @anonaddy , I can't wrap my head around the need for MAIL_HOST/MAIL_USER/etc env variables. Why rely on a 3rd party SMTP server as postfix is right here ?

**Comment by anonaddy** [comment]
@slurdge currently out of office so will respond properly in a day or two.

The MAIL_HOST and other env variables need to be removed from the env.example file, I forgot to update it.

The MAIL_DRIVER should be sendmail so that emails are sent using Postfix.

**Comment by slurdge** [comment]
I tried the image provided by @crazy-max and could run it (at least web interface). I have a few issues (https/http mixed, etc.) that I'll try to resolve.

**Comment by crazy-max** [comment]
> I have a few issues (https/http mixed, etc.) that I'll try to resolve.

@slurdge Leave an issue on my repo about that (maybe you missed `APP_URL` en var).

**Comment by slurdge** [comment]
Yes I'll open issues :-)

**Comment by anonaddy** [comment]
#12 and #13 should now both be sorted, thanks for the contributions. I'll be able to hopefully contribute to this image in the new year.

**Comment by slurdge** [comment]
So, by playing around with @crazy-max new image, I was able to create a new recipient and confirm it.
I'm trying to sort out https://github.com/crazy-max/docker-anonaddy/issues/2 and then I should be able to test with incoming emails.

**Comment by h-town** [comment]
Thanks for your work here @crazy-max and @slurdge. Looking forward to this one!

**Comment by crazy-max** [comment]
https://github.com/anonaddy/docker :)

**Comment by slurdge** [comment]
Doing tests on it right now!

**Comment by crazy-max** [comment]
Fyi, I have set up a  [Vultr VPS instance](https://www.vultr.com/) (1 vCore CPU, 1024MB RAM, 25GB SSD) using an Alpine 3.12 ISO with a traefik and this AnonAddy docker image. For the DNS and domain I'm using [Namecheap](https://www.namecheap.com/) and everything looks good so far (~4 weeks).

**Comment by slurdge** [comment]
I comment here because I'm not sure it comes from docker or anonaddy itself. After starting the instance, I can't create 'admin', 'anonaddy', or 'test' users. Is there any place where these forbidden usernames is defined ? Tells me they are already taken.

**Comment by crazy-max** [comment]
@slurdge You can't register against `https://anonaddy.example.com/register`?

**Comment by slurdge** [comment]
@crazy-max I can, but if I select 'admin', 'anonaddy', or 'test' as the username, it refuses to register. However other logins like 'test123456' are fine. So there must be some kind of list of either pre-made accounts or forbidden accounts

**Comment by willbrowningme** [comment]
@slurdge There is actually a username blacklist that is used here - https://github.com/anonaddy/anonaddy/blob/master/config/anonaddy.php

Do you think it would be best to remove this for the self-hosted version?

**Comment by slurdge** [comment]
@willbrowningme Thanks! I didn't find this list :-)
I think it's fine to leave it in the self-hosted version, after all, it's here for a reason!

**Comment by crazy-max** [comment]
@willbrowningme

> There is actually a username blacklist that is used

Didn't know about that thanks for the tip!

> Do you think it would be best to remove this for the self-hosted version?

It's fine to keep this list.

**Comment by slurdge** [comment]
Well I still can't make it work from a pristine install, but maybe it's best to discuss it on the docker repo :-)

**Comment by crazy-max** [comment]
@slurdge Yeah if it's about anonaddy/docker#21 it's ok to close this issue.

**Comment by andrewkdinh** [comment]
Looks great. Thanks!
