### ISSUE TITLE
warn users about how sending test messages might be misleading

### ISSUE THREAD

**Issue by ItsExtra** [anonaddy/anonaddy#11]
I was making use of another similar service and sent myself a test message to troubleshoot. Then I got this very clever email in my inbox:

> It appears that you are sending a test email through [another service] from your own email account. We want to warn you that many email clients, including Gmail, will hide these messages in your Sent folder, giving the false impression that [another service] failed to forward them.

I don't know what they do to determine this (maybe the word "test" in the subject with no body content?), but it seems like a very helpful thing to tell people.  

(I am assuming the etiquette here is to _not_ mention the competitor's name but that could be wrong; not my area.)

**Comment by anonaddy** [comment]
Thanks, I haven't heard of this with gmail before. This should not be an issue for AnonAddy as the email is forwarded on as a new message so shouldn't flag any messages like this.
