### ISSUE TITLE
Service unreachable

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [anonaddy/anonaddy#112]
Emails arent getting forwarded anymore.
I wanted to check the website but i cant reach the website.
Also tried the unofficial app but i didnt work.

**Comment by willbrowningme** [comment]
Our hosting provider is experiencing a DDOS attack, they are working hard to bring all services back online. Please check their Twitter for updates - https://twitter.com/greenhost

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Thanks for the quick response. 
Is it possible to also host ur service at another provider, so that u dont have a single point of failure?

**Comment by willbrowningme** [comment]
Yes I will be doing that as soon as possible after this incidence.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
So before opening an issue here i tried to check if there was a post of this to be find anywhere, but i couldnt find it. I dont know how much value it will add atm because Greenhost says it is almost resolved, but maybe it is good to do a post about this on r/annonaddy.

**Comment by willbrowningme** [comment]
I'm sharing updates on Twitter and have just posted in r/anonaddy - https://old.reddit.com/r/AnonAddy/comments/kexaam/hosting_provider_experiencing_ddos_attack/

**Comment by willbrowningme** [comment]
Closing this, I will write a blog post in the coming days with more details and some potential solutions.
