### ISSUE TITLE
[Feature Request] Option to permanently discard aliases that are disabled

### ISSUE THREAD

**Issue by ghost** [anonaddy/anonaddy#113]
It gets cluttered when the disabled spam aliases are not used but no way to clean it up from the Hidden Alias list. Sure you can hide them, but an option to trash (maybe send them to a central server blacklist so no chance of reuse) would be better.

**Comment by Virtual-Github** [comment]
I think its not a good idea ,you have option to hide deleted alias use that. I sometimes need to use deleted alias mainly for custom shared domain alias that is created before on site and so that I can use it again and you may also need in future. So I think its good option that anonaddy gives access to deleted alias.

**Comment by willbrowningme** [comment]
This is currently a planned feature on the roadmap - https://github.com/anonaddy/anonaddy/discussions/105

It would mean that if the alias used a shared domain then it would never be able to be used again.

However if the alias was at a custom domain or your unique username subdomain then you would be able to create it again in the future.

**Comment by grande-mephistopheles** [comment]
> This is currently a planned feature on the roadmap - #105
> 
> It would mean that if the alias used a shared domain then it would never be able to be used again.
> 
> However if the alias was at a custom domain or your unique username subdomain then you would be able to create it again in the future.

That's great! Eagerly waiting for this feature :+1:

**Comment by willbrowningme** [comment]
This feature has just been added.
