### ISSUE TITLE
Bandwidth usage for each alias

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [anonaddy/anonaddy#116]
So today i noticed that I'm over the monthly bandwidth usage and i thought to myself what alias is using this much bandwidth.
It could be alias X that received one huge mail or it could be alias Y that received 80 mails in a month.
So that is why i think that it will be a handy feature to have more insight of that.

Quick question what will happen when I'm using more then the monthly bandwidth? My bandwidth cap is at 10MB but it is displaying that i already used 10.7MB. I'm scared of not receiving incoming mails this month.

**Comment by willbrowningme** [comment]
The main problem I can think of with moving bandwidth usage data to each individual alias is that I will soon be adding the option to "dissasociate/forget" an alias. This would then remove that data too. 

I'll have a think about a way to get around the above problem.

Once you go over your bandwidth limit the emails will be dropped, this is mentioned in the FAQ section on the site.

Did you receive an email letting you know you were close to your limit?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
No i didn't get any mail :(

**Comment by willbrowningme** [comment]
Hmm, okay then there might be a bug. You should receive an email notification each day when you go over 90% of your bandwidth limit. I'll look into this shortly. If you send me an email with your username I can reset your bandwidth for this month so you can still receive emails.

**Comment by willbrowningme** [comment]
Closing this for now as no current plans to implement.
