### ISSUE TITLE
Last contact column

### ISSUE THREAD

**Issue by crazy-max** [anonaddy/anonaddy#119]
Like Abine, would it be possible to add a "Last contact" column on Aliases page?:

![image](https://user-images.githubusercontent.com/1951866/104106173-ae2cf800-52ab-11eb-9695-2f95286960cf.png)

**Comment by ccorneli** [comment]
Similarly Sneakemail has details for:  (example)
   Last used on:  Sat, 28 Dec 2019 00:05:01 +0000'

**Comment by xanoni** [comment]
I strongly vote against this. I would not want this type of information be logged by the server. If you really need to know, you can check your mail program.

**Comment by ccorneli** [comment]
I understand the concern. So perhaps something that can be configured in privacy preferences to optionally enable.  (Default would be security/privacy first.. so would need to be manually enabled).  It wouldn't need to maintain a full log, it could simply update a register with the latest timestamp as it passes through. Much like it does for message count of forwarded/blocked.  (At least that's how I assume it works)

**Comment by xanoni** [comment]
Yes optional is fine, but it should not be just `set hidden=false`. I prefer AnonAddy to be a bare bones tool that doesn't try to aggregate and analyze all the data that flows through it.
Users are already increasing their attack surface by adding a middleman to the mix, so why then also ask the middleman to log/aggregate information. I think the convenience is not worth it.

**Comment by xanoni** [comment]
Just created this: https://github.com/anonaddy/anonaddy/issues/163

**Comment by crazy-max** [comment]
> I would not want this type of information be logged by the server.

Why? This is already logged by Postfix server and the Forwarded counter already gives an hint of the alias activity.

**Comment by xanoni** [comment]
> Why? This is already logged by Postfix server and the Forwarded counter already gives an hint of the alias activity.

There is a world in which logs are not kept forever.

**Comment by texinick** [comment]
I, too, would like to see a 'last used' date so I have some idea if anything is coming through for the relevant address.

**Comment by billyb1987** [comment]
+1 I would like this feature.
