### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by crazy-max** [anonaddy/anonaddy#12]
Hi,

First of all, thank you for this project, it's exactly what I've been looking for for a long time!

I started working on a Docker image and everything looks fine except that there is no versioning or roadmap to correctly tag the versions in this Docker image.

Would it be possible for you to set this up through Git tags to start with?

Thanks!

**Comment by anonaddy** [comment]
Thanks a lot. I'll add semantic versioning to the repo shortly. Do you think I should start at version 0.1.0 or 1.0.0?

**Comment by crazy-max** [comment]
@anonaddy I think a prem-ver 0.1.0 is a good start

**Comment by anonaddy** [comment]
@crazy-max I've just tagged initial version 0.1.0, thanks!
