### ISSUE TITLE
Unable to add recipient with subdomain

### ISSUE THREAD

**Issue by TomasTokaMrazek** [anonaddy/anonaddy#126]
I have one domain and one subdomain. Domain DNS records (MX, DKIP, SPF) point to AnonAddy, which obviously serves as a proxy. Subdomain DNS records point to my selfhosted email server. I would like to be able to add subdomain email as a primary recipient for domain. In AnonAddy, it is currently not possible due to error "The recipient cannot use a local domain or be an alias."

I understand this limitation, it serves as a prevention to email loop, but my usecase is perfectly valid and currently works. In other words, email send to anonaddy@domain.tld goes through AnonAddy, email send to personal@mail.domain.tld goes through my email server. 

Right now I am basically forced to use third-party email provider as a recipient for AnonAddy, or switch my email server to different domain. Neither solution is feasible for me, but I'll glady hear some arguments on why move email server to different domain. 

I unfortunately don't have a solution from AnonAddy side. I can only think of validating MX DNS records for specified subdomain in recipient and block the request only if it points to AnonAddy email servers.

**Comment by willbrowningme** [comment]
Hmm, thanks for bringing your scenario up. I'll have to have a think about the best way to change this to allow what you've described.

You're right that the restriction is in place as I wanted to avoid any alias -> recipient -> alias -> ... loop.

**Comment by willbrowningme** [comment]
I've just pushed an update that fixes this.

Please try to add your subdomain again and let me know if you are still having issues.

**Comment by TomasTokaMrazek** [comment]
Thank you, I tested it today, works as expected.
