### ISSUE TITLE
[Feature Request] Specify recipient for newly created alias

### ISSUE THREAD

**Issue by TomasTokaMrazek** [anonaddy/anonaddy#129]
Workflow for creating new alias is composed of **domain**, **format**, **local part** and **description**. I suggest to add new filed for recipient. This is not that much needed in web gui itself, since it's few click away, but browser extensions can highly benefit from this.

**Comment by willbrowningme** [comment]
Good idea, I've added it to the roadmap and will work on it as soon as I can.

**Comment by willbrowningme** [comment]
I've just added this to the web app and will try to update the browser extension to include it shortly too.

**Comment by willbrowningme** [comment]
Now added to v2 of the browser extension.
