### ISSUE TITLE
Request: Move unsubscribe header to the bottom of the mail

### ISSUE THREAD

**Issue by grandeljay** [anonaddy/anonaddy#139]
Pretty much the title. The unsubscribe link is really cool but as somebody who immediately clicks the first link he sees in an e-mail (to activate his account or whatever) I would greatly benefit if it was at the bottom and thought it couldn't really harm, would it?

The Newsletter unsubscribe links are also all at the bottom, so why not the same for anonaddy? :)

**Comment by willbrowningme** [comment]
Hi, it's already possible to set this text to appear at the bottom of the email or to turn it off completely. It's under "Update Email Banner Location" in account settings and is available on paid plans.
