### ISSUE TITLE
Customize self-hosted environment

### ISSUE THREAD

**Issue by rajaseg** [anonaddy/anonaddy#140]
@crazy-max Thank you very much for the application. Is there a way to edit or modify self-hosted environment? I wanted to include

1. Upload custom logo
2. Modify mail templates to include custom logo and footer notes
3. Include custom terms page in registration page

**Comment by jonathan-rosa** [comment]
No, the word for your list is called "white labeling." Usually the forwarding email address service has a white label add-on, like Tutanota or just use a HTML email signature. The branding responsibility would be at the forwarding email address, and not the email alias service.

It'd be a mess anyway because the forwarding emails can be different domains.

**Comment by rajaseg** [comment]
> No, the word for your list is called "white labeling." Usually the forwarding email address service has a white label add-on, like Tutanota or just use a HTML email signature. The branding responsibility would be at the forwarding email address, and not the email alias service.
> 
> It'd be a mess anyway because the forwarding emails can be different domains.

@jonathan-rosa Thank you very much for the reply. I just want to modify the mail coming from Anonaddy when ever new user register the account, i.e. account activation mail. That mail has Anonaddy logo and footer link.

**Screen shot below for reference.**

![image](https://user-images.githubusercontent.com/633479/113570790-a70b5100-9632-11eb-96c2-2c73954887f5.png)

**Comment by willbrowningme** [comment]
Sounds like you need to fork the repo and make these custom changes there. 

You'll need to know your way around Laravel, you can make the changes here - https://github.com/anonaddy/anonaddy/blob/master/resources/views/vendor/mail/html/message.blade.php

**Comment by rajaseg** [comment]
> Sounds like you need to fork the repo and make these custom changes there.
> 
> You'll need to know your way around Laravel, you can make the changes here - https://github.com/anonaddy/anonaddy/blob/master/resources/views/vendor/mail/html/message.blade.php

@willbrowningme Thank you for the reply. I wanted to use the docker version of Anonaddy. How do I refer my cloned repo to build the docker image?

**Comment by crazy-max** [comment]
@rajaseg https://github.com/anonaddy/docker/blob/d3573ee4a12eb53d65f001cbb46599997129187d/Dockerfile#L94
