### ISSUE TITLE
DKIM Signing clarification

### ISSUE THREAD

**Issue by Flash1232** [anonaddy/anonaddy#142]
Just to make sure this is not some bug with the docker image:

Is it true that the `signing.table` file as described in [SELF-HOSTING.md](https://github.com/anonaddy/anonaddy/blob/master/SELF-HOSTING.md#spf-and-dkim) will sign mail to both *.domain.com as well as the main domain.com aliases? When testing with the docker image I only receive DKIM signed mails when sending to xyz.domain.com. Mails sent to domain.com aliases simply don't have a DKIM signature.

The docker image inserts *.domain.com blabla (https://github.com/anonaddy/docker/blob/d3573ee4a12eb53d65f001cbb46599997129187d/rootfs/etc/cont-init.d/03-config.sh#L272) into the `signing.table` file whereas the SELF_HOSTING.md describes to use `*@*.domain.com`. Is there any difference or do I even need to additionally make a line with just domain.com without prefix asterisk?

Or am I doing something else incorrectly?

PS: There is a related issue in the docker repo: https://github.com/anonaddy/docker/issues/47 .

**Comment by willbrowningme** [comment]
The `signing.table` file should have both lines:

```
*@example.com    default._domainkey.example.com
*@*.example.com    default._domainkey.example.com
```

The first line signs all emails at the apex domain (example.com) and the second line signs all emails that are subdomains of the apex domain (anything.example.com). Both with the same key.

It seems the docker image needs another line:

```
${ANONADDY_DOMAIN}    default._domainkey.${ANONADDY_DOMAIN}
*.${ANONADDY_DOMAIN}    default._domainkey.${ANONADDY_DOMAIN}
```

Also I would have thought the lines in the docker file should be:

```
*@${ANONADDY_DOMAIN}    default._domainkey.${ANONADDY_DOMAIN}
*@*.${ANONADDY_DOMAIN}    default._domainkey.${ANONADDY_DOMAIN}
```

Although I don't use Docker so I haven't tested this myself.

In the self-hosting instructions I mention "add this line too" meaning in addition to the one from the tutorial - https://www.linuxbabe.com/mail-server/setting-up-dkim-and-spf

I've moved over to Rspamd recently which can sign emails so I may update the self-hosting docs soon to describe how to use that instead.

**Comment by Flash1232** [comment]
> In the self-hosting instructions I mention "add this line too" meaning in addition to the one from the tutorial - https://www.linuxbabe.com/mail-server/setting-up-dkim-and-spf

Oh right, I got confused as I am using the docker image and just assumed this would be already present.



> I've moved over to Rspamd recently which can sign emails so I may update the self-hosting docs soon to describe how to use that instead.

That would be great, and thanks for your work here! It is much appreciated :).
