### ISSUE TITLE
Disable custom alias creation at room domain

### ISSUE THREAD

**Issue by msaeedm** [anonaddy/anonaddy#143]
Hi,

The default settings for self hosted environment allows for any user to create a custom alias at the root domain such as mycustomalias@mydomain.tld. Is there a way to disable this feature but keep it only for the admin user defined in ANONADDY_ADMIN_USERNAME?

**Comment by willbrowningme** [comment]
Not at the moment I'm afraid. I'll try to add this as an option shortly though.

**Comment by msaeedm** [comment]
That sounds good. Thank you sir

**Comment by Dominion0815** [comment]
3 years later ... is it possible to add this option now? @willbrowningme

**Comment by willbrowningme** [comment]
I've just added this, you need to add `ANONADDY_NON_ADMIN_SHARED_DOMAINS=false` to your `.env` file in order to enable it.

Will tag a new release shortly.
