### ISSUE TITLE
score changes

### ISSUE THREAD

**Issue by lgwapnitsky** [anonaddy/anonaddy#147]
per this comment:

> You may need to change the scores for a couple of symbols to 0 since AnonAddy uses a different email in the display from and email from.

which scores are recommended to change?

Thank you

**Comment by willbrowningme** [comment]
The scores I'm referring to are just below that comment:

```
group "headers" {
  symbols {
    "FAKE_REPLY" {
      weight = 0.0;
    }

    "FROM_NEQ_DISPLAY_NAME" {
      weight = 0.0;
    }

    "FORGED_RECIPIENTS" {
      weight = 0.0;
    }
  }
}
```

**Comment by lgwapnitsky** [comment]
Got it
