### ISSUE TITLE
[Feature Request] Shorten Anonaddy Domain on Alias Creation

### ISSUE THREAD

**Issue by FrozenVertx** [anonaddy/anonaddy#150]
Hi,
I want to suggest feature to shorten the domain of anonaddy on alias creation.
For Example 
Instead of this-  Github@user.anonaddy.me 
Make like- Github@user.anon.me OR Github@user.ady.me OR anything sorter around 3-5 words only.
Its really quick when writing.

I totally want to suggest it as an optional, If not Possible then forget it.

**Comment by M09NST3R** [comment]
So basically, you want additional domains that are shorter than the default domain. It's your lucky day. The paid subscription includes a domain of the same length (# of characters) as what you're proposing.

**Comment by willbrowningme** [comment]
The paid plans already include 3 extra domains that you can use, one of these is very short.

I'll keep an eye out for any other short domains that would be appriopriate too.
