### ISSUE TITLE
error while upgrading

### ISSUE THREAD

**Issue by jon-bit** [anonaddy/anonaddy#151]
I ran all the commands in the upgrading section and that was fine, however when I run the last command (php artisan queue:restart) I get this 

`root@anonaddy:/var/www/anonaddy# php artisan queue:restart
In PhpRedisConnector.php line 141:
Network is unreachable
`
I don't know why this happend today.

this is my .env file 
`APP_NAME=AnonAddy
APP_ENV=production
APP_KEY=base64:NhMSdI8a7Wp26vmm0e+J4d514NmcGIIi1ClEfjaCKv0=
APP_DEBUG=false
APP_LOG_LEVEL=debug
APP_URL=******************

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3307
DB_DATABASE=anonaddy_database
DB_USERNAME=anonaddy
DB_PASSWORD=12345

BROADCAST_DRIVER=log
CACHE_DRIVER=redis
QUEUE_CONNECTION=redis
SESSION_DRIVER=redis
SESSION_LIFETIME=10080
SESSION_SECURE_COOKIE=true
SAME_SITE_COOKIES=lax

REDIS_CLIENT=phpredis
REDIS_HOST=localhost
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=sendmail
MAIL_FROM_NAME=****
#MAIL_FROM_ADDRESS=*********
MAIL_FROM_ADDRESS=*******************************

#ANONADDY_RETURN_PATH=**********
ANONADDY_RETURN_PATH=***************************
ANONADDY_ADMIN_USERNAME=***
ANONADDY_ENABLE_REGISTRATION=true
ANONADDY_DOMAIN=*****************************
ANONADDY_HOSTNAME=***************************
ANONADDY_DNS_RESOLVER=127.0.0.1
ANONADDY_ALL_DOMAINS=*********************************************
ANONADDY_SECRET=tgvjrhn54utoehrtyio78ey0rfhdrthiobq79e63ry5h9rftuyq2wgj43fagyoerq3yhseyobqauoweyd23tnthjklvjhdzkvxofn780qwuj4jwn807tjhi043j89y0pjiw459h7guh9h8rwrpuih3w89407rqh3tuih5408734jtuiorbn07ewthj>
ANONADDY_LIMIT=200
ANONADDY_BANDWIDTH_LIMIT=1000000000000000000000000000000000000000000000000000
ANONADDY_NEW_ALIAS_LIMIT=75
ANONADDY_ADDITIONAL_USERNAME_LIMIT=3
ANONADDY_SIGNING_KEY_FINGERPRINT=
ANONADDY_DKIM_SIGNING_KEY=/etc/opendkim/keys/example.com/default.private
ANONADDY_DKIM_SIGNING_KEY=/etc/opendkim/keys/***************************/anonaddy.private
ANONADDY_DKIM_SELECTOR=anonaddy

PASSPORT_PERSONAL_ACCESS_CLIENT_ID=1
PASSPORT_PERSONAL_ACCESS_CLIENT_SECRET=Yju1TN8XZ1v85dMSkNxkLc7oleHehPQAFKjeCV0t
`

I don't know why this is happening but if anyone knows whats wrong please let me know because I'm worrying something is messed up.

**Comment by jon-bit** [comment]
UPDATE!

I restated the loop back and now it says

No route to host

**Comment by willbrowningme** [comment]
Hi there, 

You should not share senstive information in your `.env` file such as the `APP_KEY, ANONADDY_SECRET, PASSPORT_PERSONAL_ACCESS_CLIENT_SECRET`

I would recommend you generate new values for all of these if you are are using them in production.

Is redis running correctly on your server?

What is the output of:

```bash
sudo service redis status
```

**Comment by jon-bit** [comment]
1. Sorry I didn't notice that.

2. It's not working (some how) but now I can't send verification emails for a new account. any idea how to solve that?
 P.S. Thank you for the responce.

**Comment by willbrowningme** [comment]
I'm afraid I cannot debug this without any information, what does the mail log say? What about the Laravel log?

**Comment by jon-bit** [comment]
I figured it out. I acedently did not change the owner to my local user. Should I close?

**Comment by willbrowningme** [comment]
Glad you sorted it, I've closed the issue now.
