### ISSUE TITLE
"Default recipient" is not used when new alias arrives

### ISSUE THREAD

**Issue by pm-pm** [anonaddy/anonaddy#154]
Hello,
after setting the "Default Recipient" to a new email address the new email address is ignored.
New mails (with a new alias) are still forwarded to the " standard mail" address. I have to change it manually to each new alias.

I think this a bug!? Could you please check this.
Thanks

**Comment by willbrowningme** [comment]
Please can you email me with your account username and let me know which alias you used so I can look into it.

**Comment by willbrowningme** [comment]
This has been resolved via email.

@pm-pm had a default recipient they had set for their custom domain which was overriding the account wide default recipient.
