### ISSUE TITLE
Ellipsis menu gets truncated if there is only one result when searching for alias

### ISSUE THREAD

**Issue by lyrebird-sound-cloning-system** [anonaddy/anonaddy#155]
# How to reproduce
1. Search for an alias in a way that only one result will be displayed;
2. Open the ellipsis menu.

![Screenshot_20210522_022608](https://user-images.githubusercontent.com/84561213/119215662-7332a080-baa5-11eb-90a3-7d397bb4e1a4.png)

Removing overflow:auto from .vgt-responsive class fixes the problem:
![Screenshot_20210522_023300](https://user-images.githubusercontent.com/84561213/119215760-1683b580-baa6-11eb-9e5e-34ff3ce49d19.png)

**Comment by willbrowningme** [comment]
Thanks very much, I've just pushed an update that fixes this issue.

**Comment by lyrebird-sound-cloning-system** [comment]
I'm glad that I helped o/
