### ISSUE TITLE
[Enhancement] Add Version Info

### ISSUE THREAD

**Issue by h-town** [anonaddy/anonaddy#156]
Please consider adding version information to the webapp UI; if even a user-configured option and/or it being shown at the very bottom of /settings.  

As it sits today I have to compare the file dates among those at /var/www/anonaddy in order to approximate the version I'm on.  Granted, there's probably a more straightforward way to do it, but having the info front-and-center would be nice.  👍

Thanks again for your hard work in maintaining this project Will!

**Comment by willbrowningme** [comment]
Thanks a lot, that's a great idea. I've just added the version details to the footer in the latest [commit](https://github.com/anonaddy/anonaddy/commit/92ce598a559d97d95ef90c62a65c251424d5fc71).

You can also get the apps version details by calling the API - [https://app.anonaddy.com/docs/#get-the-current-anonaddy-app-version](https://app.anonaddy.com/docs/#get-the-current-anonaddy-app-version) replacing `app.anonaddy.com` with the URL of your own instance.
