### ISSUE TITLE
Sign up confirmation email has broken image

### ISSUE THREAD

**Issue by michel-slm** [anonaddy/anonaddy#16]
When signing up, at least via a Gmail address, even after loading images the AnonAddy logo does not show up

![Screenshot_20200120-163122](https://user-images.githubusercontent.com/85603/72765786-f0dd5800-3ba2-11ea-8973-dcc3e46196b5.png)

**Comment by anonaddy** [comment]
@michel-slm Thanks for bringing this to my attention. The issue was that I was using an SVG for the logo which apparently isn't supported by Google.

I've changed it to a PNG image now, appears to be working correctly.
