### ISSUE TITLE
Reply does not seem to work in free registration on anonaddy.com

### ISSUE THREAD

**Issue by Retroman445** [anonaddy/anonaddy#160]
When sending a reply to an address in the format of:

`somealiaswhichexists+test=test.nl@myusername.anonaddy.com`

results in receiving the e-mail on my registered forward address and not on the test@test.nl address.

(All data fictional)

**Comment by xanoni** [comment]
See here: https://github.com/anonaddy/anonaddy/issues/152

**Comment by willbrowningme** [comment]
The free account does not include replies or sending from an alias. You are permitted one of either to test it out and see how it works. 

What you've described sounds like you are not sending the reply from an email address that is listed as a verified recipient on your account.
