### ISSUE TITLE
[Feature request] Disable encryption for specific aliases

### ISSUE THREAD

**Issue by 4n0nym0u53** [anonaddy/anonaddy#170]
An option to disable PGP encryption for specific aliases could be very useful, something like what SimpleLogin does. A scenario where this is useful would be if the alias is used with a service that already encrypts emails (e.g. Facebook), in which case it would be redundant having AnonAddy encrypt it once more.

**Comment by willbrowningme** [comment]
This is currently possible by creating a rule, the Rules feature is in beta but if you want to try it out just email me your username and I'll add you to the list.

**Comment by willbrowningme** [comment]
You could do:

IF alias IS EXACTLY xyz@anonaddy.com THEN turn off encryption.

**Comment by 4n0nym0u53** [comment]
@willbrowningme damn, that's neat! I've sent you an email.
