### ISSUE TITLE
Periodic domain health check

### ISSUE THREAD

**Issue by theomessin** [anonaddy/anonaddy#172]
I've been using Anonaddy Pro with a custom domain for a while now. I was cleaning up my accounts and I deleted a DigitalOcean team that didn't have any droplets. I completely forgot that I had my domain's DNS on that team, however. I stopped receiving emails - something I accidentally found out about 24 hours later. A simple periodic DNS health check would've caught this a lot sooner. I can help implement this if you think it's something you'd be happy to have (maybe, just for the Pro plan for managed accounts).

**Comment by willbrowningme** [comment]
I do have a basic DNS check for that checks domains sending verification each day. However it does not check that the MX records are still pointing to AnonAddy, I'll add that to the checks too.

Did you not receive any notifcation saying your domain had been unverified for sending?

**Comment by theomessin** [comment]
Nope, didn't receive anything 😕

**Comment by willbrowningme** [comment]
Hmm okay thanks, I'll update and then test with my own domain by changing the records.

**Comment by willbrowningme** [comment]
Just added this in [v0.8.0](https://github.com/anonaddy/anonaddy/releases/tag/v0.8.0), a daily check will be carried out for every custom domains MX records and an email notification will be sent if they are invalid.
