### ISSUE TITLE
Responding to sent email creates risk of leaking real email address

### ISSUE THREAD

**Issue by xanoni** [anonaddy/anonaddy#173]
Happened to me a few times and it's always extremely annoying ...

1. You get an email on an alias and you respond to that email
2. You realize that you forgot to mention something, so you follow-up on your (own) sent message
3. DOXXED! AnonAddy just forwarded your real email address (which is included in your own quoted text from the previous sent email)

Isn't there some technical solution to this? E.g., filtering out everything that looks like the actual email address or other identifying information? Should be a trivial regex, but so much pain saved?

**Comment by willbrowningme** [comment]
I think this depends on the email client you are using, when I do this in Thunderbird it show's as:

On 07/07/2021 10:16, Will wrote:
> quoted email...

So it does not expose the real email.

What client / web app are you using for your email?

Yes it should be possible to remove any mention of the real email from the message body.

**Comment by xanoni** [comment]
> What client / web app are you using for your email?

I think this is how most popular webmail clients handle it (Gmail, Live.com, Protonmail, etc.) and probably even Thunderbird if you don't specify a name.

**Comment by xanoni** [comment]
@willbrowningme curious how you think about next steps here ... as far as I know, most webmail providers don't allow users to sanitize the "From" strings... let me know if you figure out how...

Is this something that you're planning to fix in AA directly any time soon, or should I try to find my own solution? 

If the latter, then I would likely write a browser extension that strips out pre-defined regex patterns. But it's a hack, so would be better to have AA do it directly.

(This is somewhat time sensitive for me, given that I don't want more "accidents" to happen.)

**Comment by willbrowningme** [comment]
I've just implemented this using a simple `str_ireplace()` please try it again now by replying to yourself to check.

Notes: 
- It will only remove the real email address that your are sending the reply/send from and not any of your other real recipient addresses
- It is case insensitive
- It will remove multiple mentions of the real email address

**Comment by xanoni** [comment]
THANK YOU! Will test.

> * It will only remove the real email address that your are sending the reply/send from and not any of your other real recipient addresses

This one creates a bit of a challenge for me and my current setup .... would be good if at some point all addresses were included. Or at least, ignore the `xyz` part in `user+<xyz>@host.com`.

In the end state, would it be possible to have a box in the settings where we can define our own patterns? There's other stuff we may want to remove.

**Comment by xanoni** [comment]
@willbrowningme seems to be working! however, people should note that it only deletes the email address, not the name before the email address .. so that still has to be sanitized manually, if desired

**Comment by willbrowningme** [comment]
Yes potentially an option to remove user set patterns, I'll do some more tests when I get time.

**Comment by xanoni** [comment]
Got it, thank you.
