### ISSUE TITLE
On firefox, username reminders are not sent

### ISSUE THREAD

**Issue by galets** [anonaddy/anonaddy#174]
Ubuntu 20.04:

To reproduce:

* Try to login
* Click forgot username/password
* Clich forgot username

blank screen

extensions in use: ghostery + privacy badger
same computer  it works if browser = chrome

**Comment by willbrowningme** [comment]
I believe I've just fixed this, please could you try again and let me know if the issue still persists?

I think it was related to the email validation check `'required|email:rfc,dns'`, removing the dns requirement seems to have sorted it.

**Comment by galets** [comment]
It is still broken, see screenshot with some diagnostics

![image](https://user-images.githubusercontent.com/2415755/125807821-1ed3427d-2260-4e26-9286-0529e3b383a8.png)

**Comment by willbrowningme** [comment]
Okay, it should now be fixed, please check again.

**Comment by galets** [comment]
Works now
