### ISSUE TITLE
Can't recieve emails from orange.fr

### ISSUE THREAD

**Issue by user038418** [anonaddy/anonaddy#178]
## Is your feature request related to a problem? Please describe.

I can't receive emails sent to an anonaddy alias from an orange.fr email address

## Describe the solution you'd like

Maybe the anti-spam filtering blocks these emails out.

## Additional info

It is quite problematic that I can't receive any emails from certain addresses

**Comment by willbrowningme** [comment]
Seems to be an issue starting a TLS handshake, will investigate now.

`Cannot start TLS: handshake failure`

**Comment by willbrowningme** [comment]
It seems that orange.fr does not have a correctly configured mail server - https://internet.nl/mail/orange.fr/559020/# and https://www.hardenize.com/report/orange.fr/1626686902#email

Using `SSL 3.0` and `TLS 1.0` which should now be phased out. It may be worth contacting them to inform them about these issues with their mail server.

**Comment by willbrowningme** [comment]
Closing for now.
