### ISSUE TITLE
Does not accept PGP key exported from ProtonMail

### ISSUE THREAD

**Issue by groovecoder** [anonaddy/anonaddy#18]
Steps to reproduce:

1. Go to https://mail.protonmail.com/keys
2. Click "Export"
3. Click "Public Key"
4. `cat ~/Downloads/publickey.`redacted`.asc | pbcopy`
5. Go to https://app.anonaddy.com/recipients
6. Next to the protonmail recipient, click "Add public key"
7. Paste into the `textarea` element
8. Click "Add Key"

Expected results:
Public key is added to the recipient

Actual results:
Error message: "Valid Key required"

**Comment by anonaddy** [comment]
@groovecoder You need to make sure to remove the "Version" and "Comment" lines:

```
Version: OpenPGP.js v4.7.2
Comment: https://openpgpjs.org
```

There is a small note about this on the "Add public key" modal but perhaps it isn't clear enough.

Please try again after removing these two lines and let me know if you are still having issues.

**Comment by groovecoder** [comment]
Yup, removing those lines fixed it.

**Comment by anonaddy** [comment]
Great!
