### ISSUE TITLE
Difficulty opening attachments

### ISSUE THREAD

**Issue by 4n0nym0u53** [anonaddy/anonaddy#186]
I have an issue with attachments sent through AnonAddy. I'm using ProtonMail as my recipient email address and have end-to-end encryption enabled in AnonAddy. When I receive an end-to-end encrypted email through AnonAddy, I can't open attachments, it just keeps loading on downloading the attachment. This only happens on the ProtonMail Android app tho, not on the web, so I don't know if it's an issue with AnonAddy or ProtonMail.

I have some rules enabled regarding encryption, but they're not related to the alias or sender this issue happens with.

**Comment by willbrowningme** [comment]
Hmm, that sounds like it might be an issue with the ProtonMail Android app. I've also had issues with the ProtonMail app trying to download attachments, for me it just does nothing when I click download. Works fine in the web app though.

Will close for now, but if any information comes to light that this is related to AnonAddy I'll reopen.
