### ISSUE TITLE
My dmarc settings are not recognized

### ISSUE THREAD

**Issue by jurgenhaas** [anonaddy/anonaddy#187]
Just got a blocked email reply and found out about the dmarc requirements. I've set them with Cloudflare, my DNS provider, and still get the same error. Here is the setting:

![2021-08-16_10-20](https://user-images.githubusercontent.com/1475675/129534348-ce25877a-4cd0-44a2-80c4-8efde10e5fe7.png)

Any idea what's wrong? Maybe you DNS records have not been updated yet?

**Comment by willbrowningme** [comment]
I'm assuming you are trying to reply/send from an alias?

If so, have you read this from the FAQ - https://anonaddy.com/faq/#im-trying-to-reply-send-from-an-alias-but-it-is-rejected-whats-wrong

**Comment by willbrowningme** [comment]
Hmm your records look correct, it must just be a caching issue if you've only just updated the records. Please try again in a little while and let me know if the issue still persists.

**Comment by willbrowningme** [comment]
I've just cleared the DNS cache for your domain, please try again now.

**Comment by jurgenhaas** [comment]
Perfect, now it works ! Great support.
