### ISSUE TITLE
Clarification on send from alias limit

### ISSUE THREAD

**Issue by seonwoolee** [anonaddy/anonaddy#19]
I've been testing out the new send from alias feature and it works great! Thank you for this - other email forwarding services like Blur or 33mail don't let you initiate emails like this, only reply to emails sent to an already established alias.

I know you only put up the send from alias feature two hours ago, so I don't mean to rush you, but could we get some clarification on the send from alias limit? It seems I already hit the limit at three such emails while I was testing it with my Lite plan. 

Is this limit per day? Is this a limit on the number of emails sent or the number of recipients the emails are sent to? How much higher is the limit on the Pro plan?

**Comment by anonaddy** [comment]
@seonwoolee Thanks!

The limit is per day yes (or any 24 hour window). The limit is on the number of emails that are sent.

The Lite plan has a daily limit of 5 and the Pro plan has a daily limit of 25.

I'll update the website shortly to show these on the pricing section.

I'll also be posting a blog post that goes over this new feature in more details.

**Comment by chiraag-nataraj** [comment]
I was just about to ask for this feature and I found this issue! I presume it hasn't been released yet (or I'm blind and can't find it)...what's the status?
