### ISSUE TITLE
Cannot email domains without AAAA record

### ISSUE THREAD

**Issue by voxlunch** [anonaddy/anonaddy#195]
My recipient address cannot receive emails as the domain doesn't have an IPv6 AAAA record, only an IPv4 A record.

This error appears in the Failed Deliveries tab:

`X-Postfix; Host or domain name not found. Name service error for name=<REMOVED> type=AAAA: Host found but no data record of requested type`

**Comment by willbrowningme** [comment]
Hmm, please could you [email me](https://anonaddy.com/contact/) with your actual domain so that I can check what the issue is?

**Comment by willbrowningme** [comment]
I've just checked this and it appears your domain does not have any MX records published at all.

Please verify you have correctly set MX records for your recipient's domain and if you are still having issues then send me an email.
