### ISSUE TITLE
Completely remove an account

### ISSUE THREAD

**Issue by rc042** [anonaddy/anonaddy#198]
Hi,

I test AnonAddy and if an account has been deleted, we can't create a new one with the same name. An error message said: _"The username has already been taken."_

Following my understanding, there is no admin dashboard, and I wonder know how I can definitely delete an account.

There is a table named `deleted_usernames` with an uniq column named `username`, however, the cell is encrypted (difficult to delete the good one if I have many account :p ):

![CleanShot 2021-09-16 at 12 11 40@2x](https://user-images.githubusercontent.com/22028430/133594436-f0d80261-e8bc-4017-9061-c81d633dd282.png)

Is there a particular reason to have this table? (I think about a security issue: If someone get the alias, he should receive emails from the previous user, right?)

Can I delete this entry without any side effect (except the security issue)? And, is there a cron job witch do that?

Thanks!

**Comment by willbrowningme** [comment]
Yes, that's correct. The default behaviour is that once a username has been deleted it cannot be used by anyone else again. Yes, it's to prevent the risk of someone else gaining access to a previous user's aliases.

That is what the `deleted_usernames` table is for, it's encrypted for another layer of security. You can delete any rows from that table if you wish, and then that username will be free to use again.

I'll add an `.env` option to let you choose whether usernames that are deleted should be added to the `deleted_usernames` table or not.
