### ISSUE TITLE
"Save" description for the completely anonymous emails should be more obvious

### ISSUE THREAD

**Issue by CouldBeThis** [anonaddy/anonaddy#2]
I'm new to this end of software but have been trying to learn about participating in the way which I am able, which is this. If I did anything at all incorrectly please tell me so I can learn. 

Love this project. Almost too good to be true. Assuming reasonable prices I plan to subscribe when the option is available. 

Anyway here is a piece of minor feedback:

When saving the description I didn't realize you had to click anything. I guess everything just got lost. I'll have to go back and sort this out. I think if the icon changed colour to red of was highlighted in some other way it would be less easily missed for dumdumbs like myself. 

as it is
![Screen Shot 2019-08-04 at 1 59 01 AM](https://user-images.githubusercontent.com/53547181/62420154-ab13ee00-b65b-11e9-9645-55145b2ccd20.png)

red save button (crude)
![Screen Shot 2019-08-04 at 1 59 01 AM](https://user-images.githubusercontent.com/53547181/62420181-03e38680-b65c-11e9-8b47-cb414e8ccd17.png)

adding a box would also help but the CSS might be more annoying to code.
![Screen Shot 2019-08-04 at 1 59 01 AM](https://user-images.githubusercontent.com/53547181/62420224-bc112f00-b65c-11e9-9b18-b6ef38627baa.png)

There are other ways to skin this cat.

**Comment by anonaddy** [comment]
Hi, thanks a lot for your feedback! 

Really happy to hear you are finding it useful.

I've just updated to colours of the 'save' and 'close' icons when editing the descriptions to make them more obvious. I might change the way descriptions are edited in the future to make this more clear (perhaps edited in a modal?).

Please let me know if you have any others suggestions.
