### ISSUE TITLE
Encrypt replies to forwarded emails?

### ISSUE THREAD

**Issue by chiraag-nataraj** [anonaddy/anonaddy#20]
Hello!

Firstly, I love this service! I use ProtonMail and have PGP-encrypted emails set up using my PM keys. I'd also like to encrypt any replies I happen to send, but I'm not sure how I should set that up. Any help would be greatly appreciated!

**Comment by anonaddy** [comment]
Hi, this is something I'm looking into, so that if a reply comes in that is already encrypted it can be sent on as expected.

I'll keep you updated on progress here.

**Comment by anonaddy** [comment]
@chiraag-nataraj I believe I have sorted this issue, please could you give it a try and let me know what you think? Just encrypt the reply in ProtonMail as you would normally and send it.

**Comment by chiraag-nataraj** [comment]
Which key should I encrypt to? The same one I use to verify signatures?

**Comment by willbrowningme** [comment]
@chiraag-nataraj If you were replying to "sender@example.com" then you would encrypt your reply with their public GPG key (which they would either have sent you or you got from a keyserver).

Then only they can decrypt the reply using their corresponding private key.

**Comment by chiraag-nataraj** [comment]
Oh, I see. I was more thinking about encrypting till the anonaddy server, since most of my contacts don't use GPG :/ I was sort of thinking of this as a mirror of the "encrypt to me" functionality, since in the absence of widespread GPG usage, encrypting to at least the anonaddy server is better than no encryption-at-rest at all. 

Under the current scenario, there is an asymmetry between sending and receiving, where I can ensure all of the emails sent to me are encrypted at the last leg (anonaddy -> my email address), but I can't ensure the first leg of the reply is encrypted as well (my email address -> anonaddy).

**Comment by willbrowningme** [comment]
@chiraag-nataraj so would the purpose of this be to hide your replies (sent messages) from your email provider?

So you are suggesting encrypting a reply using the mailer@anonaddy.me public key that is then decrypted when it arrives at the AnonAddy server and sent on to the sender in plain text?

It's an interesting suggestion but I'm not sure many users would use this?

**Comment by nodecorum** [comment]
I would use this!

**Comment by willbrowningme** [comment]
I'll look a bit more into this. Just thinking about the potential overhead as it would need to check by trying to decrypt every encyprted reply/send from that comes through the server with the "mailer@anonaddy.me" key. Then if successful to decrypt it and send it on and if unsuccessful leave as is.

**Comment by nodecorum** [comment]
> I'll look a bit more into this. Just thinking about the potential overhead as it would need to check by trying to decrypt every encyprted reply/send from that comes through the server with the "mailer@anonaddy.me" key. Then if successful to decrypt it and send it on and if unsuccessful leave as is.

I don't know your flow, but could you not keep track of which aliases have uploaded a private key. I doubt too many would do that so the overhead would be relatively smsll.

**Comment by willbrowningme** [comment]
I don't think I would create a new private key for every alias as this could make the keyring huge.

I would just ask users to encrypt their replies with the "mailer@anonaddy.me" public key and then use that private key to decrypt.

**Comment by nodecorum** [comment]
You already have a public key per alias for the outgoing mail. Would adding a private key per (reverse) alias kill the keyring? I would not expect everyone to use this - especially if you make the user responsible for generating and managing their own keys.

**Comment by willbrowningme** [comment]
The public keys are currently per recipient (where the email is forwarded to) and not per alias.

A forwarded email is encrypted for any alias where the alias has a recipient which has a public key attached and encyption is enabled.

It would be a huge security risk if users were able to upload their own private key to the AnonAddy server in order to decrypt their own replies.

**Comment by nodecorum** [comment]
The private key would only be for the alias - that's not a key that would be used anywhere else and would only be useful to decrypt a mail which is being forwarded unencrypted - I don't see the "huge security risk" in that scenario.
