### ISSUE TITLE
Unable to delete or forget last alias in the list

### ISSUE THREAD

**Issue by fazy** [anonaddy/anonaddy#204]
I have six active aliases, all with the same custom domain and recipient (domain's). The three dots menu is the same for all except the last one in the list. The last one in the list has only "Send From" and not "Delete" or "Forget" like the others.

At first I couldn't figure out what's different about this one. Having it active or inactive and refreshing made no difference.

Now I find that if I enter a substring of the alias in the search box so that it's the only one, I have the other options. Seems like this could be a UI bug?

**Comment by willbrowningme** [comment]
Hmm, that is strange. Have you tried clearing your browser's cache or using a different browser?

**Comment by fazy** [comment]
I figured it out in the end, it was a mixture of user error and a UI issue. ;) 

When the list reaches the bottom of the space, no scrollbar:

![image](https://user-images.githubusercontent.com/1623556/136256110-e758bb89-d6b5-469d-97cf-98d30926bcc5.png)

If I then click the menu dots, the menu items are hidden but I didn't notice the scrollbar:

![image](https://user-images.githubusercontent.com/1623556/136256328-1de03137-5248-4f9d-b092-d6f79dcc0376.png)

Sorry about that.
