### ISSUE TITLE
[Feature request] Additions to the "Failed deliveries" tab

### ISSUE THREAD

**Issue by Coderdude112** [anonaddy/anonaddy#209]
Recently I had multiple emails return the status deferred, they were eventually sent through once the receiving server let some time pass, but in the between time I was super confused (Until looking at the server logs) would there be a way to implement a notification on the dashboard that an email is deferred potentially under a email status tab or one similar to the "Failed deliveries" tab? I feel like this would help users know what's going on and be very helpful.

Thanks!

**Comment by willbrowningme** [comment]
I'm afraid I don't currently have any plans to add information on deferred emails, this is all handled by Postfix and would likely be tricky to try to periodically parse and display the outgoing mail queue.
