### ISSUE TITLE
In-line pictures won't load

### ISSUE THREAD

**Issue by froman753** [anonaddy/anonaddy#210]
I had previous used other masking services that didn't seem to have this issue where in-line pictures won't load. Particularly weekly ads from Micro Center and also Informed Delivery from USPS. I had thought it could have been due to having encryption enabled, but nothing seemed to change after disabling it. With the informed delivery emails, the pictures are included as separate attachments that I have to download and don't automatically load in-line like they had with previous masking services. For reference, I am using Protonmail.

Does any one else have this issue?

**Comment by willbrowningme** [comment]
This should be fixed in the latest [release](https://github.com/anonaddy/anonaddy/releases/tag/v0.8.7)!
