### ISSUE TITLE
[Feature Request] Sort and filter aliases by domain name

### ISSUE THREAD

**Issue by samirgunic** [anonaddy/anonaddy#211]
At the moment, I can sort aliases by the "Alias" column, regardless of what domain name they are using. Given the aliases `01234@omega.com` and `56789@alpha.com` they would appear in ascending alphabetical order as follows.

```
01234@omega.com
56789@alpha.com
```

I would like the `alpha.com` domain to appear on top of the `omega.com` domain. In this very simple example with only two aliases, this can be easily achieved by reversing the order (from ascending to descending). But as you can imagine, it gets more complicated as you add more and more aliases with varying names.

I propose that you add a "Domain" column to enable sorting by domain name.

```
Alias            Domain ↑
==========================
56789@alpha.com  alpha.com
01234@omega.com  omega.com
```

In addition, I propose that you add an option to filter aliases by their domain name (next to the "Hide Deleted", "Show Deleted", "Deleted Only" filters).

This would allow us to more easily locate the aliases of interest in a systematic fashion where we can view them all at a glance rather than doing one by one search for each of them. Like for example, I am currently replacing my aliases that use the shared domain name `anonaddy.me` with new aliases using my own custom domain. A simple feature like sorting and filtering based on domain name would make this – otherwise painstaking and tedious – process much easier for me.

**Comment by willbrowningme** [comment]
You can now sort aliases by their domain name, you can also click through on any custom domain to see all the aliases that belong to it.

**Comment by samirgunic** [comment]
Much appreciated! Looking forward to using the new feature.
