### ISSUE TITLE
[Feature Request] Increase characters allowed in alias descriptions

### ISSUE THREAD

**Issue by samirgunic** [anonaddy/anonaddy#212]
Currently there is a 100 character limit for the alias description.

![anonaddy-character-limit](https://user-images.githubusercontent.com/3742529/136999371-4e41980d-bf58-4c4d-925e-c2febe0fb14c.png)

I propose an increase of characters allowed (lowering the limit) to 200 characters.

**Comment by willbrowningme** [comment]
Added in the latest release [v0.8.6](https://github.com/anonaddy/anonaddy/releases/tag/v0.8.6).
