### ISSUE TITLE
Don't add plaintext if original email didn't have it

### ISSUE THREAD

**Issue by ypsu** [anonaddy/anonaddy#221]
Sometimes I send HTML only email without the plaintext alternative. However anonaddy force-adds a plaintext attachment with empty contents if I do that. That looks weird in plaintext clients that prefer the plaintext version. This happens both when receiving and when sending emails.

Would it be possible for anonaddy to detect the lack of plaintext attachment and omit adding its own plaintext attachment in that case? Thanks! Awesome product!

**Comment by willbrowningme** [comment]
Just sorted this, thanks again!
