### ISSUE TITLE
[Feature Request] Add recovery code requirement when using hardware keys/UF2 for 2FA

### ISSUE THREAD

**Issue by lazytownfan** [anonaddy/anonaddy#223]
I'd like to request having a single recovery code to log in for "emergency" use when using hardware keys/UF2 for two-factor authentication, just like when using TOTP for 2FA (Google Authenticator or Aegis).

I'm aware that the proper way to use 2FA exclusively with hardware keys is to have 2 (or more) keys, the first being the primary key and the second (or beyond) keys are backup(s). However, nearly every online service I can think of requires you to copy down a recovery code (or multiple codes) when using UF2 compatible hardware keys.

I would like to prevent users (including myself) from ending up in the worst situation (with UF2 security keys): loosing all hardware keys, with no other allowed method to get back into your own Anonaddy account.

_Edit_: I was about to ask for using TOTP and UF2 at the same time, but I noticed it's a milestone on [the roadmap](https://github.com/anonaddy/anonaddy/projects/1). Hopefully, this can be a stepping stone towards that milestone.

**Comment by willbrowningme** [comment]
A backup (recovery code) is already displayed to you once you enable 2FA with U2F or TOTP. 

It is shown at the top of the settings page in an orange banner with the following text:

> **IMPORTANT** 
2FA enabled successfully. Please **make a copy of your backup code below.** If you have an old backup code saved **you must update it with this one.** If you lose your 2FA device you can use this backup code to disable 2FA on your account. **This is the only time this code will be displayed, so be sure not to lose it!**

If you missed that message then you will need to disable then re-enable 2FA to see it again.

**Comment by lazytownfan** [comment]
Sorry about that, I'll fix 2FA on my account ASAP!
