### ISSUE TITLE
Policy in the event of a request for logging?

### ISSUE THREAD

**Issue by chiraag-nataraj** [anonaddy/anonaddy#23]
Hi! I really love this service, and I don't ever anticipate this happening to me. But I'm curious what @anonaddy's response would be if a nation-state came to you and asked you to save copies of all emails sent through your service, either for _everyone_ or only a specific user.

**Comment by anonaddy** [comment]
Thanks! In the event of something like this happening I would likely follow Lavabit's example and shut down the service rather than snoop on users' emails.

I plan to add a warrant canary and/or transparency report to the site soon too.

**Comment by MrSuddenJoy** [comment]
@anonaddy: 4 years has passed and?
