### ISSUE TITLE
[Feature Request] Obtain new recovery code while keeping current 2FA method

### ISSUE THREAD

**Issue by lazytownfan** [anonaddy/anonaddy#231]
I would like to know if it's possible to add an option in Anonaddy's settings so that you to create a new recovery code while still keeping your current 2FA method active.

Currently, as mentioned in #223, you must completely turn off 2FA (turn off TOTP or remove every hardware key for UF2) if one wants to change the recovery code. This would be unnecessarily roundabout in the case that you still have your current 2FA method but lost the recovery code. As soon as possible after the loss of just the recovery code, It would be more efficient to allow users to log in with 2FA as normal and directly reset the view-once recovery code.

What I'm describing is similar to other online sites with 2FA recovery codes, such as Microsoft as an example. While also Microsoft Accounts only allows you to see your recovery code once, it additionally lets you create a new recovery code while logged in, explicitly stating that creating a new recovery code will invalidate the prior recovery code.

**Comment by willbrowningme** [comment]
Good idea, I'll add this as soon as I can.

**Comment by willbrowningme** [comment]
Added this in the latest commit, thanks!
