### ISSUE TITLE
[Feature Request] Registration token

### ISSUE THREAD

**Issue by pacroix** [anonaddy/anonaddy#233]
I'm self hosting the application and want to make it available to a few well trusted friends and family members. 
Currently the only way to create new users is through the registration form, but I don't want to make it public because then everyone could create an account. Would it be possible to add a config entry with a string that you have to provide when registering, that you can share with people who should be allowed to register?

**Comment by willbrowningme** [comment]
There is already a command that allows you to create new users from the CLI.

```bash
php artisan anonaddy:create-user {username} {email}
```

e.g. 

```bash
php artisan anonaddy:create-user johndoe john@doe.com
```

This will create a user with the password set as their user_id, they can then login and update their password.

So you can send them these details and tell them to reset their password when they first login.
