### ISSUE TITLE
Adding Wiki section for this project

### ISSUE THREAD

**Issue by Mr-Sheep** [anonaddy/anonaddy#236]
It is very nice to have a very [detailed walk-through](https://github.com/anonaddy/anonaddy/blob/master/SELF-HOSTING.md) for self-hosting anonaddy. 

But it now only has documentation for Ubuntu; it would be very nice to have a wiki page (maybe categorized by distros) for this project.

**Comment by willbrowningme** [comment]
I'm afraid I don't currently have any plans to write self-hosting instructions for any other linux distributions since I am only familiar with Ubuntu. You could try using the [Docker image](https://github.com/anonaddy/docker) instead.
