### ISSUE TITLE
Include ability to restrict which domains can send email to an alias

### ISSUE THREAD

**Issue by chiraag-nataraj** [anonaddy/anonaddy#24]
This would be an interesting extension to the current enable/disable system, where the user could select which domains (possibly with wildcards) are allowed to email a certain alias. All other emails to that alias are dropped.

Thoughts?

**Comment by anonaddy** [comment]
Yes that is a great idea and definitely something I'd like to implement.

I will probably add a new "Rules" page with global and per alias rules to allow users to set up options like this.

It's on my to do list. I'll update this issue with any progress.

**Comment by willbrowningme** [comment]
This is now possible using the new rules system which is currently being beta tested.
