### ISSUE TITLE
Custom Domain - Verification Fails

### ISSUE THREAD

**Issue by brink668** [anonaddy/anonaddy#240]
Custom Domain - Verification Fails if you add another custom domain without refreshing the page first.

Essentially the old verification record will show instead of a new one.  What probably should happen is as soon as the verification check validates it should create a new verification entry.

Not a big deal, but for other users this may be confusing / not realized

**Comment by willbrowningme** [comment]
Thanks, I am aware of this issue and will sort it shortly.

**Comment by willbrowningme** [comment]
The page will now be reloaded so that you get the new correct TXT verification value.
