### ISSUE TITLE
Alias-specific subject replacement?

### ISSUE THREAD

**Issue by chiraag-nataraj** [anonaddy/anonaddy#25]
The main use-case is that I'd like the mailing lists I sign up with to retain the original subject while hiding the subject for all other aliases (and by default).

Thoughts?

**Comment by anonaddy** [comment]
Another good idea, I'll try to add this as an option for the "Rules" page when I implement it so that you can do:

If sender is *@newsletter.com then replace subject to "XYZ" etc.

**Comment by willbrowningme** [comment]
This is now possible with the new rules system, I'll also be adding placeholders for subject replacement.
