### ISSUE TITLE
Is gmail blocking emails to anonaddy?

### ISSUE THREAD

**Issue by mikejavier** [anonaddy/anonaddy#254]
Hey guys, how are you?

so, today I try to send a lot of email to test from my gmail and from gmail of my work and these emails aren' t sent.
when I tried to send from other service, the emails arrived fine. Is there a problem with gmail?

thank you!

**Comment by ccorneli** [comment]
I just tested and something does seem amiss....
This is what I found:

I sent FROM: a gmail account from my computer TO:  an alias I created on the AA site 
with format   [randomstring]@[myid].anonaddy.com
Logging into gmail.com web page, I see it in my sent folder,  
but  still after about 20 min AA dashboard still shows forwarded = 0 and nothing has arrived.

Then I sent from the gmail web page to two email addresses 
1. my iCloud account, 2. an existing alias on my own hosted domain.
Although both were sent as part of the same message, only the iCloud email arrived.

All email from other sources seem to be flowing through fine.

Note: I think would help to debug in this case to keep a register of "last used" to show that there has been recent traffic.  (Perhaps as an setting that can be turned off/on for the extreme privacy folks.)

**Comment by willbrowningme** [comment]
Thanks, it does seem that there was a temporary lookup error that only affected IPv6 connections which is why Google was affected in this instance. These messages will have been deferred so should start arriving now as the issue has been resolved. Let me know if you are still having issues.

**Comment by willbrowningme** [comment]
@ccorneli I agree about the last used addition to the aliases table, I will add this at some point and allow the user to opt-in to it.
