### ISSUE TITLE
[Feature Request] SAML / Oauth SSO capabilities and User Provisioning (SCIM)

### ISSUE THREAD

**Issue by timomayer** [anonaddy/anonaddy#255]
To use AnonAddy in a corporate environment it would be necessary to provide SAML or OAuth connection and SCIM support for user provisioning. Can maybe done by using: https://simplesamlphp.org/

**Comment by alexanderadam** [comment]
May I ask why you closed this issue?
Is something like OpenID Connect/OAuth already supported?

**Comment by willbrowningme** [comment]
@alexanderadam I believe because it is a duplicate of #248 

I'm afraid I do not have any plans at this time to implement SSO.

**Comment by disconn3ct** [comment]
I understand the conflict with the paid service, but fwiw my use case for SSO (via oidc, keycloak) is far from corporate. I just run services for family, and the fewer passwords to remember (and 2fa and logins and site addresses and..) the easier my life is by far :smile: SSO means not having to keep a (corporate) checklist by my computer for password rotations, etc.
