### ISSUE TITLE
Feature Request: Fake Bounce-Back for an alias

### ISSUE THREAD

**Issue by ccorneli** [anonaddy/anonaddy#256]
I think it would be helpful to provide a way to fake a bounce-back email.
I realize this really needs to be done from client side, but wondering if there is a way AA can easily support that feature.  Perhaps by constructing a special reply-to email which handles the response and reformatting accordingly. 

As an example, 
I have a catch-all domain and a spammer sent to a random alias they generated, and sent to my domain.  I would like to be able to bounce it back as invalid, rather than letting them know it was received.  In my case it was someone marketing their services to help with the website at my domain (which doesn't actually exist).      

As a reference, (Apple used to do it..Not clear why they stopped) 
https://www.lifewire.com/bounce-message-to-sender-os-x-mail-1172786
https://discussions.apple.com/thread/252591528

And some similar ideas here:
https://help.blocksender.io/how-to-bounce-back-emails
https://gmail-tips.blogspot.com/2012/01/blocking-senders.html
https://www.gigxp.com/bounce-back-emails-from-unwanted-senders/

**Comment by willbrowningme** [comment]
Not sure if this will be possible to implement due to the way AnonAddy is setup. Once Postfix pipes the message to the application it is considered a successful delivery, as far as I can see it isn't possible to implement this directly in Postfix.

**Comment by willbrowningme** [comment]
Closing this as it is already possible to simply turn off catch-all for your domain and that will bounce any attempts to send to an alias that does not exist and I do not believe there is any way to send a fake bounce response with the current setup.
