### ISSUE TITLE
Automatic subject replacement in replies?

### ISSUE THREAD

**Issue by chiraag-nataraj** [anonaddy/anonaddy#26]
As an alternative to #25, could there be an option (probably alias-specific) to back-substitute the subject that was erased on delivery when I reply to the email?

**Comment by anonaddy** [comment]
Hmm, I'm just trying to think how this would work as I don't save any copy of the original subject on the server.

If you have the banner information included on forwarded emails and the subject is replaced then the original subject is shown in the message body (encrypted if enabled). So I think the best option would be just to change the replaced subject back to the original when replying.

**Comment by chiraag-nataraj** [comment]
Presumably, if the banner that you insert is left in the replied email, then you could parse that and figure out the original subject? But I think #25 is a cleaner way to do this anyway, and more flexible to boot. I'll close this for now.
