### ISSUE TITLE
Failed deliveries should show up as blocked instead of forwarded

### ISSUE THREAD

**Issue by Jayto1** [anonaddy/anonaddy#264]
I received a spam email recently and noticed the alias has (1) forwarded instead of (1) blocked and thought since the email never went through it would make more sense to put it in the blocked category.

**Comment by willbrowningme** [comment]
So do you mean it was a failed delivery that was rejected by your recipient because it was "spam"?

**Comment by Jayto1** [comment]
Sorry I mean it was a spam email that I received that was blocked, but showed up as forwarded in my dashboard.

**Comment by willbrowningme** [comment]
How did you receive the email if it was blocked?

**Comment by Jayto1** [comment]
Poor wording sorry, received as in it was sent to me, the spam filters blocked it though so it showed up in my failed deliveries. The thing that was weird to me was even though it was blocked it showed up as received in my dashboard count. Please let me know if anything I'm saying here doesn't really add up lol I'm trying my best to explain it.

**Comment by willbrowningme** [comment]
Okay, I understand now. I've added a line of code to decrement the forward count for that alias in the bounce handler which I'll push live soon.

**Comment by Jayto1** [comment]
@willbrowningme I just found out this issue happens when you send an email from your alias too. If you send an email from your alias and it fails the **sent** column in the dashboard goes up by 1.

**Comment by willbrowningme** [comment]
@Jayto1 I've sorted this now, will push it live shortly.

**Comment by Jayto1** [comment]
@willbrowningme Awesome, thanks Will 👍
