### ISSUE TITLE
Is there a technical limit to the number of aliases per user (or per deployment)?

### ISSUE THREAD

**Issue by alexaka1** [anonaddy/anonaddy#268]
Just out of curiosity. 
The unlimited™ wording is of course like the all you can eat buffet, within reason. I took a quick peak to the code and saw the database uses UUID for the keys, which is a lot... But I'm curious what limitation would the user encounter first? 

I'm assuming the alias counters on the website are not BigIntegers, and aren't even 64 bit integers, so a 32 bit integers worth of aliases would probably start doing funny business to the UI, not to mention the APIs, which probably get the alias # as a single response, and don't gather all the UUIDs and count it locally. There is also the actual alias uniqueness, I'm not sure if a character limit is set, but say 16 characters would easily allow more than 32 bits of aliases. 
(Of course assuming storage is unlimited™ too.)

**Comment by willbrowningme** [comment]
The technical limit that a user would hit is likely the number of aliases per hour that can be created. For the Pro plan this is 50 per hour which means it would take a full year to create 438,000 aliases. This can be changed when self-hosting.

The alias uniqueness is only applicable to shared domain aliases, the different formats for these (UUID, random characters, random words) have enough entropy to avoid any collisions in my opinion.
