### ISSUE TITLE
[Feature Request] Option to disable alias descriptions in outgoing mail

### ISSUE THREAD

**Issue by samirgunic** [anonaddy/anonaddy#269]
Currently, there seems to be no way to disable alias descriptions in outgoing mail.

A 20 character description is a minor problem:

> This email was sent to alias@anonaddy.me (**Lorem ipsum vivamus.**) from noreply@example.com and has been forwarded by AnonAddy.

But a 200 character description is a major problem:

> This email was sent to alias@anonaddy.me (**Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nunc mi, convallis feugiat nunc et, molestie pretium eros. Aliquam posuere metus in vulputate feugiat. Ut ut fermentum dui. Nunc libero.**) from noreply@example.com and has been forwarded by AnonAddy.

As you can see, the longer the description is, the more it gets in the way when you receive that e-mail. You can fit a decently sized paragraph in there, so you may need to scroll a bit before the actual content of the e-mail begins and this adds unnecessary noise.

For these reasons, I would like to see an option to disable these descriptions.

**Comment by willbrowningme** [comment]
Good point, I think perhaps a setting to let users write their own custom text using placeholders would be the best option e.g.

`This email was sent to {{aliasEmail}} from {{sender}}`

In the meantime you can disable the banner information entirely in your account settings.

**Comment by samirgunic** [comment]
I didn't know you can disable the banner entirely. This is good enough for me. Thanks!

It's also possible to relocate the banner to the bottom which is a nice middle ground. It solves the issue of having to scroll down before the content of the e-mail begins. Perhaps placing it at the bottom should be the default setting? I think it would make more sense. It would be in line with how newsletters for example place their "unsubscribe" links at the bottom. Even GitHub notifications have these links at the bottom. It would definitely be a good fit for alias deactivation links: "Click here to deactivate this alias"

Regarding placeholders, I think that would be even better. That way you could totally customize it and omit this part for example: "has been forwarded by AnonAddy". You don't necessarily need to be reminded what service you're using. Also, in case you're self-hosting for example, you probably want to use the name of your own AnonAddy instance.

**Comment by willbrowningme** [comment]
Thanks for the suggestions, I'm closing this issue for now since this has been added to the roadmap [here](https://github.com/anonaddy/anonaddy/projects/1#card-78200573).
