### ISSUE TITLE
U2F Support

### ISSUE THREAD

**Issue by IceCryptonym** [anonaddy/anonaddy#27]
Having U2F support would be another great two factor authentication to have. There are some WebAuthn implementations in PHP. https://github.com/lbuchs/WebAuthn
If you need someone to help test, I am willing.

**Comment by anonaddy** [comment]
Thanks, that is something I would like to add. I'll have a look at that package and see if I can implement it.

**Comment by willbrowningme** [comment]
@IceCryptonym I've just added U2F support, please feel free to try it out and if you have any feedback I'd love to hear it.
