### ISSUE TITLE
Possible rspamd permission issue in SELF-HOSTING.md

### ISSUE THREAD

**Issue by makua-bernal** [anonaddy/anonaddy#272]
I ran into an issue when moving from OpenDKIM and OpenDMARC to Rspamd. A few instructions in the `SELF-HOSTING.md` file seem to create files owned by root, such as
```
sudo cp /etc/rspamd/local.d/dkim_signing.conf /etc/rspamd/local.d/arc.conf
```
and
```
echo "enabled = false;" | sudo tee -a /etc/rspamd/override.d/module_name.conf
```
This results in errors similar to 
```
rspamd_config_read: failed to load config: ucl parser error: cannot open file /etc/rspamd/local.d/arc.conf: Permission denied
```
when `rspamd.service` is run as the `_rspamd` user, which I think is done by default. Rspamd fails to start and errors like `connect to Milter service inet:localhost:11332: Connection refused` appear in `/var/log/mail.log` when sending from a recipient address, which led to AnonAddy thinking they were spoofed.

**Comment by willbrowningme** [comment]
All files in the `/etc/rspamd` directory are owned by `root` with group `root`. The Rspamd main process should start as root and then drops privileges. Have you checked for any solutions on the [Rspamd repo](https://github.com/rspamd/rspamd/issues?q=is%3Aissue+root+permission)?

**Comment by makua-bernal** [comment]
I didn't see anything there other than a few older solved issues ([1](https://github.com/rspamd/rspamd/issues/3131), [2](https://github.com/rspamd/rspamd/issues/1996)) related to permission errors. It seems like they say the files should be owned by `_rspamd:_rspamd`, which is what I did to solve it. Is your `rspamd.service` also using `User=_rspamd`?

**Comment by willbrowningme** [comment]
Yes the rspamd.service is run by `_rspamd`. Following the exact instructions in the self-hosting instructions worked for me with no issues. Closing this issue, since it seems you've resolved it now.
