### ISSUE TITLE
My email client has a fit when receiving encrypted mail from aliases

### ISSUE THREAD

**Issue by CaptainFrosty** [anonaddy/anonaddy#273]
That's the only way I know how to describe it. I had to turn encryption off. Only the header will load on the screen and it blinks very fast. When I get a chance I'll try sending one with the debug logs on and see if I can uncover anything.

I'm using eM Client on Windows. The key is stored in it.

**Comment by willbrowningme** [comment]
Are you sure this isn't just an issue with eM Client?

Have you tested sending an encrypted message not through AnonAddy to see if the result is the same?

**Comment by willbrowningme** [comment]
Closing this as I don't think it's related to AnonAddy.

**Comment by CaptainFrosty** [comment]
@willbrowningme The blinking stopped thankfully when I updated it. Probably a database issue; this client seems prone to them. The pgp is working normally now, so that's good. I do get this message:

![image](https://user-images.githubusercontent.com/8523498/158072364-16cdca7f-e739-4b2a-aec2-552ee5ba4753.png)

But it doesn't seem to affect anything.

**Comment by CaptainFrosty** [comment]
And no, it doesn't happen on messages outside of the server, I made sure of that. Odd that the message itself checks out fine...it's only the signature.

**Comment by willbrowningme** [comment]
Glad you sorted it. Don't worry about the cerificate signature warning, it's a known issue - https://github.com/anonaddy/anonaddy/issues/164

It's because the signing key has identity `mailer@anonaddy.me` which doesn't exactly match the identity of the alias xyz@anonaddy.me etc.

**Comment by willbrowningme** [comment]
The signature identity mismatch warning is only present on forwarded messages so nobody else will see this.

If you want to send an encrypted email to someone from an AnonAddy alias then you need to encrypt it with their public key and send it as you normally would.

You don't want to sign it with your real email's private key because this would reveal your real email to them. So you can either not sign the message at all, or create a private key for that exact alias and sign it with that, so the identities match.

**Comment by CaptainFrosty** [comment]
@willbrowningme That's what I was thinking, to create a few aliases exclusively for pgp and generate keys for those. It's kind of a pain that pgp uses email addresses for identity purposes rather than some other mechanism, but that's what keeps it decentralized I guess. My client supports aliases, so maybe I can get rid of the warning by setting a policy for the alias.
