### ISSUE TITLE
Sending from alias does not work when sending from same postfix/rspam as anonaddy instance

### ISSUE THREAD

**Issue by returntoreality** [anonaddy/anonaddy#275]
Anonaddy requires DMARC_POLICY_ALLOW, which is not generated in rspamd for local or authenticated senders since SPF is not checked. This means that local or authenticated sender cannot send via their aliases. As a workaround I changed the line in milter_headers.conf to `if (task:has_symbol('DMARC_POLICY_ALLOW') or task:has_symbol('DKIM_SIGNED')) then`. This whitelists any locally DKIM signed domains as well.

**Comment by makua-bernal** [comment]
Can you provide more information and an example of what you're trying to do?

**Comment by returntoreality** [comment]
My setup is the following:
I have a mailserver for the maildomain.net and I send mail for a.maildomain.net to annonaddy. The annonaddy user register with their maildomain.net and can then use a.maildomain.net to receive mails for aliases. What does not work is sending from an alias using the "Send From" feature where you get a destination address like myalias+destinaton=destinationdomain.net@a.maildomain.net. When trying to send an email to this address, the user gets an email "Someone tried to send mails from your alias" (or something along those lines). Since sending from an alias requires a valid DMARC and the policy need to allow this sender. The problem is, that the check for a valid DMARC policy in rspam requires that both SPF and DKIM were checked (which is what you would want). When receiving emails directly from an authenticated user, the SPF check is not done (which is also what you would want) and in turn the DMARC policy is not checked. And because the header for dmarc-policy-allow is not set by rspamd, anonaddy rejects the forwarding.

**Comment by makua-bernal** [comment]
To make sure I understand:

- The domain you used in place of `example.com` in the SELF-HOSTING guide is `a.maildomain.net`
- You get an error when trying to send from an alias with this domain e.g. `myalias+destinaton=destinationdomain.net@a.maildomain.net`
- This error takes the form of AnonAddy spoof warning email `Someone tried to send mails from your alias`

Is this correct?

**Comment by returntoreality** [comment]
Correct

**Comment by makua-bernal** [comment]
Okay a few more questions:
- Did you recently upgrade from OpenDKIM and OpenDMARC to Rspamd?
- Where is the email to `myalias+destinaton=destinationdomain.net@a.maildomain.net` being sent from?

**Comment by willbrowningme** [comment]
Are you self-hosting AnonAddy or talking about the hosted app.anonaddy.com?

**Comment by returntoreality** [comment]
> Did you recently upgrade from OpenDKIM and OpenDMARC to Rspamd?
no, only used rspam so far
> Where is the email to myalias+destinaton=destinationdomain.net@a.maildomain.net being sent from?
Using submission/SMTP with authentication to the same postfix that also handles the annonaddy mails
> Are you self-hosting AnonAddy or talking about the hosted app.anonaddy.com?
This is a salf-hosted instance

**Comment by willbrowningme** [comment]
@returntoreality thanks for the info, I didn't anticipate people would be sending from the same mail server as an authenticated user. I'll look into updating the docs and config to allow for that.

**Comment by willbrowningme** [comment]
Is this still an issue?

**Comment by ilyadel** [comment]
> Is this still an issue?

I have this issue on my fresh selfhosted instance (docker last release 1.0.9)
