### ISSUE TITLE
Selfhosted - user subdomains are being bounced

### ISSUE THREAD

**Issue by lgwapnitsky** [anonaddy/anonaddy#276]
My domain is anon.blingblong.com. (not really). Emails to aliases there go fine.

Aliases at dumdum.anon.blingblong.com are being rejected. Dumdum is the user.

I'm using a pcre file for mydestinations

**Comment by willbrowningme** [comment]
Did you read the release notes for the latest release [v0.11.0](https://github.com/anonaddy/anonaddy/releases/tag/v0.11.0)?

About the username column from the users table being moved to the usernames table?

**Comment by lgwapnitsky** [comment]
Got it. Thanks. Thought i had it, but will verify tomorrow

**Comment by lgwapnitsky** [comment]
Yes, sorry. Been dealing with other personal stuff
