### ISSUE TITLE
failed delivery code column too long causing SQL error

### ISSUE THREAD

**Issue by makua-bernal** [anonaddy/anonaddy#277]
This happened in a self-hosted v10.1 instance when trying to send to a google workspace address' alias.

I sent an email to a google workspace address' alias `bbbbb+aaaaa@xxxxxxxxx.xxxx.xx` instead of `aaaaa+bbbbb@xxxxxxxxx.xxxx.xx` causing a failed delivery.

The beginning of the error in the AnonAddy storage logs looks like this
```
production.ERROR: SQLSTATE[xxxxx]: String data, right truncated: 1406 Data too long for column 'code' at row 1`
(SQL: insert into failed_deliveries (recipient_id, alias_id, bounce_type, remote_mta, sender, email_type, status, code, attempted_at, user_id, id, updated_at, created_at)
...
```

The contents of the code column were
```
smtp; 550-5.1.1 The email account that you tried to reach does     not exist. Please try 550-5.1.1 double-checking the recipient's email     address for typos or 550-5.1.1 		unnecessary spaces. Learn more at 550 5.1.1     https://support.google.com/mail/?p=NoSuchUser     xxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xx - gsmtp
```

**Comment by willbrowningme** [comment]
The diagnostic code is already limited in `ReceiveEmail.php` - https://github.com/anonaddy/anonaddy/blob/master/app/Console/Commands/ReceiveEmail.php#L321

What version of MariaDB are you using and what charset?

**Comment by willbrowningme** [comment]
Is the distribution output from that command `Distrib 10.5.15-MariaDB`?

**Comment by makua-bernal** [comment]
Yes
