### ISSUE TITLE
Verification string wrong after adding domains in sequence

### ISSUE THREAD

**Issue by makua-bernal** [anonaddy/anonaddy#278]
In v11.1 after adding a domain the displayed verification string doesn't get updated until the page is refreshed.

To reproduce:

- Click `Add Custom Domain`
- Enter domain `mysite.com`
- Add a verification record e.g. `TXT @ aa-verify=71sf5v9m0txvb2fkccxpmrekejut2ryhoj4irq3y` to domain
- Click `Add Domain`
- Add MX, TXT spf, TXT dmarc, CNAME dkim records to domain
- Click `Check Records` (closing modal successfully)
- Click `Add Custom Domain`
- verification record shown is still `TXT @ aa-verify=71sf5v9m0txvb2fkccxpmrekejut2ryhoj4irq3y` and unchanged

**Comment by willbrowningme** [comment]
This has been fixed in [this commit](https://github.com/anonaddy/anonaddy/commit/dfb78096205c37b31bfc1aafd136d6b84cd4a481) I just haven't pushed a new release for it yet.

I will do shortly.
