### ISSUE TITLE
service status announcements needed, ideally via Mastodon or gnusocial; website down ATM

### ISSUE THREAD

**Issue by bruceleerabbit** [anonaddy/anonaddy#281]
The website https://anonaddy.me redirects to https://anonaddy.com, and that site is down.  Ungoogled Chromium gives:

“
> This site can’t be reachedThe webpage at https://anonaddy.com/ might be temporarily down or it may have moved permanently to a new web address.
> ERR_HTTP2_PROTOCOL_ERROR

”
This bug report is not about the downtime at the current moment, but about giving users a way to get status notices in the future.  It would be useful if Anonaddy had a federated (Mastodon, GNU Social, or the like) account that could be followed.  It would also be a way for users to microblog to the admin when loss of service availability is first discovered by a user.  It’s particularly useful to announce planned downtime (e.g. prior to migrations) so that users can coordinate their logins.

**Comment by willbrowningme** [comment]
There was no downtime for anonaddy.com recently that I was aware of.

The current [status page](https://status.anonaddy.com/) has an [RSS feed](https://status.anonaddy.com/rss) that you can subscribe to, this would be the best way to get updates. I also post updates regarding status on Twitter/Reddit.

You can access the Twitter page using [Nitter](https://nitter.net/AnonAddy) if you'd prefer.

Going forward I will send out an email to the mailing list and announce any planned maintenance ahead of time.
