### ISSUE TITLE
Using Public Key From Protonmail Results In Unreadable/Non-Decryptable Emails

### ISSUE THREAD

**Issue by sissieadmin** [anonaddy/anonaddy#284]
I imported my Protonmail key into Anonaddy (non-selfhosted paid version) and can see that the fingerprint are the same. I was careful to remove the version and comments per the instructions, but every email I receive through Anonaddy is coming into Protonmail as an unreadable and protonmail reports that the message decryption failed and it may be due to a password reset (protonmail resets your pgp keys when resetting passwords).

Despite the Fingerprint for the keys being the same in both Protonmail and Anonaddy, the keys are not encrypting correctly.

**Comment by willbrowningme** [comment]
I'm not able to reproduce this.

Are you able to send me to public key via email? There is a chance it is simply a formatting error.
