### ISSUE TITLE
Dont add Vietnamese domain name

### ISSUE THREAD

**Issue by canhntnear** [anonaddy/anonaddy#286]
![image](https://user-images.githubusercontent.com/90050713/163100400-87cfc1a0-4826-452d-a829-ac20f2d54542.png)
i can't add vietnamese domain name !

**Comment by Koellewe** [comment]
You probably need to use Punycode instead of special characters. Use [punycoder.com](https://www.punycoder.com/) to convert your domain, and try with the converted string instead.

**Comment by willbrowningme** [comment]
Using the punycode version should work as mentioned above.
