### ISSUE TITLE
[BUG] 'Confirm Payment' email arrives unencrypted despite recipient having PGP key uploaded

### ISSUE THREAD

**Issue by alexaka1** [anonaddy/anonaddy#289]
I have changed my subscription and got an email from mailer@anonaddy.me with subject 'Confirm Payment'. The body contains the usual AnonAddy styling, and this

> Confirm your $XX.XX payment
Extra confirmation is needed to process your payment. Please continue to the payment page by clicking on the button below.
[Confirm Payment]

My default recipient (which this email was sent to) does have a PGP key set and it's activated.
~~I've read in a previous patch note / blogpost that you updated the code to use the PGP key during billing as well (if set).~~ [Here's what](https://github.com/anonaddy/anonaddy/projects/1#card-52590392) I was thinking of.
 I think this is a bug.

I can send you more details in private, if needed. Just point me in the direction.
(Also, the email wasn't sent to the alias that is set up on the Stripe billing portal. It was To-d directly to the recipient address. That alias correctly got the receipt later in encrypted format.)

**Comment by willbrowningme** [comment]
Thanks, you're right I must have overlooked this notification when I added encryption for all other notifications since it's in the Laravel Cashier vendor files.

I'll override that notification and try to get it updated shortly.

**Comment by willbrowningme** [comment]
Just fixed this, thanks again for letting me know.
