### ISSUE TITLE
Migrate to organization account?

### ISSUE THREAD

**Issue by crazy-max** [anonaddy/anonaddy#29]
Hi @anonaddy,

As discussed by email, I think it would be more efficient to migrate to an organization account. This would allow the migration of the [Docker image](https://github.com/crazy-max/docker-anonaddy/) here.
The procedure is quite easy as [you can see](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/converting-a-user-into-an-organization#convert-your-personal-account-into-an-organization-automatically). Let me know if you need assistance.

And thanks again for this project.

**Comment by willbrowningme** [comment]
@crazy-max Thanks for reminding me! I've just migrated anonaddy to an organization account.
