### ISSUE TITLE
[Feature Request] Option to transfer ownership of the alias to another AnonAddy user

### ISSUE THREAD

**Issue by W3LLD0NE** [anonaddy/anonaddy#293]
There are some sites that don't allow you to change email directly. However, with AnonAddy we are able to change the recipient of the alias whenever we want, that's great! The only thing that may be improved is to allow even more freedom in what we can do with alias, that is, **ownership transfer**.

So my friend, for example, can receive full control over _that-randomly-generated-email@anonaddy.me_ and do whatever he wants with both the alias and the site alias is linked to.

P.S. Not sure whether to allow the transfer for aliases tied to your username or custom domain, but at least shared domain is a perfect place to do that.
P.P.S. There can also be a situation where one paid user constantly registers aliases on paid-only shared domains and gives them to free accounts. Well I think we can apply a restriction to only transfer ownership of the aliases to accounts of the same level (or above) as yours (paid to paid only, free to free/paid etc.).
P.P.P.S. There is one possible drawback: some sites may blacklist AnonAddy addresses completely for that.

**Comment by willbrowningme** [comment]
Thanks for the suggestion, this is already on the roadmap here - https://github.com/anonaddy/anonaddy/projects/1#card-78194939

I'll see if I can add this in the near future, closing this issue since it is already on the roadmap.

**Comment by W3LLD0NE** [comment]
That's ok, but one point to note is that you're talking there about custom domains only, while this suggestion mainly proposes the feature on the shared domains.
