### ISSUE TITLE
Wrong error message when logging in with U2F/WebAuthn key

### ISSUE THREAD

**Issue by rugk** [anonaddy/anonaddy#295]
## STR

1. Setup U2F.
2. Try a wrong i..e different U2F key to authenticate.

### What happens:

An error like this is shown:
> This key is already registered. It’s not necessary to register it again.

![Screenshot of that, AnonAddy](https://user-images.githubusercontent.com/11966684/172959478-e435bf67-c55f-4336-90b1-1dd010713b2a.png)

### What should happen

The correct message should be something like this:
> This is the wrong security key. Please try again.

Seems like you improperly re-used some handling/code of adding keys – so as long as one cannot add keys in the login form, that is all hood, security-wise… :upside_down_face: 

## System

Linux/Fedora 36
Firefox 100

**Comment by willbrowningme** [comment]
Thanks, I've updated it to use the `errors.key_not_allowed` message instead now.
