### ISSUE TITLE
Enter key on U2F/WebAuthn key setup only reloads website

### ISSUE THREAD

**Issue by rugk** [anonaddy/anonaddy#297]
## STR

1. Add an U2F key in the settings, i.e. go to https://app.anonaddy.com/webauthn/keys/create.
2. Enter a device name.
3. Press <kbd>Enter</kbd> on your keyboard.

### What happens
The site is reloaded. (No error is shown, but the device name is empty again.)

### What should happen
<kbd>Enter</kbd> should react the same as clicking/using the button below. (That works! You can click the button or navigate there with tab – which does not really have a good focus style, though that is maybe a different issue – and trigger it. Then the popup is shown.)

This is kinda an accessibility and usability issue (as I am used to pressing enter on forms and want it to just work as expected :upside_down_face: )

## System

Linux/Fedora 36
Firefox 100

**Comment by willbrowningme** [comment]
Thanks, I've just pushed an update that should fix this!
