### ISSUE TITLE
Migrate/support new WebAuthn protocol instead of U2F

### ISSUE THREAD

**Issue by rugk** [anonaddy/anonaddy#298]
AFAIK U2F is kind of deprecated nowadays and _WebAuthn_ should be used instead. It has some more features like passwordless authentication and [some other integrations for other attestation stuff not only from hardware keys](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API/Attestation_and_Assertion), but AFAIk it's a different API and thus you may need to adjust something.

These resources here may provide more information:
* https://webauthn.guide/ (more user oriented)
* https://webauthn.io/ (more technical)
* https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API
* There are not many sites explaining the differences I could find [and here is one of them](https://blog.strongkey.com/blog/guide-to-fido-protocols-u2f-uaf-webauthn-fido2), but it may not be the best, actually.

See/Compare it with Nextcloud, who deprecated their whole implementation of U2F in https://github.com/nextcloud/twofactor_u2f and switched to https://github.com/nextcloud/twofactor_webauthn. Interestingly how they implemented it is that you can optionally also use your hardware key for passwordless authentication, but you explicitly need to register it for that.
For such a thing, IMHO; I would also be fine with Anonaddy.

## What may be done
* Change the code so it uses WebAuthn (and U2F only as a fallback, for hardware keys, which don't support it yet? Or maybe that is somehow automatically done?)
* Change all references in the UI to include less-technical terms (hardware key) or only as an addition include WebAuthn/U2F. Prefer "WebAuthn" if possible, as that is the latest stuff and also sounds better… :upside_down_face:

**Comment by willbrowningme** [comment]
Currently in the process of upgrading to v3 of https://github.com/asbiin/laravel-webauthn so I will close this once that is complete.

I'll update the references to U2F too, thanks.

**Comment by willbrowningme** [comment]
Latest release now pushed to the server with Laravel WebAuthn v3 so this can be closed.
