### ISSUE TITLE
[Feature Request] Preserving email avatars. 

### ISSUE THREAD

**Issue by aarjavpatni** [anonaddy/anonaddy#309]
When forwarded, emails lose the avatars of the sender and instead use AnonAddy's avatar. This makes it difficult to differentiate between the emails.
Is there any possibility to preserve the avatars of the sender?

**Comment by willbrowningme** [comment]
I don't think this is possible I'm afraid since the avatar comes from the From address and AnonAddy sends the forwarded messages to you from the alias itself.

AnonAddy cannot spoof "contact@ebay.com" for example in order to make the eBay avatar show up.
