### ISSUE TITLE
[Feature request] Change username (free users)

### ISSUE THREAD

**Issue by swanknight** [anonaddy/anonaddy#311]
I wanted to change my username, but currently it's not possible for free users.

So, I have a suggestion to make this possible. Allow free users to add 1 additional username, BUT only allow them to have only one active at a time. 

This will allow free users to change the username, while still not affecting the limitations of free users having only one username.

**Comment by ashutoshsaboo** [comment]
Big +1 on this, I just figured for free users the unlimited aliases are only for the aliases with username. Where probably one might not want to include personal details, when creating an alias with the username in it. This was nowhere mentioned on the website, and now that I've realised this after reading the docs I need to change the username to something non personal to be able to try out AnonAddy before thinking of a paid subscription. Having this capability would be really helpful.
