### ISSUE TITLE
[BUG] Unicode email addresses partially (?) supported

### ISSUE THREAD

**Issue by GitKepler** [anonaddy/anonaddy#312]
Emails with unicode characters (in the recipient address) do not seem to be handled (as per RFC6531).

Sending an email to an alias with unicode characters (such as `test👍@user.anonaddy.com`) properly increments the "Forwarded" counter, however the email is not sent to the recipient address configured in Anonaddy.

This happens even if the recipient address configured in Anonaddy is only composed of US-ASCII characters (as per RFC5321).

Steps to reproduce:
1. Create an alias with unicode characters in it
2. Assign a recipient for this alias
3. Send a mail to the alias
4. Observe that the "Forwarded" counter is indeed incremented by 1
5. The mail never gets forwarded to the configured recipient address

Note: for Step 1, emojis are not necessary; diacritics (such as `è`, `ô`, `ñ` ...) are also enough to prevent the mail from being forwarded.

Sidenote: I also tried with a US-ASCII alias and the same recipient to make sure it is not caused by the mail service provider I used; in this case, everything worked flawlessly

**Comment by ririko5834** [comment]
True, it doesnt work

**Comment by willbrowningme** [comment]
Thanks for the report. The addy.io mail servers do not support SMTPUTF8 and non-ASCII characters in the local part are no longer accepted.

`local-part of envelope RCPT address contains utf8 but remote server did not offer SMTPUTF8`

**Comment by RokeJulianLockhart** [comment]
> https://github.com/anonaddy/anonaddy/issues/312#issuecomment-2191962292

@willbrowningme, is support for RFC 6531 planned, then? As in, would you close an FR for it?

**Comment by willbrowningme** [comment]
@RokeJulianLockhart I don't have any plans to add support for it at this time. It would involve configuration changes to Postfix and the code and potentially introduce a number of edge cases.

**Comment by ririko5834** [comment]
sad to hear that
