### ISSUE TITLE
self hosted bitwarden issue

### ISSUE THREAD

**Issue by blimeybloke** [anonaddy/anonaddy#313]
Does the self hosted version work with bitwarden?  I have added my domain, and the api but it bitwarden just gives error.
thanks

**Comment by Stoffe** [comment]
Could also be of interrest to set an feature request on vaultwarden, so you can have it in a self hosted version :)

**Comment by alexaka1** [comment]
@blimeybloke [Does this solve your issue?](https://bitwarden.com/help/hosting-faqs/#q-how-do-i-set-up-an-smtp-mail-server)

**Comment by besendorf** [comment]
> Could also be of interrest to set an feature request on vaultwarden, so you can have it in a self hosted version :) (https://github.com/dani-garcia/vaultwarden)

This can't be done in vaultwarden, as it is a client feature.

**Comment by willbrowningme** [comment]
There is currently a discussion open for this here - https://community.bitwarden.com/t/custom-api-url-for-self-hosted-email-alias-services/42185/12

Hopefully it will be implemented in the near future.
