### ISSUE TITLE
After last update getting Relay Access Denied

### ISSUE THREAD

**Issue by ShawnTheShadow** [anonaddy/anonaddy#315]
After i updated to the latest version of anonaddy, it seems postfix is giving relay access denied now on all my incoming emails. 
``
Jul 18 19:17:03 anon postfix/smtpd[971]: connect from mail-oa1-f44.google.com[209.85.160.44]
Jul 18 19:17:03 anon postfix/smtpd[971]: Anonymous TLS connection established from mail-oa1-f44.google.com[209.85.160.44]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256
Jul 18 19:17:04 anon postfix/smtpd[971]: 3D1ED863422: client=mail-oa1-f44.google.com[209.85.160.44]
Jul 18 19:17:04 anon postfix/cleanup[975]: 3D1ED863422: message-id=<df9d205c-e651-1ece-36b7-9b0fb3f630cf@gmail.com>
Jul 18 19:17:04 anon postfix/qmgr[949]: 3D1ED863422: from=<xxx@gmail.com>, size=3203, nrcpt=1 (queue active)
Jul 18 19:17:05 anon postfix/smtpd[1011]: connect from localhost[127.0.0.1]
Jul 18 19:17:05 anon postfix/smtpd[1011]: Anonymous TLS connection established from localhost[127.0.0.1]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256
Jul 18 19:17:05 anon postfix/smtpd[1011]: NOQUEUE: reject: RCPT from localhost[127.0.0.1]: 554 5.7.1 <email@domain.com>: Relay access denied; from=<email@domain2.com> to=<email@domain.com> proto=ESMTP helo=<[127.0.0.1]>
Jul 18 19:17:05 anon postfix/smtpd[1011]: using backwards-compatible default setting smtpd_relay_before_recipient_restrictions=no to reject recipient "email@domain.com" from client "localhost[127.0.0.1]"
Jul 18 19:17:06 anon postfix/smtpd[1011]: NOQUEUE: reject: RCPT from localhost[127.0.0.1]: 554 5.7.1 <email@domain.com>: Relay access denied; from=<email@domain.com> to=<email@domain.com> proto=ESMTP helo=<[127.0.0.1]>
Jul 18 19:17:06 anon postfix/smtpd[1011]: using backwards-compatible default setting smtpd_relay_before_recipient_restrictions=no to reject recipient "email@domain.com" from client "localhost[127.0.0.1]"
Jul 18 19:17:06 anon postfix/smtpd[1011]: disconnect from localhost[127.0.0.1] ehlo=2 starttls=1 mail=2 rcpt=0/2 rset=2 noop=1 quit=1 commands=9/11
Jul 18 19:17:06 anon postfix/pipe[976]: 3D1ED863422: to=<email@domain2.com>, relay=anonaddy, delay=2.4, delays=0.92/0.01/0/1.5, dsn=4.3.0, status=deferred (An error has occurred, please try again later. )
Jul 18 19:17:37 anon postfix/smtpd[971]: disconnect from mail-oa1-f44.google.com[209.85.160.44] ehlo=2 starttls=1 mail=1 rcpt=1 bdat=1 quit=1 commands=7
``

**Comment by willbrowningme** [comment]
Are you using the Docker image?

**Comment by willbrowningme** [comment]
There is currently an issue open about this on the Docker repo - https://github.com/anonaddy/docker/issues/145

Not sure what the problem is, but trying to find a solution ASAP, in the meantime please rollback to v0.11.2.

**Comment by makua-bernal** [comment]
Just wanted to add I got the same issue after upgrading to v12.3 and am not using the docker image. I rolled back to v11.2.

**Comment by willbrowningme** [comment]
@makua-bernal did you make sure you updated your `.env` file with the following?

```
MAIL_DRIVER=smtp
MAIL_HOST=mail.example.com
MAIL_PORT=25
MAIL_ENCRYPTION=tls
MAIL_EHLO_DOMAIN=mail.example.com
MAIL_VERIFY_PEER=true
```

Where `mail.example.com` is your servers hostname. `MAIL_EHLO_DOMAIN` is a new variable that's been added.

**Comment by makua-bernal** [comment]
@willbrowningme yes I updated it according to the release notes and then updated the caches.
