### ISSUE TITLE
Add support to be able to pre pay years in advance on official instance.

### ISSUE THREAD

**Issue by DillFrescott** [anonaddy/anonaddy#322]
This would be great if I could pay years ahead to not have to worry about paying every year!

**Comment by willbrowningme** [comment]
You can currently pay for multiple years in advance either by purchasing multiple voucher codes or by adding an extra year(s) if you are on a crypto subscription.

I don't think it will be possible to add this for recurring card subscriptions due to the way in which they work.

**Comment by DillFrescott** [comment]
Okay! Thanks for the info
