### ISSUE TITLE
Unable send from alias to email from custom domain

### ISSUE THREAD

**Issue by nwhistler** [anonaddy/anonaddy#325]
I have a custom domain, and whenever I go to respond to emails, I send to `alias+recipient=company.com@mycustomdomain.com` but it never goes through and does not show up in the anonaddy portal as being sent. Unfortunately, there isn't a way to look at logging to see if email gets to anonaddy or not and I never get a bounce.

**Comment by nwhistler** [comment]
I should add that I have a pro plan, so I _should_ have the feature ability to do it.

**Comment by willbrowningme** [comment]
Please [send me an email](https://anonaddy.com/contact/) with details about your account and domain so I can look into this for you.
