### ISSUE TITLE
headers getting lost

### ISSUE THREAD

**Issue by bruceleerabbit** [anonaddy/anonaddy#330]
The Savannah bug tracker includes some custom headers that give details about the bug. These headers are getting dropped:

https://savannah.nongnu.org/support/?110698

**Comment by willbrowningme** [comment]
That is because AnonAddy forwards emails on as an entirely new email which is why headers are not passed through automatically.

Closing this as there is already an issue open to allow configuration of passed through headers - https://github.com/anonaddy/anonaddy/issues/230.
