### ISSUE TITLE
AnonAddy API returns aliases in chunks of 100 but the clients don't handle this paging properly and loose the data

### ISSUE THREAD

**Issue by w3lld0ne** [anonaddy/anonaddy#332]
1. Load app.anonaddy.com (you should have more than 100 aliases in total)

2. Here I have 108 active aliases by default: ![image](https://user-images.githubusercontent.com/14851973/188454355-bd2a17ae-0f07-49a8-a93e-3d30a4c07bb7.png)

3. Now I want to see my deleted aliases: ![image](https://user-images.githubusercontent.com/14851973/188454468-618941f7-9a58-4668-b898-d7059f32537c.png)

4. The new aliases count is now 100 in total (98 active + 2 inactive/deleted) which is false: ![image](https://user-images.githubusercontent.com/14851973/188454582-16903670-dbfe-4ce5-bf75-323c9217b6d7.png)

5. I've tried to hide deleted aliases again (not by reloading the page but by resetting the filter), but the total amount of alises is still capped by 100: ![image](https://user-images.githubusercontent.com/14851973/188454746-0599f04e-2dcf-4af5-b9df-3a539dc12ebb.png)

The oldest aliases are not displayed anymore (until I reload the page).

**Comment by W3LLD0NE** [comment]
This actually seems like the problem with API because mobile apps are also affected (they never load the full list of aliases, only the latest 100). Browser extension seems to not be affected but it loads aliases by chunks, few after few, maybe it does matter.

**Comment by W3LLD0NE** [comment]
I've also found out that when you initially load app.anonaddy.com page, it doesn't produce any API calls (thus initial load is unaffected by the problem), but whenever you touch the filter, an API call is made with the described bug.

**Comment by willbrowningme** [comment]
Thanks, I am aware of the issue on the web application and will be fixing it soon in the new UI. This will fix the alias counts etc. too.

There is no issue with the API, it is paginated to 100 aliases per page by default - https://app.anonaddy.com/docs/#aliases-GETapi-v1-aliases

Some users have 10s of thousands of aliases so it is not feasible to allow an API call to fetch all of these in a single request.

That is why pagination was added, this is present in the browser extension where 10 aliases are fetched per page.

As KhalidWar mentioned the API allows you to search aliases by description or email server side.

**Comment by D3strukt0r** [comment]
Still a problem. Makes sense you can't get all in one request. But it still makes sense to know what the total actually is, and that pagination would work like that. I have 485 aliases (recently renewed most of them, so equal number of deleted ones), switching to deleted ones, caps to 100 with 4 pages, which is clearly wrong

**Comment by willbrowningme** [comment]
Should be sorted now.

**Comment by D3strukt0r** [comment]
I do already miss being able to select the page size, having the option to see everything on one page and use the browser search was neat. Maybe create a new issue/request for that 🤔
