### ISSUE TITLE
Emails not received at the default alias address

### ISSUE THREAD

**Issue by payzillee** [anonaddy/anonaddy#338]
I changed my default recipient address but emails are still going to the old default recipient address.  I can get them to send to alternate addresses by manually changing each alias recipient as a workaround for now, but any new aliases created automatically with catch-all are still going to the old default recipient.  

Ta!

**Comment by willbrowningme** [comment]
If you have set a default recipient for your username or domain then this will override the account wide default recipient which is set on the settings page. Please check this and let me know if you are still having issues.
