### ISSUE TITLE
[Feature Request] 'forget all' for deleted alias, or select multiple.

### ISSUE THREAD

**Issue by billyb1987** [anonaddy/anonaddy#341]
Please add the ability to 'forget' all deleted aliases or to 'select' multiple deleted aliases to be forgotten at once to save the user time. I am in the process of swapping my custom domain to a new one and to keep my alias list clean I want to 'forget' the old alias', I have 200+ to work through and as far as I can tell I can only 'forget' them 1 by 1.

**Comment by billyb1987** [comment]
I have just noticed this feature was requested by user: Ghost on 31st of May 2021. I do hope that it will be implemented at some point.

**Comment by willbrowningme** [comment]
Yes, it will be added with or soon after the new user interface is launched. In the mean time you can email me with details of the domain and I will forget them all for you. Closing this as a duplicate of #161.
