### ISSUE TITLE
Self-Hosted | can't get verification email 

### ISSUE THREAD

**Issue by VijendraMalhotra** [anonaddy/anonaddy#348]
I am trying to register an account after hosting the site. (https://github.com/anonaddy/anonaddy/blob/master/SELF-HOSTING.md#creating-your-account). but can't seem to get the verification email.
looked at the app logs /var/www/anonaddy/storage/logs/larvel-2022-10-13.log (it's clean)
looked at the /var/logs/mail.log and that is clean as well

what am i missing?

**Comment by willbrowningme** [comment]
Does your hosting provider have port 25 open?

**Comment by willbrowningme** [comment]
Perhaps you have not setup supervisor correctly which is why is is not processing the queued mail jobs. Please make sure supervisor is running and the config for it is correct.

**Comment by willbrowningme** [comment]
Did you sort this in the end?

**Comment by VijendraMalhotra** [comment]
AWS doesn’t like opening port 25 it seems. so waiting to hear from them!
thanks for you help @willbrowningme

**Comment by willbrowningme** [comment]
No problem, hopefully they will open it.

Closing as this isn't related to the software.

**Comment by VijendraMalhotra** [comment]
If anyone has ever worked with AWS to get the port open, help would be appreciated in terms of answering the question " A technical explanation of your spam prevention mechanisms, including details regarding your infrastructure and security measures."

**Comment by narainaDewasi** [comment]
Hi i am facing same issue 
i am using AWS SES  for send email
after all configuration for aws ses and postfix when i test it with this command 

``echo "Test Message" | mail -s "Test Subject" -a "From:info@mail.domain.com" my-email-id@gmail.com``
its sending the mail but on the anonaddy app it says that the verification mail have been sent then i have nothing received.

there is no error log found in mail.log /mail.err / laravel-*.log files
