### ISSUE TITLE
Allow management of deleted aliases

### ISSUE THREAD

**Issue by stefanschramek** [anonaddy/anonaddy#35]
Hi,
I think it would be nice to have the following management functionality:

- See my deleted alias and blocked emails count for each of them
- "Forget" them, so it will be possible to reuse them - only possible for custom domains through catch-all-function

Thanks
Stefan

**Comment by willbrowningme** [comment]
Good ideas, I definitely think the ability to view previously deleted aliases should be added.

I'll update this issue when I've implemented that.

**Comment by willbrowningme** [comment]
You can now view manage and restore previously deleted aliases.

**Comment by stefanschramek** [comment]
Thanks for adding this!
Would it be also possible to add the possibility to release an alias? It would be handy to completly remove an alias if it is not needed anymore!

**Comment by willbrowningme** [comment]
Do you mean the abilty to "forget" an alias as if it had never existed? What use case would you have for doing this?

**Comment by stefanschramek** [comment]
Yes, exactly! From time to time I create an UID-alias and realize afterwards, that the service I want to use it with, does not accept such email addresses! I would be better to delete them instead of reuse later with any other service!

**Comment by willbrowningme** [comment]
So could you not just delete it and leave it deleted in that scenario? Then you won't have to see it in the default aliases view on the dashboard.

**Comment by stefanschramek** [comment]
For sure that is one way to deal with it! I just thought it would be cleaner to totally remove them!
Thanks!
