### ISSUE TITLE
[BUG] Automatic creation of aliases

### ISSUE THREAD

**Issue by Gurp1272** [anonaddy/anonaddy#350]
Hello,

I really like this solution. Helps me separate all my email concerns. It was working great until... dun. dun. dun...

I started getting emails forwarded to me from aliases I never created. For example, say I use scary@gurp.com for a sketchy website that I can't trust not to leak my email.

Then I start getting emails forwarded from aliases like hr-mail@gurp.com.

So I'm like "HEY, I didn't create that alias". Then I go and check my aliases to be sure I didn't create it and, it's there. BUT, I know I didn't create it. Then I start getting more and more emails forwarded from aliases I know I didn't create. 

Anyone else have this issue? 

Is there a solution for this now, or does one need to be created?

**Comment by willbrowningme** [comment]
Hi there,

This is not a bug, it is just the way that catch-all works for a domain. [https://www.mailercheck.com/articles/catch-all-email](https://www.mailercheck.com/articles/catch-all-email)

When you have catch-all enabled for an email domain it will automatically forward you any message e.g. random@example.com.

Please go to the [domains page](https://app.anonaddy.com/domains) and in the column called "Catch-All" turn the switch to OFF. Then you can go and "forget" or "delete" the aliases that have already been created that you don't want.
