### ISSUE TITLE
[BUG] check_access procedure always returns DUNNO

### ISSUE THREAD

**Issue by TheBinaryLoop** [anonaddy/anonaddy#353]
check_access procedure always returns DUNNO even if I check it against a valid alias

**Comment by willbrowningme** [comment]
That is the intended behaviour of the `check_access` stored procedure.

Try running it for an alias that is either deactivated or deleted.

Please read the [MariaDB](https://github.com/anonaddy/anonaddy/blob/master/SELF-HOSTING.md#installing-mariadb) section in the self-hosting guide that explains why the stored procedure returns `DUNNO` for a valid alias.
