### ISSUE TITLE
APP_URL

### ISSUE THREAD

**Issue by muxo771** [anonaddy/anonaddy#355]
The APP_URL has to be set to a real address. 

Had setup a test system with a non-default port for the webserver. 

Always got a 403 bad signature for the verification email, because I added the port number by hand.

After some search I found a hint how the system creates the verification email.
https://stackoverflow.com/questions/53892356/laravel-5-7-signed-route-returns-403-invalid-signature

***********************************
UNDERSTANDING LARAVEL EMAIL VERIFICATION WAY

Understanding the way of verification can help you simply solve this error.
laravel makes a temporary signed url using method URL::temporarySignedRoute(),
this method is called in verificationUrl() located at \vendor\laravel\framework\src\Illuminate\Auth\Notifications\VerifyEmail.php.

So if the url that sent to emails is different from url that will laravel get at the time of verification (time of checking signature of url), 403 | invalid signature occurs.

Example:

if you set APP_URL to http://yourdomain.com/, verification link should be look like http://yourdomain.com/email/verify/{id}/{hash}. now if you set your server configs to redirect to https, invalid signature will occured, since the url laravel gets is https://yourdomain.com/email/verify/{id}/{hash} and not same as email verification url.

**************************************

After putting the port number also in the .env I could verify the test account. 

Could be helpful to explain it on the comment line, like has to be the complete url(:port) or verification will fail. 

or

The URL of the AnonAddy instance, can be anything you like e.g. aa.example.com(:port), or just example.com(:port)

kind regards

**Comment by willbrowningme** [comment]
Thanks, I've updated the comment to mention the port too.
