### ISSUE TITLE
Error, emails dont deliver

### ISSUE THREAD

**Issue by ririko5834** [anonaddy/anonaddy#356]
Hello, forwarded emails sometimes dont come.

And I am getting errors like this (this is for example when I used anonaddy alias on aliexpress)
![image](https://user-images.githubusercontent.com/64729293/198986308-e863673a-bed5-4ad7-a222-2d5ac53c87b1.png)

It sometimes also happens for emails from other sites. When I try to resend the verification code for aliexpress, I get it on second or third attempt, and usually I receive also the first emails but with long delay (but then when I resend verification code, just the last one is actual, not the first one that I receive so I have to wait long until the correct comes)

**Comment by willbrowningme** [comment]
It looks like the HELO hostname "out32-32.sg.b.dm.aliyun.com" could not be resolved for some reason. Perhaps Aliexpress was having issues.

That is because the error code is `450` which means the email was deferred and that's why it came through later.

I'm afraid I cannot provide unlimited support for self-hosted instances here.

**Comment by ririko5834** [comment]
I understand, but I cant affect from which domain will ali send emails.

Is there a way to disable spamhaus checking for specific domains/subdomains?

**Comment by willbrowningme** [comment]
You can override the `main.cf` postfix configuration file in Docker - https://github.com/anonaddy/docker#override-postfix-main-configuration

You would need to change `smtpd_recipient_restrictions` - https://github.com/anonaddy/docker/blob/master/rootfs/etc/cont-init.d/15-config-postfix.sh#L88-L97

and possibly `smtpd_helo_restrictions` - https://github.com/anonaddy/docker/blob/master/rootfs/etc/cont-init.d/15-config-postfix.sh#L74-L79

**Comment by ririko5834** [comment]
It's sad that there isn't a way to add env variable to disable it just for specific domain(s)
