### ISSUE TITLE
add the name of the alias to the forwarded mail

### ISSUE THREAD

**Issue by HelpfulRock** [anonaddy/anonaddy#37]
posted the issue on reddit, got some votes but no feedback:
https://www.reddit.com/r/AnonAddy/comments/ffryws/how_do_you_use_anonaddy_relativly_new_and_not/

issue: i'm using anonaddy now for every website i register with and did the same but just with catchall and random aliases before. problem is anonaddy doesn't really make it possible to see if the sender is comprimised or not since no matter which sender sends something to a viable randomadress it gets forwarded and i have no easy way to check if an email for example from amazon hit the amazonspecific adress or if some adress got leaked and i got a fake amazon mail to another adress.
currently i have to set up an inboxrule and tell my inbox to put any email for the adress i gave amazon in the amazon folder or put a label amazon on it. this way if an adress hits that doesn't get the treatment i see that its fake.

solutions:
change the text in the forwarded mail to:

> This email was sent to 2r34d@example.com **"Amazon"** from xyz@amazon.com and has been forwarded by AnonAddy
> Click here to deactivate this alias

or enable replacing the subjectline with the name of the alias.

the secondline would be way more obvious but might not be apreciated since it subjectlines are not pgp encrypted.

not sure about those people deactivating the text telling us that the mail was forwarded... but well being able to choose between both solutions above would work for most people i guess.

**Comment by willbrowningme** [comment]
Would you not be able to use the Reply-To: header which would look like this:

2r34d+xyz=amazon.com@example.com

I'll be adding a new Rules system to the site shortly so will hopefully be able to implement this into that as one of the conditions/actions.

**Comment by HelpfulRock** [comment]
Hey Will,
sorry for the late reply - not sure how that helps or if its just the way my mailprovider shows it thats not that great (protonmail)
if i click answer - sure that shows me the input you mentioned but every halfway not stupid spammer should be able to send mails that break this? Also having to click on "answer" for every mail and then deleting the draft seems kind of impractical and gives no more usability than adding a million filterrules. especially when considering that this still doesn't solve the problem regarding "is the person sending mail sending it to the right alias".

what kind of new rule are you adding?

**Comment by willbrowningme** [comment]
So if I understand correctly you want a way to see who the sender of the email is?

The solution you've suggested above is to add e.g. "Amazon" to the banner information.

You can see already in the banner information that the sender is "xyz@amazon.com", this email is the return-path of the sender who sent the email to the alias. So the fact that it is an amazon.com domain let's you know it came from Amazon. If someone else had sent it e.g. spammer@example.com then it would say:

> This email was sent to 2r34d@example.com from spammer@example.com and has been forwarded by AnonAddy
> Click here to deactivate this alias

The new rules will allow you to do things like:

IF sender IS EXACTLY xyz@amazon.com THEN rewrite the subject to this ....

etc.

I'll be improving the rules and system over time.

**Comment by HelpfulRock** [comment]
Hi Will,
sorry for the late answer. yes the emailname is there but as i said - i can't see on a glance if the alias the sender is using is the right for the adress that sends the mail. Thats why i proposed the option to have the name i have given the alias in anonaddy displayed in the text.
what i mean is if an email from amazon is coming to my jh3f5@example.com instead of 2r34d@example.com i would like to see that it hit the wrong alias.

the rules sound fine - but as i said its more about bringing the right mailadress and the right alias together. perhaps amazon was a bad example since they will most likely have configured their DMARC in a way that i can't send an email pretending to be amazon but there are lots of other sites out there which have bad settings so i would not in every case count on the sender being correct.

**Comment by erik-h** [comment]
@willbrowningme Something I've been wondering about that I think applies to this: would you be open to adding a configuration option to set the "From" address to the same value as the "Reply-To" header? My use case is: I want to filter marketing emails separately from non-marketing emails from a few different companies. It'd be awesome if I could set up my email client to filter `"amazon+marketing=amazon.com@mydomain.com"` to one folder, and `"amazon+orders=amazon.com@mydomain.com"` to a different folder (as a made up example).

**Comment by willbrowningme** [comment]
@erik-h Intersting idea, would you able to set up a filter in your email client that filters on the current Reply-To header to acheive this?

**Comment by erik-h** [comment]
@willbrowningme good point - I'm mainly using the webapps of two providers: [ProtonMail](https://protonmail.com) and [HEY](https://hey.com). It looks like I can create a custom sieve filter to achieve this using ProtonMail. The unfortunate part though is that as far as I understand, I would have to manually go in and configure custom sieve filter rules for every company I want to filter on. If the From address was set to the value, the filter would be easier to create quickly (I think).

HEY is the main provider with which I've been wanting to use this "filter by from address" functionality. They have this "screener" that captures all incoming email from unknown senders and allows you to send all email from that sender to the Imbox, the Feed, or the Paper Trail (basically three special folders). It's not possible to create custom sieve filters in HEY currently - you can only filter based on From address (but it's super easy to create one of these filters, which is a huge plus).

**Comment by erik-h** [comment]
@willbrowningme I don't mean to poke, but I was just wondering if you have any further thoughts on this.

**Comment by willbrowningme** [comment]
@erik-h you mention above:

>If the From address was set to the value, the filter would be easier to create quickly (I think).

What exactly do you mean by this, the "display from" value or the actual email address a forwarded message is sent from?

**Comment by erik-h** [comment]
@willbrowningme The actual email address the forwarded message is sent from. I'm proposing something like a user setting one can enable that says "Append sender to forwarded 'From' address" that sends the forwarded email from what Anonaddy currently sets for the "Reply-To" header.

Currently the emails are sent from e.g. `amazon@anonaddy.me` - I'm proposing a setting that would instead send them from e.g. `amazon+orders=amazon.com@anonaddy.me`. I think this would be a really nice way to allow emails sent to Anonaddy addresses to be easily filtered based on the _original_ sender. Currently to achieve this I'd need to create custom sieve filters that check the "Reply-To" header. This is only possible in my case in ProtonMail, not in HEY nor Gmail (I _think_? I don't use Gmail very much).

**Comment by willbrowningme** [comment]
@erik-h Okay, I understand.

So it would mean the from email address would be set to be the same as the reply-to one?

**Comment by erik-h** [comment]
@willbrowningme Sweet, yea that's correct. Does that sound reasonable? I haven't looked at the code so I'm not sure what all would be involved.

**Comment by willbrowningme** [comment]
@erik-h yes it is possible, I think I'll add this as an option for the rules or in account settings as to make it opt-in.

**Comment by erik-h** [comment]
@willbrowningme that sounds great, thank you!

**Comment by willbrowningme** [comment]
@erik-h I've just pushed an update that removes the Reply-To: header on forwarded emails and sets that to the From: header instead.

**Comment by erik-h** [comment]
@willbrowningme That works great - thanks!
