### ISSUE TITLE
Anonaddy Bitwarden support: Created alias does not adhere to custom default alias type in AA

### ISSUE THREAD

**Issue by mannp** [anonaddy/anonaddy#379]
Likely I need to link this on bitwardens mobile device repo, but wanted it here to0, in case anonaddy config settings influence the way BW works with it?

In order to get domain-45g@ format aliases from the BW android mobile app is that a BW or a AA change pls?

Thanks

**Comment by willbrowningme** [comment]
The only available alias formats currently are "Random Characters", "Random Words", "UUID" or "Custom" and this is chosen on the web app's settings page.

So it won't be possible to generate `domain.45g@yourdomain.com` using Bitwarden as that comes under the "Custom" alias format and there is no option to enter that in Bitwarden.

However there is an issue I need to fix regarding alias creation through the API that does not respect the default alias format setting in your account (e.g. random words / random characters).

**Comment by willbrowningme** [comment]
If you are using your own domain you can just create the alias on the fly (if you have catch-all enabled) without needing to use Bitwarden to create it for you.

**Comment by mannp** [comment]
> The only available alias formats currently are "Random Characters", "Random Words", "UUID" or "Custom" and this is chosen on the web app's settings page.

Yes this is what previously confused me, not having domain-random character in that list too. 

My thought was, if custom was selected as the default in the web app, and BW creating an alias, shouldn't it by default create a custom alias?

> So it won't be possible to generate `domain.45g@yourdomain.com` using Bitwarden as that comes under the "Custom" alias format and there is no option to enter that in Bitwarden.

This is why I was not sure where to post, as I was unclear what api call BW was using to create the alais.

> However there is an issue I need to fix regarding alias creation through the API that does not respect the default alias format setting in your account (e.g. random words / random characters).

Okay this is the crux, and makes sense now ... but would fixing this bug fixed the creation of a custom domain initiated through the BW android app?

**Comment by mannp** [comment]
> If you are using your own domain you can just create the alias on the fly (if you have catch-all enabled) without needing to use Bitwarden to create it for you.

I am using my own domain, but am not a fan of catchalls, as the only thing it tends to catch are bad actors, as a legitimate source would have the correct email address to use.

**Comment by willbrowningme** [comment]
> Okay this is the crux, and makes sense now ... but would fixing this bug fixed the creation of a custom domain initiated through the BW android app?

No it would not, because when the alias format of "custom" is chosen, you must provide a value for the alias "local part" because it is not randomly generated.

Bitwarden does not provide anything in their API request for "local part" so it would fail.

Also it is not trivial to parse and extract the name part of a domain e.g. `example` from `sub.example.co.uk`. I had to use the help of [psl (Public Suffix List)](https://www.npmjs.com/package/psl) to get it to work and I doubt Bitwarden will want to pull in another dependency just to add this.
