### ISSUE TITLE
Better RSS status updates

### ISSUE THREAD

**Issue by nicolas-g** [anonaddy/anonaddy#382]
When you subscribe to your https://status.anonaddy.com/ in Slack, the message title coming from just shows `status updates`.

This is very generic and requires someone to click on the link in order to confirm this is coming from AnonAddy, will be nice if we can see instead  of `status updates` as a title see `AnonAddy`

In the screenshot you can see an example of how it looks and also including a good example from GitHub blog:

<img width="826" alt="image" src="https://user-images.githubusercontent.com/2202932/199769176-6139a24e-86f7-4bf7-ae51-ec78fce29881.png">

**Comment by willbrowningme** [comment]
I'm using ohdear.app for the status page and uptime monitoring, I cannot see a way to change the title for the RSS feed updates though. I will have to contact them and ask about this.

**Comment by nicolas-g** [comment]
I see, this is annoying but I assume very low on your list of priorities. I thought it was worth reporting it.

Thank you.

**Comment by willbrowningme** [comment]
I contacted them and they've just updated it so that it can now be changed in the settings, I've set it to "AnonAddy Service Status".
