### ISSUE TITLE
Dropdown is behind pagination

### ISSUE THREAD

**Issue by limonte** [anonaddy/anonaddy#383]
<img width="554" alt="CleanShot 2022-11-04 at 15 52 29@2x" src="https://user-images.githubusercontent.com/6059356/199989015-2bed9e48-ea72-4501-abf2-d03a342b05d5.png">

**Comment by willbrowningme** [comment]
Thanks, I'm aware of this issue and will fix it in the new UI launch.

**Comment by willbrowningme** [comment]
I've pushed a temp fix for this but I'm not completely happy with it. Will try to figure out a better way to handle it.
