### ISSUE TITLE
[Feature request] From name per alias

### ISSUE THREAD

**Issue by limonte** [anonaddy/anonaddy#389]
ATM setting From Name is available as paid feature:

<img width="528" alt="CleanShot 2022-11-27 at 14 48 01@2x" src="https://user-images.githubusercontent.com/6059356/204136037-a191935f-a422-46d8-9315-ab116f6bdca6.png">

But, it'd be great to have more control over this feature and have the ability to set From Name per alias.

Thank you for such an amazing OSS project! <3 I've recently subscribed to the annual subscription and it's worth every penny!

**Comment by willbrowningme** [comment]
Thanks for the suggestion! This is currently already on the roadmap [here](https://github.com/anonaddy/anonaddy/projects/1#card-79830989).

Closing this as #279 is already open and on the roadmap.

P.s. Thanks very much for your sponsorship, just updated the repo to add your name.
