### ISSUE TITLE
[Feature Request] Replace reverse address with recipient address when replying to email

### ISSUE THREAD

**Issue by ghost** [anonaddy/anonaddy#395]
I mean a *reverse alias* is an address like this. I am not sure what it is called:
`alias+hello=example.com@johndoe.anonaddy.com`.

When replying to a forwarded email, that address may be automatically included.
It looks something like this.

```
Hello, this is a test reply.

-------- Original Message --------
On Dec 1, 2022, 12:30 AM, hello at example.com <alias+hello=example.com@johndoe.anonaddy.com> wrote:
                                               ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Hello, please reply to this message.
```

This may cause confusion when the person to whom you are replying sees this reply.  
Because the address to which you are replying (`alias+hello=example.com@johndoe.anonaddy.com`)  
is not the address of the person to whom you are replying (`hello@example.com`).

I would like the ability to replace that address with the address of the person to whom you are replying.

PS.
SimpleLogin seems to have this feature, but I like AnonAddy :D

![screenshot1](https://user-images.githubusercontent.com/95062307/205790809-5f5f7f39-51b7-4e6a-8c08-6ae79049eb89.png)

**Comment by willbrowningme** [comment]
Thanks, I'll see if I can sort this out.

**Comment by ririko5834** [comment]
I like this idea

**Comment by leonardosegurat** [comment]
Was about to create as a new issue, referring specifically to forwarded emails.
I see that #123 is already in the roadmap as in progress, and there's a rules system card. I think this issue should be placed under it as well, as it falls under the same umbrella and should be considered when developing the rules system.

**Comment by willbrowningme** [comment]
I believe I have this working, for best results use the following options in your [account settings](https://app.addy.io/settings):

1. Set **Update Display From Format** to option 4 `John Doe`.
2. Set **Use Reply-To Header For Replying** to `disabled`.

Then give it a try by replying to yourself from one of your aliases.
