### ISSUE TITLE
[bug] New/Edit Rule page layout glitches

### ISSUE THREAD

**Issue by buxm** [anonaddy/anonaddy#398]
On the self hosted Anonaddy the modal for adding/editing Rules shows some glitches.
1. The Text Input field for the Condition value is very small. It's impossible to see what you type in it.
2. Also the Text Input field for the Action value is quite small. It only fits 4 characters.
3. The Actions fieldset does not fit into the modal when selecting "set the banner information location to" in the "Then" drop down list
Here are example screenshots:
![image](https://user-images.githubusercontent.com/57507414/206858549-b392f50b-9fae-4acf-b3c5-a91e396f8a97.png)
![image](https://user-images.githubusercontent.com/57507414/206858581-4099904b-a9e0-4207-9b42-8ddcc7c675ac.png)

Anonaddy version: 0.13.12
Browser: Chrome 108.0.5359.99 on Windows 11

**Comment by willbrowningme** [comment]
Thanks, will be fixed in the new UI shortly.

**Comment by buxm** [comment]
Hi,
things have greatly improved with Anonaddy version 0.14.0.
There is still a small glitch with a down arrow partly covering some text:
![image](https://user-images.githubusercontent.com/57507414/232288219-e695ffee-afa7-4064-acc5-021c455d84b2.png)

Also having a bit more space in the "Enter value" boxes could help with longer values.

Many thanks!

**Comment by willbrowningme** [comment]
Should be sorted now.

**Comment by buxm** [comment]
the [issue reported with version 0.13.12](https://github.com/anonaddy/anonaddy/issues/398#issue-1488506340) had been sorted in version 0.14.0.
However a [small glitch was still present in version 0.14.0](https://github.com/anonaddy/anonaddy/issues/398#issuecomment-1510203802). And still is in version 0.14.1.

**Comment by willbrowningme** [comment]
I will update the self hosted repo shortly.
