### ISSUE TITLE
integration with bitwarden password manager

### ISSUE THREAD

**Issue by CouldBeThis** [anonaddy/anonaddy#40]
I have no idea what would be involved with this, how it would work or if it's possible. :) 

If someway, somehow, anonaddy could work with [bitwarden](https://github.com/bitwarden), most _especially_ the browser extension, that would be so so so cool. I know this is a long shot but I'm throwing it out because I think of it all the time. 

Click one button and a new accounts signup page auto-fills with a generated email address and password, which are automagically remembered by bitwarden. No more copy pasting all over the place. 

Bitwarden is my choice but I guess other people use other tools and would probably appreciate same. Any such integration would make anonaddy extra appealing to existing users of given credential managers (and add an extra very useful service to the managers). Presumably people who use tools like that for privacy/security purposes are extremely likely to be interested in anonaddy. 

I can't imagine that there is a way to do this without the OK of the bitwarden dev, though I have no idea about the back of these things, so maybe. The bitwarden browser extension just pops up a little webpage from what I can see. But I'd hope there is some sort of security preventing one extension from going in and fiddling with another.

**Comment by MarionMoseby** [comment]
Cant you autogen an email with anonaddys extension, then autogen a password with bitwarden, hit sign up and then click "remember this psswd for me" in the dialog bitwarden shows for unknown passwords?

**Comment by CouldBeThis** [comment]
It doesn't always work. I don't know why.

**Comment by willbrowningme** [comment]
Closing this as Bitwarden has now added AnonAddy integration into their service.
