### ISSUE TITLE
PGP from self-hosted AnonAddy cannot be decrypted in Proton Mail mobile app

### ISSUE THREAD

**Issue by zcyph** [anonaddy/anonaddy#400]
Related to [#187](https://github.com/anonaddy/docker/issues/187)

PGP encrypted mail forwarded by AnonAddy gets decrypted normally in third party email clients like Thunderbird/Evolution Mail on Desktop or K9/FairEmail on mobile. They decrypt properly in Proton Mail's webapp - but _not_ in Proton's mobile app.

Initially thought this might only have been impacting the Docker version, but I spun up a fresh non-Docker instance and saw the same behavior there. This does not happen with the official hosted version at anonaddy.com.

Opening the issue here as it's not Docker-specific.

**Comment by dcod3d** [comment]
I have two instances (0.11.2 and 0.13.12) running and both using the same key to encrypt/sign the message. The 0.11.2 version works as expected with the later version not, so I don't think it's an issue with Proton Mail's Bridge.

**Comment by willbrowningme** [comment]
I've just fixed this issue in the latest release - [v0.13.13](https://github.com/anonaddy/anonaddy/releases/tag/v0.13.13).
