### ISSUE TITLE
Dropdown Menu is partially hidden.

### ISSUE THREAD

**Issue by dinodev0101** [anonaddy/anonaddy#408]
Hello Anonaddy Team.

I've been using Anonaddy Email Forwarding for about 1month.
All the features look good, but there's only one that I want it to be fixed.

![image](https://user-images.githubusercontent.com/117986510/210437019-35f286ac-d87d-4c3e-877c-7da0dc029e76.png)

I'm not sure that you intended. But I think it's not following the user-friendly design.
However, I really love Anonaddy. Please forgive me to give you bad feedback.

Thanks

**Comment by willbrowningme** [comment]
Thank you, I am aware of this and there is already an issue open for it - #383
