### ISSUE TITLE
Inline Images in emails

### ISSUE THREAD

**Issue by m42e** [anonaddy/anonaddy#412]
Hi,

I discovered that forwarded mails are not displayed correctly if they contain inline images. After looking into the source I discovered the `content-id` was missing. It seems to be an issue in the mail parser, as it simple declares the `content-disposition` as `attachment` whereas it was originally declared as `inline`.

I added a fix as a PR here. https://github.com/php-mime-mail-parser/php-mime-mail-parser/pull/409 

I am not 100% sure if this is enough or if there is something happening in anonaddy in some cases.

Could someone have a look, too?

Best
m42e

**Comment by m42e** [comment]
I just recognised, that the multipart type is also changed from `multipart/related` to `multipart/mixed`.

**Comment by willbrowningme** [comment]
Inline images are handled here - https://github.com/anonaddy/anonaddy/blob/master/app/Mail/ForwardEmail.php#L217

This sets the correct `Content-Id` for each inline image.

The `Content-Type` may be something that needs looking at though, do you have an `.eml` example that replicates the issue?

**Comment by willbrowningme** [comment]
Just tested with your `.eml` in the pull request and can reproduce this, you're right. Will try to do some debugging shortly.

**Comment by m42e** [comment]
I already discovered the issue is not part of anonaddy, but Symphony. I raised a PR there, too: https://github.com/symfony/symfony/pull/48901

**Comment by m42e** [comment]
As the change may take a while to hit this project, there would be a workaround. Replacing the cid with the name upfront. Not a great one to be honest. What do you think?

**Comment by willbrowningme** [comment]
Hmm, might just wait as it seems your PR has now been merged in Symfony, thanks for finding this!

**Comment by willbrowningme** [comment]
Okay Symfony have released version 6.3 so as soon as a new release of [php-mime-mail-parser](https://github.com/php-mime-mail-parser/php-mime-mail-parser) comes out that includes your [fix from above](https://github.com/php-mime-mail-parser/php-mime-mail-parser/pull/409) then it will all work as expected.

Thanks again for finding this and creating the fixes.
