### ISSUE TITLE
anonaddy selfhosted // relay access denied

### ISSUE THREAD

**Issue by redalert99** [anonaddy/anonaddy#415]
Hello,

I have set up my server according to the instructions WITHOUT Docker.

My problem now is that I can't send emails (e.g. registration mail). The mail.log shows me the following:

Jan 12 16:54:57 mail postfix/smtpd[16273]: connect from somedomain[IP]
Jan 12 16:54:57 mail postfix/smtpd[16273]: Anonymous TLS connection established from somedomain[IP]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange ECDHE (P-384) server-signature RSA-PSS (4096 bits) server-digest SHA256
Jan 12 16:54:57 mail postfix/smtpd[16273]: NOQUEUE: reject: RCPT from somedomain[IP]: 554 5.7.1 <user@name>: Relay access denied; from=<mailer@somedoman> to=<user@name> proto=ESMTP helo=<mail.somedomain>

Can someone help me to solve this problem ?

Thanks a lot.

Red

**Comment by mzch** [comment]
It's. a MTA problem. Perhaps you don't list a domain part of `user@name` in replay host nor desitination.

**Comment by redalert99** [comment]
What can I do ? I have done everything exactly as it is written in the instructions.

**Comment by mzch** [comment]
Do you list a domain part of `user@name` in any one of `relay_host`, `mydesitination` or `virtual_mailbox_domains` in your  `/etc/postfix/main.cf`?

**Comment by redalert99** [comment]
Hey. i added my host ip to the allowed netwokrs and now it works.
