### ISSUE TITLE
[Feature Request] username-like feature for custom domain names

### ISSUE THREAD

**Issue by fryorcraken** [anonaddy/anonaddy#423]
I used anonaddy with a custom domain name for my own emails.

I would like to enable my family members to use the same custom domain name for their aliases.
Hence, I need for them to be able to create aliases on the fly that points directly to a given recipient (their email).
Very similar to the "username" feature but for a custom domain name.

E.g. custom domain name is `example.com`.

username `alice` means that `anything@alice.example.com` forward to Alice's email.

do note that subdomains are actually not ideal as some forms do not support an email that has a subdomain, so having more choice such as:

- `alice+anything@example.com`
- `alice.anything@example.com`

Would be ideal.

**Comment by willbrowningme** [comment]
You can add a separate subdomain as a custom domain to your account for each family member.

So you can add `alice.example.com` and then set the default recipient for that custom domain to Alice's email.

You can also use recipient keys to attach differrent recipients to aliases when they are created on the fly - [more details here](https://anonaddy.com/blog/add-recipients-to-aliases-at-creation-and-new-uuid-aliases/).
