### ISSUE TITLE
fdroid apk repeatedly crashes while trying to edit alias

### ISSUE THREAD

**Issue by m1chj** [anonaddy/anonaddy#425]
Fresh fdroid install 4.5.0 works fine for a while, then crashes every time like below. Clearing app's cache doesn't help and this happens the same way on different Huawei P40 series devices I've tested, both running latest firmware.

Crashes like this:

https://user-images.githubusercontent.com/45080190/214538884-8b8fafbd-fe80-4beb-9650-e6d596167951.mp4

Works fine for a while after fresh install:

https://user-images.githubusercontent.com/45080190/214538790-b8d65ab0-f0ba-43d3-b131-45389ba79dd8.mp4

**Comment by willbrowningme** [comment]
Please could you open this issue on Stjin's repository on GitLab - https://gitlab.com/Stjin/anonaddy-android
