### ISSUE TITLE
[Self-Hosted] SSL_accept error for all received emails

### ISSUE THREAD

**Issue by TheComp44** [anonaddy/anonaddy#426]
Hello! I have a self-hosted AnonAddy (non-docker version) running on my server and it has been working for over a year now.

After the last update from `v0.12.3` via `v0.13.0` to `v0.13.13`, suddenly all emails received from AnonAddy fail to deliver to my recipients. I followed all the steps under "Updating" in the AnonAddy Self-Hosting guide.

Here is the log from postfix:

```
Jan 30 11:23:48 mail postfix/smtpd[90650]: connect from mail-ej1-f44.google.com[209.85.218.44]
Jan 30 11:23:48 mail postfix/smtpd[90650]: Anonymous TLS connection established from mail-ej1-f44.google.com[209.85.218.44]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange ECDHE (P-384) server-signature RSA-PSS (4096 bits) server-digest SHA256
Jan 30 11:23:48 mail postfix/smtpd[90650]: C69FF402F0: client=mail-ej1-f44.google.com[209.85.218.44]
Jan 30 11:23:48 mail postfix/cleanup[90657]: C69FF402F0: message-id=<SOME-ID@mail.gmail.com>
Jan 30 11:23:48 mail postfix/qmgr[1977]: C69FF402F0: from=<SOMEONE@gmail.com>, size=2710, nrcpt=1 (queue active)
Jan 30 11:23:49 mail postfix/pipe[90658]: C69FF402F0: to=<SOMEONE@MYDOMAIN>, relay=anonaddy, delay=0.7, delays=0.39/0.01/0/0.3, dsn=2.0.0, status=sent (delivered via anonaddy service)
Jan 30 11:23:49 mail postfix/qmgr[1977]: C69FF402F0: removed
Jan 30 11:23:49 mail postfix/smtpd[90676]: connect from localhost[127.0.0.1]
Jan 30 11:23:49 mail postfix/smtpd[90676]: SSL_accept error from localhost[127.0.0.1]: -1
Jan 30 11:23:49 mail postfix/smtpd[90676]: warning: TLS library problem: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../ssl/record/rec_layer_s3.c:1543:SSL alert number 48:
Jan 30 11:23:49 mail postfix/smtpd[90676]: lost connection after STARTTLS from localhost[127.0.0.1]
Jan 30 11:23:49 mail postfix/smtpd[90676]: disconnect from localhost[127.0.0.1] ehlo=1 starttls=0/1 commands=1/2
```

The email seems to be piped to AnonAddy just fine, but then it stops at an `SSL_accept error` with `tlsv1 alert unknown ca`, even though the connection is coming from localhost. The server certificate is from Let's Encrypt, it's valid and is served by nginx just fine. The certificate also hasn't changed since `v0.12.3`, where it has been accepted without a problem.

Any help on this would be appreciated, since I am running out of ideas how to solve this problem. Thank you!

**Comment by willbrowningme** [comment]
What do you have for your mail settings in your `.env` file?

```
# The from name to be used for outgoing email notifications from AnonAddy
MAIL_FROM_NAME=Example
# The from address to be used for outgoing email notifications from AnonAddy
MAIL_FROM_ADDRESS=mailer@example.com
MAIL_DRIVER=smtp
MAIL_HOST=mail.example.com
MAIL_PORT=25
MAIL_ENCRYPTION=tls
MAIL_EHLO_DOMAIN=mail.example.com
MAIL_VERIFY_PEER=true
```

**Comment by TheComp44** [comment]
Exactly like this, just with my own domain:
```env
# The from name to be used for outgoing email notifications from AnonAddy
MAIL_FROM_NAME=Mydomain
# The from address to be used for outgoing email notifications from AnonAddy
MAIL_FROM_ADDRESS=mailer@mydomain.de
MAIL_DRIVER=smtp
MAIL_HOST=mail.mydomain.de
MAIL_PORT=25
MAIL_ENCRYPTION=tls
MAIL_EHLO_DOMAIN=mail.mydomain.de
MAIL_VERIFY_PEER=true
```

**Comment by willbrowningme** [comment]
In `/etc/hosts` if you don't already have it set can you try making sure you have:

```
127.0.0.1 mail.mydomain.de localhost
```

and then try again.

**Comment by TheComp44** [comment]
I tried that, but there is still the `SSL_accept error`

**Comment by willbrowningme** [comment]
If you set `MAIL_VERIFY_PEER=false` does it still show the error?

**Comment by TheComp44** [comment]
Yes, the error is still there

**Comment by TheComp44** [comment]
The `MAIL_EHLO_DOMAIN` entry is already in my `.env` file. After running the command you suggested, the error still comes up unfortunately.

**Comment by willbrowningme** [comment]
You can try adding `smtpd_tls_CAfile=/etc/ssl/certs/ca-certificates.crt` or  `smtpd_tls_CAfile=/path/to/your/mail-server-ca`  to your `/etc/postfix/main.cf` file as mentioned here - https://github.com/Mailu/Mailu/issues/181
