### ISSUE TITLE
Thunderbird Conversations

### ISSUE THREAD

**Issue by gossi** [anonaddy/anonaddy#43]
Hello and thank you for that nice software + service.

I'm using it with thunderbird as my mail client. That is TB shows conversations (when enabled with the addon). However, mails coming in through anonaddy are not grouped into conversations. I turned off email banner off but that wasn't the right switch. I suspiciously looking at the `... <{mail}@{username}.anonaddy.com>` as addition to the `To:` field.. whether this might be causing it - Dunno if this is really the troublemaker.

Would love to have this nice feature of TB working again. I'm also happy to see an option, that I need to turn on for this.

**Comment by stefanschramek** [comment]
Great idea! I have the same issue when using Outlook!
Maybe the following could help https://www.jwz.org/doc/threading.html

Thanks
Stefan

**Comment by willbrowningme** [comment]
Hmm, I think this could be due to the Message-ID headers and the In-Reply-To headers.

I have tried to retain the Message-ID to be the same as the original but many kept causing errors to be thrown by Swift Mailer. 

I'll try to think of a way to solve this.

**Comment by willbrowningme** [comment]
@gossi @stefanschramek I've just pushed an update that should hopefully fix this issue.

Please could you give it a try and let me know.
