### ISSUE TITLE
Reply quote sanitation

### ISSUE THREAD

**Issue by Nypheena** [anonaddy/anonaddy#439]
is there any plans to add the FROM: email address quote sanitation like simplelogin has? even iCloud has it, at current the alias sent to will be the one in the quote on tutanota, protonmail and icloud and probably most other mail services if using reply-to header and the reply address if not using it, banner seems to be sanitized but the quote is an issue

hopefully this can become a priority as like the banner if not replaced/removed it is heavily deanonymizing and exposes you using an alias service

**Comment by willbrowningme** [comment]
Yes this is the same as #395 I've added it to the roadmap.
