### ISSUE TITLE
Failures when sending to/from custom domain name

### ISSUE THREAD

**Issue by combatant3** [anonaddy/anonaddy#44]
I believe I've enabled my domain name properly because most of the send/receive functionality is working with it. However, I discovered some edge cases where the emails don't seem to be sent/received.

Times where recipient does not get email:

1. Sending from an AnonAddy alias to a domain linked to AnonAddy.
Ex: To: alias1+alias2=aa-domain.com@user.anonaddy.com
where "aa-domain.com" is a domain that's linked to someone's AnonAddy account.

2. Sending from an AnonAddy alias to another AnonAddy alias.
Ex: To: alias1+alias2=user.anonaddy.com@user.anonaddy.com
*Note: alias2 also appears to not be auto-generated if it doesn't exist already. I'm not sure if this is the cause of the error but it's something I noticed.

--

Other than those two cases, the following seem to be working fine:
To: alias1+alias2=user.anonaddy.com@aa-domain.com
To: alias1+alias2=aa-domain.com@aa-domain.com
To: alias1+user=domain.com@aa-domain.com
To: alias1+user=domain.com@user.anonaddy.com
*Again, where domain.com is a general domain not linked to an AnonAddy account, and aa-domain.com is a domain linked to an AnonAddy account.

*Another note: I tested these circumstances a few different times, but only using one AnonAddy account instead of two separate accounts. So I was basically sending emails to myself, but with different aliases.

**Comment by xoengine** [comment]
I believe we are experiencing the same issue.  Just checking to see if anyone has had the opportunity to look into it?

**Comment by willbrowningme** [comment]
I will look into this again, it's tricky as I need to avoid any permanent forwarding loops from occurring.

**Comment by xoengine** [comment]
Thank you.  If you come up with something let me know and we can try it.

**Comment by willbrowningme** [comment]
Please could you test this out again and let me know if it gives the expected behaviour now.

**Comment by willbrowningme** [comment]
Closing for now.
