### ISSUE TITLE
[Bug Report] subscription change issue

### ISSUE THREAD

**Issue by Nypheena** [anonaddy/anonaddy#442]
It seems if you swap to lite plan on stripe to take effect next year anonaddy swaps you immediately down to lite with no pro rata refund or waiting until the new plan is meant to take effect

**Comment by willbrowningme** [comment]
Changing subscriptions happens immediately, this is the intended behaviour. It is not possible to schedule a subscription change for the end of the billing cycle.

If you change from the Pro plan to Lite half way through your current Pro subscription then your unused time on the Pro plan will be added as credit to your account.

**Comment by willbrowningme** [comment]
The fact that you were not charged to upgrade back to Pro proves that your Stripe details had the credit. If you send me an email with your username I can check in Stripe and confirm that this was the case.
