### ISSUE TITLE
Log of when an alias was last used

### ISSUE THREAD

**Issue by teeruku-github** [anonaddy/anonaddy#447]
Is there anyway to see when an alias was last used? something like a log 
example below
<img width="1163" alt="Screenshot 2023-04-29 at 11 43 21 AM" src="https://user-images.githubusercontent.com/57341203/235287182-7f3558b6-1c9d-4861-9035-2578aa7dc132.png">

**Comment by willbrowningme** [comment]
No, I don't keep a log of incoming messages like that. It is on the roadmap to add a "last used" date so you can see when an alias last forwarded/replied/sent an email - https://github.com/anonaddy/anonaddy/projects/1#card-52590977.
