### ISSUE TITLE
CNAME domainkey check fails

### ISSUE THREAD

**Issue by ririko5834** [anonaddy/anonaddy#454]
![image](https://github.com/anonaddy/anonaddy/assets/64729293/25dc49e4-dfd2-4161-bd2e-87716e559ad0)
I get this message 

![image](https://github.com/anonaddy/anonaddy/assets/64729293/994f1427-abe6-490d-bb37-042a5fd487c8)

My records: 
![image](https://github.com/anonaddy/anonaddy/assets/64729293/2b0cf93b-4db3-4461-b69c-c78b788d6fa5)

I receive emails normally but that error annoys me

**Comment by willbrowningme** [comment]
Please send me an email with your actual domain name so that I can check it for you.

**Comment by willbrowningme** [comment]
If you are self hosting make sure you have:

```
ANONADDY_DKIM_SELECTOR=default
```

in your `.env` file.

**Comment by ririko5834** [comment]
Yes Im selfhosting

**Comment by ririko5834** [comment]
> If you are self hosting make sure you have:
> 
> ```
> ANONADDY_DKIM_SELECTOR=default
> ```
> 
> in your `.env` file.

thanks worked
