### ISSUE TITLE
Problem with receiving emails from Ikea

### ISSUE THREAD

**Issue by dinauu** [anonaddy/anonaddy#456]
Hello.
I tried to register at [Ikea.com.tr](https://www.ikea.com.tr/en/), but I don't get the activation email. I tried to use several different domains, but nothing works. The "Failed Deliveries" section is empty.
I tried using an alias from another provider and it worked.

Thanks for the great service, been using it for a few weeks and no problems until now.

**Comment by willbrowningme** [comment]
Thanks, their HELO hostname could not be found which is why the messages were being rejected.

I've just whitelisted them so if you try again it should work now.
