### ISSUE TITLE
[question] self hosting requirements 

### ISSUE THREAD

**Issue by fareszr** [anonaddy/anonaddy#46]
hi i would like to self host anonaddy i already have a server with other services setup
since there is no documentation yet.
what do i need to self host anonaddy ?
i was thinking of :
php package 
apache (web server)
and mysql 
anything else ?
and also does self hosting unlock the pro features ?

**Comment by willbrowningme** [comment]
Please could you drop me an email and I'll send over the instructions I've got so far.

Yes self hosting unlocks all the features.

**Comment by fareszr** [comment]
> 
> 
> Please could you drop me an email and I'll send over the instructions I've got so far.
> 
> Yes self hosting unlocks all the features.

i couldn't find your personal email, i will contact you on contact@anonaddy.com

**Comment by fareszr** [comment]
another question, does the browser add-on work with self hosting ?

**Comment by willbrowningme** [comment]
> another question, does the browser add-on work with self hosting ?

It will work but you would need to edit any references to app.anonaddy.com/api/v1 etc. to point to your own self-hosted instance. Then you can build the browser add-on yourself and use it as normal.
