### ISSUE TITLE
Sign up / add recipiant email address validation rejects valid email addresses 

### ISSUE THREAD

**Issue by mzarglis** [anonaddy/anonaddy#463]
When trying to register using my personal email address of `me@michaelzargl.is` it says i must use a valid email which the address is. I also get this on the "Add new recipient" page when using the same email

**Comment by willbrowningme** [comment]
I just tested it and it added it without any issue, you will likely have received the verification email which you can ignore. Please try again and [send me an email](https://anonaddy.com/contact/) if you are still having issues.
