### ISSUE TITLE
Email aliases are recreated when someone sends email to it

### ISSUE THREAD

**Issue by ririko5834** [anonaddy/anonaddy#464]
Hello, it sometimes happens that when I use Forgot alias and someone sends email to it, it's re-created automatically on the dashboard 
![image](https://github.com/anonaddy/anonaddy/assets/64729293/9bfb8141-2708-47cd-a110-3615c1db1cc0)
I have catch-all disabled 
![image](https://github.com/anonaddy/anonaddy/assets/64729293/213c2e61-962a-416e-a545-78d5b2231c89)
What is the difference between Forget and Delete? Which should I use when I want to delete alias but I don't want it to be re-created automatically if someone sends email to it (when catch-all is disabled only) and at the same time I want it to be possible to restore it manually (by making alias on that domain with custom type and entering there deleted alias name?
Btw the alias notes arent restored if alias is re-created so I sometimes don't know which service was it used for.

I tried to "Delete" some alias and then recreate it but it doesnt work, it shows error that alias already exists
![image](https://github.com/anonaddy/anonaddy/assets/64729293/55bb2181-2e33-4c8b-b202-5ff28dc78835)

**Comment by willbrowningme** [comment]
That is the expected behaviour.

Please check the terminology here - https://anonaddy.com/help/

> Forgotten Alias - When an alias is forgotten it is completely disassociated from your account.

> - If the alias is a shared domain alias (e.g. @anonaddy.me) then it can never be restored or used again. Once a shared domain alias is forgotten, it will reject any emails sent to it with the same message as above.

> - If the alias is a standard alias then it can be created again in the future since it will be as if it never existed in the database. Once a standard alias is forgotten, if someone sends an email to it and you have catch-all enabled then it will be created automatically again. If you would like the alias to reject any messages sent to it then you should delete it or disable catch-all for that domain.

If you delete an alias then try to create it then you get that message because the alias does still exist in the database, you need to select to view deleted aliases from the dashboard and then you can restore it from there.

If you forget a standard alias and you have catch-all disabled for that username/domain then it will not be able to be automatically created again.
