### ISSUE TITLE
Unable to Register, No verification email. 

### ISSUE THREAD

**Issue by ashishbishnoi** [anonaddy/anonaddy#465]
I have port 25 open on my contabo server but I am not receiving any verification email while registering.
I am registering with a Gmail address. Here are the postfix logs:
`May 30 21:19:49 mail postfix/smtpd[4649]: connect from o1.ptr4846.authentisign.com[149.72.128.206]
May 30 21:19:50 mail postfix/smtpd[4649]: Anonymous TLS connection established from o1.ptr4846.authentisign.com[149.72.128.206]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange ECDHE (P-384) server-signature RSA-PSS (2048 bits) server-digest SHA256
May 30 21:19:55 mail postfix/smtpd[4649]: 53247260E1E: client=o1.ptr4846.authentisign.com[149.72.128.206]
May 30 21:19:55 mail postfix/cleanup[4653]: 53247260E1E: message-id=<N_uGuvBJQDS0z0xsLMVfNw@geopod-ismtpd-9>
May 30 21:20:00 mail postfix/qmgr[4449]: 53247260E1E: from=<bounces+25875436-04ca-noreply=secureemail.site@em1409.authentisign.com>, size=38465, nrcpt=1 (queue active)
May 30 21:20:00 mail postfix/smtpd[4649]: disconnect from o1.ptr4846.authentisign.com[149.72.128.206] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
May 30 21:20:00 mail postfix/pipe[4656]: 53247260E1E: to=<noreply@secureemail.site>, relay=anonaddy, delay=10, delays=9.8/0/0/0.26, dsn=2.0.0, status=sent (delivered via anonaddy service)
May 30 21:20:00 mail postfix/qmgr[4449]: 53247260E1E: removed`

**Comment by ashishbishnoi** [comment]
Yes, I have followed all the steps. Here's supervisor status:
`● supervisor.service - Supervisor process control system for UNIX
     Loaded: loaded (/lib/systemd/system/supervisor.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-05-30 20:46:51 +08; 57min ago
       Docs: http://supervisord.org
   Main PID: 399 (supervisord)
      Tasks: 9 (limit: 9477)
     Memory: 280.5M
     CGroup: /system.slice/supervisor.service
             ├─ 399 /usr/bin/python3 /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
             ├─5037 php /var/www/anonaddy/artisan queue:work redis --sleep=3 --tries=3
             ├─5038 php /var/www/anonaddy/artisan queue:work redis --sleep=3 --tries=3
             ├─5041 php /var/www/anonaddy/artisan queue:work redis --sleep=3 --tries=3
             ├─5059 php /var/www/anonaddy/artisan queue:work redis --sleep=3 --tries=3
             ├─5060 php /var/www/anonaddy/artisan queue:work redis --sleep=3 --tries=3
             ├─5069 php /var/www/anonaddy/artisan queue:work redis --sleep=3 --tries=3
             ├─5380 php /var/www/anonaddy/artisan queue:work redis --sleep=3 --tries=3
             └─5381 php /var/www/anonaddy/artisan queue:work redis --sleep=3 --tries=3

May 30 21:35:15 mail.secureemail.site supervisord[399]: 2023-05-30 21:35:15,681 INFO exited: anonaddy_01 (exit status 0; expected)
May 30 21:35:16 mail.secureemail.site supervisord[399]: 2023-05-30 21:35:16,684 INFO spawned: 'anonaddy_01' with pid 5079
May 30 21:35:16 mail.secureemail.site supervisord[399]: 2023-05-30 21:35:16,685 INFO success: anonaddy_06 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
May 30 21:35:17 mail.secureemail.site supervisord[399]: 2023-05-30 21:35:17,686 INFO success: anonaddy_01 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
May 30 21:39:22 mail.secureemail.site supervisord[399]: 2023-05-30 21:39:22,148 INFO exited: anonaddy_06 (exit status 1; not expected)
May 30 21:39:22 mail.secureemail.site supervisord[399]: 2023-05-30 21:39:22,149 INFO exited: anonaddy_01 (exit status 1; not expected)
May 30 21:39:23 mail.secureemail.site supervisord[399]: 2023-05-30 21:39:23,152 INFO spawned: 'anonaddy_01' with pid 5380
May 30 21:39:23 mail.secureemail.site supervisord[399]: 2023-05-30 21:39:23,154 INFO spawned: 'anonaddy_06' with pid 5381
May 30 21:39:24 mail.secureemail.site supervisord[399]: 2023-05-30 21:39:24,156 INFO success: anonaddy_01 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
May 30 21:39:24 mail.secureemail.site supervisord[399]: 2023-05-30 21:39:24,156 INFO success: anonaddy_06 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)`

**Comment by willbrowningme** [comment]
Please check the laravel logs at `/var/www/anonaddy/storage/logs`.

**Comment by ashishbishnoi** [comment]
I am getting relay access denied error in logs:
`[2023-05-30 14:38:47] production.ERROR: Expected response code "250/251/252" but got code "554", with message "554 5.7.1 <yibejit418@cutefier.com>: Relay access denied". {"exception":"[object] (Symfony\\Component\\Mailer\\Exception\\TransportException(code: 554): Expected response code \"250/251/252\" but got code \"554\", with message \"554 5.7.1 <yibejit418@cutefier.com>: Relay access denied\". at /var/www/anonaddy/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php:338)
[stacktrace]
#0 /var/www/anonaddy/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(201): Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->assertResponseCode()
#1 /var/www/anonaddy/vendor/symfony/mailer/Transport/Smtp/EsmtpTransport.php(105): Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->executeCommand()
#2 /var/www/anonaddy/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(264): Symfony\\Component\\Mailer\\Transport\\Smtp\\EsmtpTransport->executeCommand()
#3 /var/www/anonaddy/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(220): Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->doRcptToCommand()
#4 /var/www/anonaddy/vendor/symfony/mailer/Transport/AbstractTransport.php(69): Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->doSend()
#5 /var/www/anonaddy/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(137): Symfony\\Component\\Mailer\\Transport\\AbstractTransport->send()
#6 /var/www/anonaddy/app/CustomMailDriver/CustomMailer.php(169): Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->send()
`

**Comment by ashishbishnoi** [comment]
Hey, Thanks for the lead to laravel logs! There were several issues, I just solved them one by one and everything's working now.

**Comment by willbrowningme** [comment]
Great stuff and no problem.

**Comment by andre-paulo98** [comment]
I'm having the same problem. Do you still remember what you did to solve this? @ashishbishnoi
