### ISSUE TITLE
allow configuring the 'aliases per page' setting

### ISSUE THREAD

**Issue by 07416** [anonaddy/anonaddy#469]
At the bottom of the `app.anonaddy.com` page. Defaults to `25`.

I always lose my set value when [the site data is cleared in Firefox](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox) (set to be wiped when closing the browser).

Can the option be saved on a per-account basis or as a URL parameter (can be bookmarked), for instance?

**Comment by willbrowningme** [comment]
Thanks, should be able to add this as a URL parameter in the near future with the new UI. With options 25, 50 and 100.

**Comment by 07416** [comment]
> Thanks, should be able to add this as a URL parameter in the near future with the new UI. With options 25, 50 and 100.

Would adding a 250 as well be a stretch? How much resources loading all of the aliases (let's assume well over a thousand, for instance) at once would require?

Sure, there's a search function on the page, but I find it easier to use the native browser search whenever possible.

**Comment by willbrowningme** [comment]
I've just added a new page size option to the aliases page so you can now view up to 100 per page.

**Comment by 07416** [comment]
> I've just added a new page size option to the aliases page so you can now view up to 100 per page.

the URL is `https://app.addy.io/aliases?page_size=100` (& `page_size=25`, `50`)
