### ISSUE TITLE
Recipient Alias count is wrong

### ISSUE THREAD

**Issue by stefanschramek** [anonaddy/anonaddy#47]
Hi,

it seems that the count for aliases at recipient tab is wrong, as it shows 0 for one email address and adds all recipient to the default email address:

![image](https://user-images.githubusercontent.com/921342/81729717-bcace080-948c-11ea-86ff-6efdd7634c4e.png)

At the domains tab it is correct:

![image](https://user-images.githubusercontent.com/921342/81729828-eb2abb80-948c-11ea-992f-37dddf6bf5ba.png)

Thanks
Stefan

**Comment by willbrowningme** [comment]
Hi Stefan, are you sure that the count is wrong?

The default recipient in your first screenshot has a total of 133 aliases which must have been the total number of aliases on your account at the time.

In your second screenshot with your domains you can see that the bottom domain has 125 aliases. This means that you must have had 133 - 125 = 8 aliases that were at your unique username subdomain or at an AnonAddy shared domain (anonaddy.me / 4wrd.cc).

I think that is why there is a difference between the two.

**Comment by stefanschramek** [comment]
The 8 aliases that are left are used with a different custom domain and are pointing to the recipient with key 2, which shows 0 aliased in the first screenshot.
For my understanding in the first screenshot it should show 8 for recipient with key 2 and 125 recipients with key 1.

**Comment by willbrowningme** [comment]
This issue should be fixed in the latest [commit](https://github.com/anonaddy/anonaddy/commit/8ecc24657bbbaeae32c91621e6ad3291d1a4728e).
