### ISSUE TITLE
'from' email should be the 'reply'/'forward' email

### ISSUE THREAD

**Issue by martin-braun** [anonaddy/anonaddy#474]
My first impression is positive. I bought premium, because I want to support the service. I'm coming from IronVest, formerly known as Blur. I noticed something that I miss, which was this way in my former service.

When I receive a mail that was redirected, it will be sent from `mailer@anonaddy.me`. This is a big problem for me, because when I respond, the email client will not keep this conversation together properly.

At IronVest it was solved like this: 

<img width="489" alt="Screenshot 2023-06-23 at 07 08 43" src="https://github.com/anonaddy/anonaddy/assets/24259245/4b9b2945-f40f-4c3c-a11e-5e372f968930">

As you can see, the 'from' mail is the actual mail I will sent my response to. This way, my email client is able to keep the conversation in one thread.

I want to support this project, but this is a critical issue for me.

**Comment by willbrowningme** [comment]
Your custom domain is not verified for sending which is why the messages are being forwarded from `mailer@anonaddy.me` instead of the actual alias.

Please go to the [domains page](https://app.anonaddy.com/domains) and click "Check Records" to see which DNS records you need to add to your domain.
