### ISSUE TITLE
Use a different Sender Name for each Alias?

### ISSUE THREAD

**Issue by martin-braun** [anonaddy/anonaddy#475]
It would be nice if I could change my Sender Name for each alias. For instance, I want to share my real name only with entities I trust. I still don't trust such entities enough to give them my real email address for good reasons.

**Comment by willbrowningme** [comment]
This is a duplicate of #279 and has already been added to the [roadmap](https://github.com/anonaddy/anonaddy/projects/1#card-79830989).

**Comment by martin-braun** [comment]
@willbrowningme How did I miss that ... thanks for the prompt response.
