### ISSUE TITLE
Multiple default recipients for domain

### ISSUE THREAD

**Issue by GJurriens** [anonaddy/anonaddy#478]
Hello,

I would like to do a feature request. Is it possible to have the default recipient for a domain have multiple addresses, just like you can custom setup for a specific alias. I have a domain I'm using with aliases, but the recipients should be my girlfriend and I (cause it is mail considering us both).
The way it is now, I would need to change it for every single recipient to sent it to both of us in stead of the default recipient.

Thank you for your time and effort.

Kind regards,
Guido Jurriens

**Comment by willbrowningme** [comment]
Thanks for the suggestion, this is already on the roadmap [here](https://github.com/anonaddy/anonaddy/projects/1#card-68636917). I don't have an estimated date for it at the moment.
