### ISSUE TITLE
Add option to 'From' be the true sender

### ISSUE THREAD

**Issue by joaonunovalente** [anonaddy/anonaddy#479]
Right now, we have the option to the 'From' header to be:

- alias@username.anonaddy.com
- alias+sender=example.com@username.anonaddy.com

Would be nice that we could also have the option:

- sender@example.com

That would be easier to know who is the email from and would add the possibility to answer directly to it, using our email.

I know the last reason ignores the main purpose of anonaddy, but still.

**Comment by willbrowningme** [comment]
It is not possible to have the original sender as the `From:` header because AnonAddy forwards the messages on as entirely new emails and this would cause all authentication checks to fail and messages to be rejected.

**Comment by joaonunovalente** [comment]
Yeah... That actually makes sense!

Another sugestion then.

Would it be possible to have the `Sender:` be another email instead of the alias?

For instance:

**From:** sender@username.anonaddy.com
**Reply-to:** sender+example=sender.com@username.anonaddy.com
**To:** sender@username.anonaddy.com

Could the `To:` email be our own email?

**Comment by willbrowningme** [comment]
The `To:` could be your recipient's email e.g. `you@gmail.com` yes.
