### ISSUE TITLE
Self-Hosted | Not working with incoming emails.

### ISSUE THREAD

**Issue by tommyvange** [anonaddy/anonaddy#48]
I recently installed the self-hosted version on my server but I cant for the life of me get incoming emails to work. It can send emails just fine (verification and password reset), but it doesn't recognize incoming emails.

The emails are not bouncing either, they are just not being handled by anonaddy.

Any ideas as to what error logs I can check or configs I can dubblecheck?

**Comment by willbrowningme** [comment]
Have you checked /var/log/mail.log to see what happens when the email arrives at your server?

Have you made sure that your /etc/postfix/master.cf is correct and is set to pipe incoming emails to your web application?

**Comment by willbrowningme** [comment]
The error looks like the issue is that you do not have the mailparse php module installed.

Please try running `php -m` from the server and see if the mailparse module is shown.

**Comment by tommyvange** [comment]
That was it, thank you so much!

For anyone else running into the same issue, you can install mailparse by using to following command:
`sudo apt-get install php-mailparse`
