### ISSUE TITLE
When you remove record from custom domain or it expires, it doesnt show error

### ISSUE THREAD

**Issue by ririko5834** [anonaddy/anonaddy#486]
Hi, when you remove some needed record like MX from custom domain or the custom domain expires and all records are removed, it still acts as active on dashboard 
there is that green ✔️ 
![image](https://github.com/anonaddy/anonaddy/assets/64729293/a0e3d352-2307-4168-9e99-cd10b3da8919)
only after you run recheck it shows error 
![image](https://github.com/anonaddy/anonaddy/assets/64729293/40766233-12fb-4469-a3c8-90ee82700a4c)

I think that it should display ❌ when records couldn't be found and it should send a notification to your email address that records for custom domain arent set up correctly, would be useful.

**Comment by willbrowningme** [comment]
These checks already happen each day as can be seen here - [https://github.com/anonaddy/anonaddy/blob/master/app/Console/Kernel.php#L27-L28](https://github.com/anonaddy/anonaddy/blob/master/app/Console/Kernel.php#L27-L28)

An email notification is already sent out if any records are missing.
