### ISSUE TITLE
option to forward original eml without modified headers, allowing SpamCop to make an abuse report

### ISSUE THREAD

**Issue by e075e** [anonaddy/anonaddy#488]
Hi,
it would be useful to have an option that enable anonaddy to forward the original eml with untouched headers.
In this way, the spam received can be forwarded to services like [SpamCop](https://www.spamcop.net) to make an abuse reports to the spammer's Internet Service Provider.
This will benefit all the email users

Thanks for your app
Luca

**Comment by willbrowningme** [comment]
All of the original `Received` headers are already included in forwarded emails which I believe is what SpamCop uses to determine the origin.

**Comment by willbrowningme** [comment]
Hmm, it would be useful to see the email so we can determine how SpamCop came to that conclusion. If it happens again please send me an email and let me know.
