### ISSUE TITLE
[Feature Request] Quick reply mail calculator

### ISSUE THREAD

**Issue by luckydonald** [anonaddy/anonaddy#490]
I always struggle a bit to remember how to create outgoing links.

Hence, it would be handy to have a “generator” for those outgoing mails.

Basically, I propose two fields:

> Outgoing Email: `test@example.com`
> Email Alias: `example-test`

Which would display a `mailto:` link right below:

> Email to send to: [example-test+test=example.com@luckydonald.anonaddy.com](mailto:example-test+test=example.com@luckydonald.anonaddy.com)

Ideally it would immediately update when any of the input fields change, so you can “learn” from example as well, just in case. And because nobody likes clicking an extra button for that.

I would place that easily reachable from the main anonaddy page of your account. 
For placing my ideas would be either as a widget above the list (as it doesn't take up much space), or as a separate page linked in the menu.

**Comment by willbrowningme** [comment]
This already exists in the web application, browser extension and mobile apps.

In the web application from the aliases page, click the 3 dots on the right hand side of the table, then click "Send From" to display the modal.

I will be making this more visible shortly.
