### ISSUE TITLE
Faulty notification "DNS check failed"

### ISSUE THREAD

**Issue by ProfNeck** [anonaddy/anonaddy#491]
Hi,

I recently signed up for the "Lite" subscription and added a custom domain. Everything works great but I receive an email every morning, claiming "Your domain has been unverified for sending on AnonAddy".

The exact error message reads:

> CNAME dk2._domainkey record not found. This could be due to DNS caching, please try again later.

I haven't noticed any impediments in sending or receiving messages and after clicking on "Recheck", it shows "fully verified" again (until the next morning), no problem. The CNAME-records concerned are either `dk1._domainkey` or `dk2._domainkey`.

I tried adjusting the TTL (between 10min and 1hr) in the DNS settings to no avail.

Any idea how to solve this?

Best regards

**Comment by willbrowningme** [comment]
Is this still occurring?

**Comment by ProfNeck** [comment]
No, fortunately, you were able to solve this problem when I contacted you via mail.
Unfortunately, though, my github account was banned for using an addy.io-adress, lol. Sorry for the belated answer.
