### ISSUE TITLE
"Default recipient updated" shows same mail adress

### ISSUE THREAD

**Issue by ProfNeck** [anonaddy/anonaddy#492]
Hi,
when updating my default mail recipient, I noticed that the notification email showed the new (=updated) recipient 2x instead of "`new-email@example` to `new-email@example`".

Here is the mail I received:

> Default Recipient Updated
> 
> Your account's default recipient has just been updated from **new-email@example** to **new-email@example**.
> 
> If this change was not made by you, please visit the settings page, click the button to log out of all other browser sessions and then update your account's password.

Best regards and sorry for opening two issues right after another

**Comment by willbrowningme** [comment]
Sorry I must have completely missed this issue, should all be fixed now, thanks!
