### ISSUE TITLE
API doesn't provide defaultAliasDomain if not explicitly set

### ISSUE THREAD

**Issue by tomtjes** [anonaddy/anonaddy#493]
While a new account currently automatically has anonaddy.me set as the default domain, this value is not returned by the API upon querying `api/v1/domain-options`. Only after the user has clicked on `Update Default Alias Domain` in their settings, the API returns the value for `defaultAliasDomain` correctly.

**Comment by willbrowningme** [comment]
Thanks, just pushed an update to fix this, default values will now be provided for `defaultAliasDomain` and `defaultAliasFormat`.
