### ISSUE TITLE
Update source code in this repo to the latest version

### ISSUE THREAD

**Issue by ririko5834** [anonaddy/anonaddy#494]
When will you update source code in this repo to the latest version with new branding addy.io, I saw the UI design was improved and also some new features, when will be the source code here updated?

**Comment by willbrowningme** [comment]
When I get time I will update this repository. Please stop opening new issues just to ask a simple question.

**Comment by ririko5834** [comment]
Ok, sorry, I should used discussions for that.

**Comment by ririko5834** [comment]
Do you think it will be updated this month?

**Comment by ririko5834** [comment]
@willbrowningme
