### ISSUE TITLE
X-Anonaddy-Authentication-Results needs to be switched from anonaddy.me to addy.io?

### ISSUE THREAD

**Issue by stites** [anonaddy/anonaddy#495]
My mail client has started to attach this banner to my emails:

![image](https://github.com/anonaddy/anonaddy/assets/1694705/58444208-f707-4263-ac88-83923f26a2bb)

I'm guessing it's just having to do with the branding switch -- the header in question currently points to mail.anonaddy.me:
```
X-Anonaddy-Authentication-Results: mail.anonaddy.me;
```

I don't *think* this is related to #485, but I'm tagging it anyways -- just in case.

**Comment by willbrowningme** [comment]
`mail.anonaddy.me` is the hostname for the mail server, that is not changing.

That banner has been added to ensure that you are warned about any potential spoof attempts.

I'm keeping the header name as `X-Anonaddy-Authentication-Results` for now too as I don't want to break any filters etc. that people may have set up.

No, this is not related to 485.

**Comment by wjhrdy** [comment]
I've seen this banner on a couple of forwarded emails for my custom domains over the last couple of days. They were legit emails. not sure what is causing it.

**Comment by willbrowningme** [comment]
If an email fails DMARC checks or has spammy / suspicious content then it may be added.
