### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by rrn21833** [anonaddy/anonaddy#500]
After switching to a new domain name, I did two-step verification again, and found that the beautiful logo was not displayed.

**Comment by rrn21833** [comment]
@willbrowningme Settings→Security→Two-Factor Authentication→Authentication App (TOTP)
![BB715F15-CBAE-4389-AA6F-0902EC105C92](https://github.com/anonaddy/anonaddy/assets/37966911/764ed6e1-7278-49ac-a0b8-ad2fec747743)

**Comment by rrn21833** [comment]
@willbrowningme 
![D674F1CB-C09D-4264-8163-B033FEF4FB7F](https://github.com/anonaddy/anonaddy/assets/37966911/e30f8e8c-efc0-4008-80b1-5e5d0207f5e7)

**Comment by willbrowningme** [comment]
What authentication app are you using on your phone?

**Comment by rrn21833** [comment]
> What authentication app are you using on your phone?

Tofu
![AACF2E37-BC7C-41AA-9B35-C45DCF1A6899](https://github.com/anonaddy/anonaddy/assets/37966911/aaa0c3f0-ce56-4065-a09c-5744d5771902)

**Comment by willbrowningme** [comment]
Thanks, I've opened a [PR](https://github.com/iKenndac/Tofu/pull/132) to add the new icon.

**Comment by rrn21833** [comment]
Authentication App (TOTP)’s icon is still "A".

Will Browning ***@***.***>于2023年8月21日 周一16:53写道：

**Comment by willbrowningme** [comment]
@rrn21833 that is because the maintainer(s) of the Tofu code have not yet merged my changes - https://github.com/iKenndac/Tofu/pull/132.
