### ISSUE TITLE
UI inconstancy recipient settings

### ISSUE THREAD

**Issue by Stjin** [anonaddy/anonaddy#502]
When "Hide Email Subject" is enabled the "Use PGP/Inline Encryption" switch is disabled (cannot be clicked) and a tooltip shows up on hover
![image](https://github.com/anonaddy/anonaddy/assets/23135973/02c975ea-f372-4ff9-99fb-3a14787c3a05)

However, when "Use PGP/Inline Encryption" is enabled the "Hide Email Subject" switch is still enabled and will throw an error.
![image](https://github.com/anonaddy/anonaddy/assets/23135973/0219ae40-8d30-4dc4-b99f-9787b8b83b22)

It would be more consistent when the "Hide Email Subject" is disabled just like the "Use PGP/Inline Encryption" switch.

**Comment by willbrowningme** [comment]
Thanks, I've just pushed a fix for this!
