### ISSUE TITLE
Can't access to my account

### ISSUE THREAD

**Issue by argalad** [anonaddy/anonaddy#503]
I have to verify my account again after the change to addy.io and the email I was using as account is no longer available. They're sending me a verification email there but as I cannot access I have the option to change the email, and when I try and enter my verification code, the following appears:
This content is blocked. Contact the site owner to fix the issue.
What can I do?

**Comment by willbrowningme** [comment]
Please [send me an email](https://addy.io/contact/) with more details including your username.
