### ISSUE TITLE
Unavailable from Firefox addon site

### ISSUE THREAD

**Issue by rycee** [anonaddy/anonaddy#505]
The anonaddy Firefox addon no longer seems to be accessible from the Mozilla addon site: https://addons.mozilla.org/en-US/firefox/addon/anonaddy/

Do you know if this is temporary or permanent? It seems to be gone since (approximately) August 16.

**Comment by willbrowningme** [comment]
The extension has been renamed after the [rebrand](https://addy.io/blog/anonaddy-has-rebranded-as-addy-io/) and can be found here - [https://addons.mozilla.org/en-US/firefox/addon/addy_io/](https://addons.mozilla.org/en-US/firefox/addon/addy_io/).

**Comment by rycee** [comment]
Thanks for the quick response!
