### ISSUE TITLE
[Feature Request] monthly lite plan for a little more than $1

### ISSUE THREAD

**Issue by braboobssiere** [anonaddy/anonaddy#506]
in case of emergency sometimes a site or service just locked your account out and there's a need to contact them by sent email from alias but anonaddy only have yearly lite plan ($12) or monthly pro plan ($3), which seems a bit wasteful since it wouldn't really fits the purpose of short duration sent (which free plan doesn't support, lite plan is too long and pro plan seems overkill for the functionality needed)

does it possible to add monthly lite plan for $1.25 or $1.5 or maybe a 15 days lite plan for $1?

**Comment by willbrowningme** [comment]
I'm afraid I don't currently have any plans to make the Lite plan available monthly as it would not be worth while due to Stripe processing fees for such a small payment.

**Comment by ririko5834** [comment]
Maybe there should be free trial available for lite plan so people can first try it before purchasing. Foe example simplelogin has 7 day long free trial of their paid plan
