### ISSUE TITLE
Allow rules to dictate the recipient(s)

### ISSUE THREAD

**Issue by a-lam** [anonaddy/anonaddy#512]
I would like to be able to control recipients base on rules. For instance, if I wanted to allow my spouse to create aliases that send to both of us, couple.wildcard@customdomain.com. Or if they wanted to create aliases spouse.wildcard@customdomain.com. while everything else at customdomain.com is the default recipient.

_Originally posted by @a-lam in https://github.com/anonaddy/anonaddy/discussions/334#discussioncomment-6833237_

**Comment by martin-braun** [comment]
I strongly support this take. I just discovered rules and would love to be able to redirect based on some conditions.

Here is my real life example: I have a mail that occasionally receives invoices that I wish to automatically redirect into a different inbox. Sure, there are email clients that allow setting up rules, but having something like this on the gateway level would be a pleasure.

Lastly I kindly ask this feature to be available on the Lite plan.

**Comment by willbrowningme** [comment]
I've just added this as an action to the rules called "Forward to", please give it a go and let me know what you think.

It only works on `forwards` and not `replies` or `sends` from aliases.
