### ISSUE TITLE
Very slow forwarding

### ISSUE THREAD

**Issue by jaljol** [anonaddy/anonaddy#516]
I have for two days now had a very slow service from Anonaddy. To test it, i sent an email from another email address and it was received 47 minutes later.

This is unacceptable and if not resolved, I must find another service.

**Comment by willbrowningme** [comment]
This happened on Tuesday due to a very large increase in emails that caused a backlog. It should now be resolved, please try by testing again now and everything should be okay.

Apologies for the inconvenience.
