### ISSUE TITLE
Subdomain handling seems wrong

### ISSUE THREAD

**Issue by GJurriens** [anonaddy/anonaddy#518]
Hello,

I'm having some issue's when receiving and sending mail from a subdomain.
I'm running Addy in Docker on the latest version v0.14.1
My setup:
Addy domain: example1.com
Custom domain: sub.example2.com

When I receive a mail to (for example) test@sub.example2.com, I will see test@example2.com in the to address in the mail client (also in the headers, the reply-to address is correct).
When checking the Verified Records for custom domains, it seems like it is not checking the subdomain. I have checked my DNS records and they are correct, but still those checks fail. This also means that sending mail using the alias (or replying to a mail sent to an alias) will bounce back telling me settings are incorrect (mail from Addy).

I hope someone can help me out with this as I really like the product.

**Comment by willbrowningme** [comment]
Please [send me an email](https://addy.io/contact/) with details of the actual subdomain so that I can check the DNS records.
