### ISSUE TITLE
I cant send reply/send email from aliases 

### ISSUE THREAD

**Issue by ririko5834** [anonaddy/anonaddy#523]
I selfhost anonaddy and I can't send reply from aliases.
I always get this error. I tried with  multiple recipents - protonmail and seznam.cz email, but all don't work and anonaddy rejects my emails and refuses to forward it.

![image](https://github.com/anonaddy/anonaddy/assets/64729293/d1630fff-50e4-4b7b-88a7-48a6cd095051)

Anonaddy logs: https://pastebin.com/raw/s3BF2sDB

**Comment by ririko5834** [comment]
@willbrowningme

**Comment by willbrowningme** [comment]
You need to make sure you have Rspamd running and the correct headers are being added `/etc/rspamd/local.d/milter_headers.conf`. See the "Rspamd" section of the [self-hosting](https://addy.io/self-hosting/) instructions.

**Comment by ririko5834** [comment]
I use anonaddy docker and dont close issues when it wasn't solved

**Comment by ririko5834** [comment]
also why you still didnt update this github repo to the latest anonaddy version?

**Comment by ririko5834** [comment]
@willbrowningme When it will be updated?
