### ISSUE TITLE
Bitwarden Firefox extension error

### ISSUE THREAD

**Issue by bitsByB** [anonaddy/anonaddy#526]
Same error as this user: https://www.reddit.com/r/Bitwarden/comments/16h8ely/anonaddy_addyio_every_browser_extension_gives/
Domain and api token (starting with addy_io_) set correctly.
Thanks
![image](https://github.com/anonaddy/anonaddy/assets/102392085/e1784e40-dd84-4c07-9a0d-b33cdc4766d5)

**Comment by willbrowningme** [comment]
Please [send me an email](https://addy.io/contact/) with your username so I can check what the issue is.

**Comment by willbrowningme** [comment]
Browser extension needed updating to use the new API endpoint.
