### ISSUE TITLE
[Bug] Setting the "Alias From Name" clears the alias description and vice versa

### ISSUE THREAD

**Issue by samirgunic** [anonaddy/anonaddy#527]
Setting the **"Alias From Name"** in the Edit Alias view, _inadvertently clears_ the **alias description**. The opposite is true as well: setting the alias description, inadvertently clears the "Alias From Name". It's either this or that. You can't have it both.

I have used AnonAddy (or just _Addy_) for about two years now, and I never had a need to set a From name for an alias until recently, and when I did need to do that, I discovered this bug.

**Comment by willbrowningme** [comment]
Thanks for letting me know, I've just fixed this now.
