### ISSUE TITLE
[Bug] Editing deleted alias results in 404 Not Found

### ISSUE THREAD

**Issue by samirgunic** [anonaddy/anonaddy#528]
As the title says, I am getting a **"404 Not Found"** status code when trying to edit a deleted alias (_I need to restore it_).

Starting off by viewing _deleted aliases only_:
`https://app.addy.io/aliases?deleted=only`

I click on the Edit button for a given alias, on the right hand side, and I'm presented with a "404 Not Found", and a rather cool looking 404 art image, depicting a camel standing on a desert dune in the distance.

![addy-the-camel](https://github.com/anonaddy/anonaddy/assets/3742529/82881d99-13dd-456a-b4ef-9fbf85222315)

This issue is present for all my deleted aliases. Other aliases are not affected. I don't recall seeing this issue before, with the old version of the AnonAddy UI.

I notice the GUID is missing from the URL.

Normally, the URL for editing an alias looks like this:

`https://app.addy.io/aliases/9ebfd982-9af8-4436-bffb-5a3827c864da/edit`

One of my deleted aliases looks like this:

`b88e346d-551e-4b9f-b225-6729eab21547@4wrd.cc`

(_Note: This e-mail address is used for demonstration purpose only. It's not the actual address._)

It's the only one I made with a GUID as the local part of the e-mail address. Assuming the same GUID is used to ID this alias, I figured I should be able to navigate to it directly, so I can edit it, in case it's just a bad link.

But unfortunately, this didn't work:

`https://app.addy.io/aliases/b88e346d-551e-4b9f-b225-6729eab21547/edit`

So it's a deeper issue I think.

**Comment by willbrowningme** [comment]
Thanks for reporting this, I've just fixed this too.

**Comment by samirgunic** [comment]
That was faster than fast! 😃 Much appreciated. Thanks!

I see now that this is one of the new features.
https://addy.io/blog/anonaddy-has-rebranded-as-addy-io/

Aside from a few bugs like these, I really love the new interface! Just so you know. Alias counts are now displayed correctly, which is a massive improvement in my book. It's the small things like that, that make up a greater whole, and a great product. Keep up the great work, and thanks again!
