### ISSUE TITLE
[Feature Request] Lightning Payments Dependant Forwarding

### ISSUE THREAD

**Issue by santyr** [anonaddy/anonaddy#529]
It'd be awesome to be able to create aliases associated with lightning lnurls or bolt11 invoices which only forward email after an set amount of sats are paid.

This would act as a type of spam filter.

See also: https://github.com/strikewalker/reacher

**Comment by willbrowningme** [comment]
Thanks a lot for the suggestion. I'm afraid that I don't have any plans to add anything like this at the moment. So will close this issue for now.
