### ISSUE TITLE
Switching from monthly to yearly payment

### ISSUE THREAD

**Issue by Damdrara** [anonaddy/anonaddy#532]
According to the Pricing page, yearly subscriptions are an option, and cheaper than monthly. 

However, I picked a monthly pro subscription at first to try it out before fully committing. Now that I'm ready to do so, I can't find a way to change my subscription to yearly though. I even tried cancelling the subscription and renewing, but nope, not a thing. Please make it so, so I can throw more money at you!

**Comment by willbrowningme** [comment]
You should be able to change without any issue.

Please could you [send me an email](https://addy.io/contact/) with your username so that I can check you account?
