### ISSUE TITLE
[Self Hosting] issue with spamhaus filtering

### ISSUE THREAD

**Issue by Mr-Sheep** [anonaddy/anonaddy#533]
spamhaus no longer allows query with public dns server without registering their DQS: [Using our public mirrors? Check your return codes now.](https://www.spamhaus.org/news/article/807/using-our-public-mirrors-check-your-return-codes-now)

the following config (commented out part) in `/etc/postfix/main.cf` will now return all emails to the sender:
```
smtpd_recipient_restrictions =
   permit_mynetworks,
   reject_unauth_destination,
   check_recipient_access mysql:/etc/postfix/mysql-recipient-access.cf,
   # reject_rhsbl_helo dbl.spamhaus.org,
   # reject_rhsbl_reverse_client dbl.spamhaus.org,
   # reject_rhsbl_sender dbl.spamhaus.org,
   # reject_rbl_client zen.spamhaus.org
   reject_rbl_client dul.dnsbl.sorbs.net
```

with the error message: `host mail.exmaple.com[0.0.0.0] said: 554 5.7.1
    Service unavailable; Helo command [mail-xxxxx.protonmail.ch] blocked using
    dbl.spamhaus.org; Error: open resolver;
    https://www.spamhaus.org/returnc/pub/172.69.x.x (in reply to RCPT TO
    command)
`

**Comment by willbrowningme** [comment]
You should be using a local DNS resolver as mentioned in the [self-hosting](https://addy.io/self-hosting/) guide under "Setting up a local caching DNS resolver".
