### ISSUE TITLE
Banner info not always showing correctly 

### ISSUE THREAD

**Issue by jaljol** [anonaddy/anonaddy#536]
Hi

Most of my received emails show the banner info correctly. But sometimes it just shows as plain text:

This email was sent to *email* from *email*.
To deactivate this alias copy and paste the url below into your web browser.

https://emea01.safelinks.protection.outlook.com/?url=https...

**Comment by jaljol** [comment]
Before and after the text above, there is a "". But somehow that was editied out of my post.

**Comment by willbrowningme** [comment]
That is the intended behaviour in order to keep plain text only messages as plain text. Which is why the email banner is also just plain text.

Otherwise every message would be forced as HTML.
