### ISSUE TITLE
Incorrect option in "Update Display From Format" user setting

### ISSUE THREAD

**Issue by aik099** [anonaddy/anonaddy#539]
Hello,

The "Update Display From Format" user setting (on https://app.addy.io/settings page) has `John Doe - johndoe(a)example.com` option, but it works as if it was `John Doe - johndoe(at)example.com` (the `(a)` replaced with `(at)`).

I like how it works, but maybe the option text needs to be changed to `John Doe - johndoe(at)example.com` as well.

Thank you.

**Comment by willbrowningme** [comment]
Thanks for letting me know, `John Doe - johndoe(a)example.com` is actually the correct version. I've just updated it so that should now come through on newly forwarded messages.
