### ISSUE TITLE
Self-Hosted | Emails can not be received

### ISSUE THREAD

**Issue by tommyvange** [anonaddy/anonaddy#54]
Hello, I recently installed Anonaddy but I can not seem to figure out why I cant receive incoming emails. Outgoing emails work just fine.

I checked the `/var/log/mail.log` log, but there is nothing new being created there when I send a new email. The emails are also not bouncing.

Are there any other error logs I can check?

**Comment by willbrowningme** [comment]
Have you made sure to include the correct lines in your `/etc/postifx/master.cf` file to pipe the email through to the application?

Do you have the correct MX record set up for the domain you are using?

**Comment by tommyvange** [comment]
I was being an absolute idiot and managed to misspell my domain in the MX records.

Thanks.
