### ISSUE TITLE
[Feature Request] Admin can completly delete Accounts

### ISSUE THREAD

**Issue by eriCCsan** [anonaddy/anonaddy#541]
Hi guys,
I was looking for this function but I could not find it. 
I just want to delete an account. But how?
If this is not included, I recommend at least implementing a console command that can be used like CreateUser.
I can do it myself, but before that I want to ask if I searched wrong or this is not intended here?
regards :-)

**Comment by willbrowningme** [comment]
You can delete an account by running the following commands in Laravel tinker:

```php
$user = Username::firstWhere('username', 'johndoe')?->user;

DeleteAccount::dispatch($user);
```

Where `johndoe` is the username of the account and `DeleteAccount` is the job that is dispatched that actually deletes it.
