### ISSUE TITLE
Add plus-address sub-recipient

### ISSUE THREAD

**Issue by bafbl** [anonaddy/anonaddy#546]
This is requesting an additional option for the Recipients page: An "Add plus-address recipient" option to an existing, validated Recipient which would request the +address information and create an automatically validated recipient with the same public key. 

In case the motivation behind this isn't clear... I've found it useful to categorize my inbound email within Addy by having about a dozen +addresses for my backend email address which are then processed by fairly static mailbox filter rules. Obviously, I was able to create/validate/publickey the Recipients with the current UI, but it was pretty tedious.

**Comment by willbrowningme** [comment]
Thanks for the suggestion, this doesn't sound like a common occurrence and due to some checks that are carried out when verifying an email I don't have any plans to add this at this time.
