### ISSUE TITLE
What will happen to addy.io in case of @willbrowningme's death?

### ISSUE THREAD

**Issue by limonte** [anonaddy/anonaddy#548]
Good day Will,

I am sorry to bother you with this very uncomfortable question, but I must ask.

As I can see from the activity, you're the only person behind addy.io development. And it might be that you're the only person behind the company.

You look young and healthy and I hope you live at least up to 100 years, but death comes to everyone in the least expected moment.

What will happen to addy.io in such a scenario?

From the users' perspective, losing the long list of email aliases would be extremely painful. In most cases, it'd be possible to change an account's email address easily while in some cases it might get tricky.

Once again, I'm sorry about this question. I wish you a great day!

**Comment by ccorneli** [comment]
He talks about that in the FAQ

https://addy.io/faq/#what-happens-to-addy-io-if-you-die

**Comment by limonte** [comment]
Oh, sorry for not checking FAQ first 🤦 

Thank you @ccorneli
