### ISSUE TITLE
Ability to create a user through artisan

### ISSUE THREAD

**Issue by crazy-max** [anonaddy/anonaddy#55]
Hi @willbrowningme,

It would be nice to allow creation of user through artisan with something like:

```shell
$ php artisan user:add --password=mypwd --email=anonaddy@example.com --role=admin --no-ansi --no-interaction anonaddy
```

This way we could remove the static [`DatabaseSeeder.php`](https://github.com/crazy-max/docker-anonaddy/blob/master/rootfs/var/www/anonaddy/database/seeds/DatabaseSeeder.php) for our Docker image and let the user decide its credentials.

**Comment by willbrowningme** [comment]
Hi, I'm not too familiar with the docker image but is there any reason why you cannot just use the /register page to register the initial user account?

**Comment by crazy-max** [comment]
Hi @willbrowningme,

> Hi, I'm not too familiar with the docker image but is there any reason why you cannot just use the /register page to register the initial user account?

Yes we could do that but how can we create an admin user?

**Comment by willbrowningme** [comment]
There isn't really an admin user as such, you would just need to register a user normally and then add this to your `.env` file.

`ANONADDY_ADMIN_USERNAME=johndoe`

Then it will allow the default yourdomain.com to behave as a catch-all.

Then you can disable registration for anyone else by adding

`ANONADDY_ENABLE_REGISTRATION=false` 

to your `.env` file and refreshing the cache (`php artisan config:cache`).

**Comment by crazy-max** [comment]
@willbrowningme Ok sounds good to me, I will add a note about that for the Docker image.
