### ISSUE TITLE
Buttons of the "Create new alias" modal are missing :focus-visible outlines hence not quite accessible

### ISSUE THREAD

**Issue by limonte** [anonaddy/anonaddy#557]
The same as #555 

I guess this is the downside of Tailwind CSS and going through all the buttons and adding the appropriate classes is needed.

![CleanShot 2023-11-21 at 11 13 07](https://github.com/anonaddy/anonaddy/assets/6059356/4ab961f4-8b70-4c10-b37d-7b52d5efb4be)

**Comment by willbrowningme** [comment]
Thanks, I've just fixed this and tried to make the rest of the site more accessible for keyboard users.
