### ISSUE TITLE
reply-to broken?

### ISSUE THREAD

**Issue by fbartels** [anonaddy/anonaddy#56]
Hi,

I've created an account because I am looking for ways to simplify my alias handling (for multiple domains, but just very few mailboxes).

I have then from another mailserver sent a mail to example@username.anonaddy.com. This mail was then received at the configured final destination, which is a Cloudron setup with Roundcube as the webmailer. But when I now click on reply in roundcube, then the answer will be sent to the same final destination and not to the original sender.

**Comment by willbrowningme** [comment]
Hi, apologies for the late response.

Are you making sure that you reply using an email address that **exactly** matches a verified recipient on your AnonAddy account?

If you reply from any other email then it will be forwarded on instead of sent as a reply.

**Comment by fbartels** [comment]
Hi @willbrowningme,

thanks and not problem at all.

You were right the reply to did not work simply because for testing I did deliver the mail to a catchall inbox and the actual reply address was a different one, than the one anonaddy originally delivered to. After setting the recipient to my actual address reply-to works as well.
