### ISSUE TITLE
git-send-mail and Content-Transfer-Encoding

### ISSUE THREAD

**Issue by onemoresuza** [anonaddy/anonaddy#561]
Does addy change the `Content-Transfer-Encoding` header when sending from an alias?

I'm asking this, because, no matter which `--transfer-encoding` option I pass to `git-send-mail` --- `8bit`, `7bit`, `base64`, `auto` ---, every email that reaches a mailing list has its `Content-Transfer-Encoding` header is set to `quoted-printable`.

**Comment by willbrowningme** [comment]
Each email forwarded by addy.io is sent on as an entirely new email, Laravel is using Symfony mailer to send the messages. Yes `Content-Transfer-Encoding` is automatically set as `quoted-printable`.

Unfortunately it doesn't look like there is an easy way to set the encoding in Symfony mailer, it also looks like the only supported encoding options are `quoted-printable`, `base64` and `8bit` - https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Mime/Part/TextPart.php#L66

If I can find a good way to implement this I'll include it.
