### ISSUE TITLE
I  cant get a access to my email...

### ISSUE THREAD

**Issue by shvakicha** [anonaddy/anonaddy#565]
Recently, I registered my mail there and linked it to the discord. As a result, nothing came there because I set it up incorrectly, accidentally clicked delete 2 times... After 1 hour, my account crashed and started demanding to log in, I enter my password and username and this is what it shows me. help me
![2023-12-01_23-41-24](https://github.com/anonaddy/anonaddy/assets/152647822/9c223808-c33a-40ee-9a6c-f08ba0524f3e)

**Comment by willbrowningme** [comment]
Have you tried resetting your password?
