### ISSUE TITLE
Self-Hosted Blank page

### ISSUE THREAD

**Issue by ptah4i** [anonaddy/anonaddy#57]
Hey guys

I try to setup on a local machine for testing but get a blank page when I visit the site. 

Any suggestions?

**Comment by ptah4i** [comment]
Solved.

**Comment by willbrowningme** [comment]
Great, what was the problem in the end in case someone else experiences the same thing?

**Comment by jon-bit** [comment]
I'm experiencing the same thing. can you tell us?

**Comment by willbrowningme** [comment]
@jon-bit Please can you check the Laravel log file for any errors? 

`/var/www/anonaddy/storages/logs/`

**Comment by jon-bit** [comment]
there is no log files
but when I go to the address I get a blank page
