### ISSUE TITLE
Feedback regarding updated Display From Format

### ISSUE THREAD

**Issue by vlad-timofeev** [anonaddy/anonaddy#571]
Hi there, thanks for a new major version with the revamped UI. I have updated from `v0.14.1` to `v1.0.4` and it went mostly smoothly, but I encountered one issue, which took me some time to figure out, and I wanted to leave feedback.

Apparently the default `From` header format was changed

from
`sender@sendersdomain.com <somealias+sender=sendersdomain.com@mydomain.com>`
to 
`sender at sendersdomain.com <somealias+sender=sendersdomain.com@mydomain.com>`

This caused my email filters to break because they match `From` header by patterns like `sender@sendersdomain.com` , which conveniently is an actual sender email address, but with the new format it no longer matches. I am currently considering to update my filters to match somehow differently, for example by `sender at sendersdomain.com` or `sender=sendersdomain.com`, or maybe switch to the custom header  `X-AnonAddy-Original-Sender` header, because there [doesn't seem to be an option to keep the prior format](https://github.com/anonaddy/anonaddy/blob/dc88b9bcd25f8a4f5f394bb51b03473ca338bea0/app/Mail/ForwardEmail.php#L385-L398) , and I could not find a specific issue/PR that clarifies the need for the change. 

Question 1: out of curiosity, what was the rationale for this change?

Suggestion 1: outline this as a breaking change in the release log, so folks who update can quickly spot it.

**Comment by willbrowningme** [comment]
Thanks for the feedback, this was added with v1.0.0 along with the rebrand update. To be honest I completely forget to mention it. I've just added it to the release notes now - [https://github.com/anonaddy/anonaddy/releases/tag/v1.0.0](https://github.com/anonaddy/anonaddy/releases/tag/v1.0.0)

The reason for the change is to reduce the chance of messages being rejected as spam. If an email is forwarded and the display from part of the From header is `support@paypal.com` for example then many email providers will assume this to be a phishing attempt and reject the message.
