### ISSUE TITLE
Block registration with this domains (ToS violations)

### ISSUE THREAD

**Issue by ghost** [anonaddy/anonaddy#578]
```
mailbox.zip
sailmail.io
maskmy.id
```

Provider is https://skiff.com/quick-alias and it's actually subdomains, each user can generate their own subdomain. I tested it, very easy.

The page title of https://skiff.com/quick-alias is "Quick alias burner email address". In the HTML I see

<meta name="description" content="Secure and quick-to-create burner email addresses with Skiff!
There is a browser plugin https://github.com/irazasyed/email-masker to create one email per website, skiff.com's twitter account promoted it, the github repository is tagged as 'burner-email'

You should add:

maskmy.id because it is there main domain
anything.maskmy.id because it allows you to create disposable addresses with random subdomains

![IMG_1721](https://github.com/anonaddy/anonaddy/assets/155534304/ccaa6c06-37d8-471b-98d5-5cd0b4f12b98)
![IMG_1720](https://github.com/anonaddy/anonaddy/assets/155534304/5b5b311b-b2e6-4aee-a6b9-7417efb205d0)
![IMG_1719](https://github.com/anonaddy/anonaddy/assets/155534304/b562cc3c-4e59-4669-a801-0866e49cd4c2)

**Comment by Fhciv** [comment]
@willbrowningme
