### ISSUE TITLE
User Disabled Error

### ISSUE THREAD

**Issue by StodgyWaif** [anonaddy/anonaddy#580]
Hello. I'm not sure if this is the correct place to report this but I get this error when emailing one of my aliases:

mail2.anonaddy.me
Remote server returned '552 5.2.1 <(name)@anonaddy.me>: Recipient address rejected: User disabled'

I tried disabling and re-enabling the alias but still the same error.

**Comment by willbrowningme** [comment]
That means that your account has been disabled for breaking the terms and conditions of the service, most likely:

`using the Service to create a large number of accounts on other websites/services`

- https://addy.io/terms/

**Comment by StodgyWaif** [comment]
I see now and thank you for responding.
