### ISSUE TITLE
Can't add my custom domain

### ISSUE THREAD

**Issue by jaljol** [anonaddy/anonaddy#581]
Hi

I can't add my custom domain.
I get this error:
![image](https://github.com/anonaddy/anonaddy/assets/105918187/7fb283ef-d11c-4685-a406-9331aa50a6b9)

"The domain must not already be used by a verified recipient."
I don't use this domain for any recipient.

**Comment by willbrowningme** [comment]
Please [send me an email](https://addy.io/contact/) and let me know the domain that you are trying to add.
