### ISSUE TITLE
Email aliases for custom domain are not passing mailbox validation

### ISSUE THREAD

**Issue by mamciek** [anonaddy/anonaddy#583]
I experience problems using anonaddy aliases (custom domain) on some sites (for example using as Apple ID apple.com, and wizzair.com). The email address is rejected as invalid address. 
I have investigated the issue a little bit and found out that Apple is using a verification called "Mailbox validation" which is verifying whether the mailbox associated with the email address exists and can receive emails. Apparently it is some kind of protocol that mailserver should support (?).

You can check any email at this website for a validation: https://verifalia.com/validate-email
Whenever I use any of my anonaddy alias I get a message:

`MailboxValidationTimeout`

<img width="667" alt="Screenshot 2024-01-16 at 20 04 09" src="https://github.com/anonaddy/anonaddy/assets/180237/4eb965e4-9a64-4e2c-b7de-02a6d76df188">

**Comment by willbrowningme** [comment]
The issue with the `MailboxValidationTimeout` seems to be due to [Postscreen](https://www.postfix.org/POSTSCREEN_README.html) running on the mail server. I'm looking into it now to see how to resolve it.

**Comment by willbrowningme** [comment]
It seems that the IP addresses Verifalia.com uses for their tests are listed on a number of blacklists e.g. [https://multirbl.valli.org/lookup/146.70.235.211.html](https://multirbl.valli.org/lookup/146.70.235.211.html)

I've attempted to whitelist them, please try again and let me know if the tests are now successful.

**Comment by willbrowningme** [comment]
It looks like they had another range of IPs, please try again now.

**Comment by mamciek** [comment]
<img width="691" alt="Screenshot 2024-01-24 at 15 42 45" src="https://github.com/anonaddy/anonaddy/assets/180237/d741d9be-a54f-40bd-bb0c-0d26a6ebdbd9">

There is an improvement :). It passed to the next step.

**Comment by willbrowningme** [comment]
That message is just because you have catch-all enabled for your custom domain. For some reason they class that as "risky". You can disable catch-all for your domain from the [domains page](https://app.addy.io/domains) if you wish.

Unfortunately Apple may be using other checks or means to block the aliases that we don't know about. Closing this as the [https://verifalia.com](https://verifalia.com/validate-email) checks should now be working correctly.

**Comment by mamciek** [comment]
Thank you. I can only confirm that now (after disabling catch-all in domain settings) [verifies](https://verifalia.com)[https://verifalia.com](https://verifalia.com/validate-email) verifies my email as  
<img width="613" alt="Screenshot 2024-01-24 at 18 02 26" src="https://github.com/anonaddy/anonaddy/assets/180237/4bf62d73-a246-425e-8301-782011eff573">

Unfortunately Apple still rejects it :(
