### ISSUE TITLE
[self-hosted] No verification email sent - no logs

### ISSUE THREAD

**Issue by buxm** [anonaddy/anonaddy#584]
I'm setting up a self hosted instance on Google Cloud.
Google Cloud doesn't allow outbound port 25. However I configured postfix to use Mailjet as a relay host on port 587 to send outbound emails.
After following the installation instructions, I registered the administrator user.
But then I didn't get the verification email.
Even when I click on "Resend verification email", wait until I see the "A fresh verification link has been sent to your email address." message, no email is received.

I cannot find any log that can help me investigate. Am I missing something? How can I debug this issue?

Addy version: current master branch on Git (I presume v1.0.4).
```
sudo service supervisor status
● supervisor.service - Supervisor process control system for UNIX
     Loaded: loaded (/lib/systemd/system/supervisor.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2024-01-21 14:36:29 UTC; 4h 10min ago
       Docs: http://supervisord.org
   Main PID: 442 (supervisord)
      Tasks: 9 (limit: 2337)
     Memory: 263.6M
        CPU: 1min 9.650s
     CGroup: /system.slice/supervisor.service
             ├─   442 /usr/bin/python3 /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
             ├─ 91631 php /var/www/anonaddy/artisan queue:work redis --sleep=3 --tries=3
             ├─ 91632 php /var/www/anonaddy/artisan queue:work redis --sleep=3 --tries=3
             ├─ 91647 php /var/www/anonaddy/artisan queue:work redis --sleep=3 --tries=3
             ├─ 94140 php /var/www/anonaddy/artisan queue:work redis --sleep=3 --tries=3
             ├─103028 php /var/www/anonaddy/artisan queue:work redis --sleep=3 --tries=3
             ├─104579 php /var/www/anonaddy/artisan queue:work redis --sleep=3 --tries=3
             ├─105232 php /var/www/anonaddy/artisan queue:work redis --sleep=3 --tries=3
             └─105911 php /var/www/anonaddy/artisan queue:work redis --sleep=3 --tries=3

Jan 21 18:18:06 mail.addy-test.buxnet.net supervisord[442]: 2024-01-21 18:18:06,881 INFO success: anonaddy_01 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Jan 21 18:22:06 mail.addy-test.buxnet.net supervisord[442]: 2024-01-21 18:22:06,338 INFO exited: anonaddy_07 (terminated by SIGKILL; not expected)
Jan 21 18:22:07 mail.addy-test.buxnet.net supervisord[442]: 2024-01-21 18:22:07,346 INFO spawned: 'anonaddy_07' with pid 104579
Jan 21 18:22:08 mail.addy-test.buxnet.net supervisord[442]: 2024-01-21 18:22:08,351 INFO success: anonaddy_07 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Jan 21 18:23:37 mail.addy-test.buxnet.net supervisord[442]: 2024-01-21 18:23:37,183 INFO exited: anonaddy_02 (terminated by SIGKILL; not expected)
Jan 21 18:23:38 mail.addy-test.buxnet.net supervisord[442]: 2024-01-21 18:23:38,222 INFO spawned: 'anonaddy_02' with pid 105232
Jan 21 18:23:39 mail.addy-test.buxnet.net supervisord[442]: 2024-01-21 18:23:39,227 INFO success: anonaddy_02 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Jan 21 18:25:08 mail.addy-test.buxnet.net supervisord[442]: 2024-01-21 18:25:08,229 INFO exited: anonaddy_05 (terminated by SIGKILL; not expected)
Jan 21 18:25:09 mail.addy-test.buxnet.net supervisord[442]: 2024-01-21 18:25:09,235 INFO spawned: 'anonaddy_05' with pid 105911
Jan 21 18:25:10 mail.addy-test.buxnet.net supervisord[442]: 2024-01-21 18:25:10,240 INFO success: anonaddy_05 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

`/var/log/mail.log`: no log after clicking "Resend verification email"
`/var/log/mail.err`: no log after clicking "Resend verification email"
`/var/log/php8.2-fpm.log`: no log after clicking "Resend verification email"
`/var/log/nginx/access.log`
```
127.0.0.1 - - [21/Jan/2024:18:21:06 +0000] "POST /email/resend HTTP/1.1" 302 422 "https://addy.example.com/email/verify" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
127.0.0.1 - - [21/Jan/2024:18:21:08 +0000] "GET /email/verify HTTP/1.1" 200 416 "https://addy.example.com/email/verify" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
```
`/var/log/nginx/error.log`: no log after clicking "Resend verification email"
`/var/log/supervisor/supervisord.log`
```
2024-01-21 18:22:06,338 INFO exited: anonaddy_07 (terminated by SIGKILL; not expected)
2024-01-21 18:22:07,346 INFO spawned: 'anonaddy_07' with pid 104579
2024-01-21 18:22:08,351 INFO success: anonaddy_07 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-01-21 18:23:37,183 INFO exited: anonaddy_02 (terminated by SIGKILL; not expected)
2024-01-21 18:23:38,222 INFO spawned: 'anonaddy_02' with pid 105232
2024-01-21 18:23:39,227 INFO success: anonaddy_02 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-01-21 18:25:08,229 INFO exited: anonaddy_05 (terminated by SIGKILL; not expected)
2024-01-21 18:25:09,235 INFO spawned: 'anonaddy_05' with pid 105911
2024-01-21 18:25:10,240 INFO success: anonaddy_05 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```
`/var/log/supervisor/anonaddy_07-stdout---supervisor-5v4ysyfb.log`
```
2024-01-21 18:21:06 App\Notifications\CustomVerifyEmail ............ RUNNING
```
`/var/log/supervisor/anonaddy_02-stdout---supervisor-fl_vnnsu.log`
```
2024-01-21 18:22:37 App\Notifications\CustomVerifyEmail ............ RUNNING
```
`/var/log/supervisor/anonaddy_05-stdout---supervisor-vzctg9t8.log`
```
  2024-01-21 18:24:07 App\Notifications\CustomVerifyEmail ............ RUNNING
  2024-01-21 18:25:07 App\Notifications\CustomVerifyEmail ............ 1m FAIL
```
`/var/www/anonaddy/storage/logs/laravel-2024-01-21.log`: no log after clicking "Resend verification email"

Many thanks for any help you can provide.

**Comment by willbrowningme** [comment]
Is port 587 open on the server?

**Comment by buxm** [comment]
Yes, I can successfully netcat the Mailjet server on port 587 from the machine where I installed Addy.io.

**Comment by willbrowningme** [comment]
The only thing I can think is that it must be related to the Postfix Mailjet config. If you remove all of the Mailjet config and set it back to default are any errors then shown?

**Comment by buxm** [comment]
I've just tried to remove everything regarding relayhost and sasl from /etc/postfix/main.cf.
The result is the same as before: no verification email, no meaningful log, apart from:
/var/log/supervisor/anonaddy_05-stdout---supervisor-g3_ti7ze.log
```
  2024-01-22 21:07:41 App\Notifications\CustomVerifyEmail ............ RUNNING
  2024-01-22 21:09:14 App\Notifications\CustomVerifyEmail ............ RUNNING
  2024-01-22 21:10:15 App\Notifications\CustomVerifyEmail ............ 1m FAIL
```

Maybe for some reason Postfix wasn't trying to use Mailjet as a relay host even before... but I would expect some log line of at least attempting to send the email somehow....
I've also edited Postfix's master.cf putting `smtp -v` and `smtpd -v` everywhere in place of `smtpd` and `smtp` in the "command+args" column. But no logs for the outgoing email.
However I do get verbose logs in /var/log/mail.log when someone from the outside world (maybe bots or spammers) attempts to connect to my Postfix on port 25.

I presume there is actually no other log file that I should be checking....

**Comment by willbrowningme** [comment]
If you look at the database are there any jobs listed in the `failed_jobs` table for those `App\Notifications\CustomVerifyEmail` failures?

**Comment by willbrowningme** [comment]
Yes symfony mailer cannot connect via SMTP which is causing it to timeout, you'll have to find out why that is to resolve it. I'm closing this as it doesn't look like an issue with addy.io itself.

**Comment by buxm** [comment]
I found out that my server on Google Cloud resolves its hostname (e.g. `mail.example.com`) to its _public_ IP address, not its private or localhost one. This likely causes routing issues so essentially you cannot connect to `mail.example.com` from the server itself.
So I had to set `MAIL_HOST=localhost` in the Addy.io `.env` file and also remove the variables `MAIL_ENCRYPTION` and `MAIL_VERIFY_PEER` to avoid using TLS on the connection to localhost which would fail the validation of the certificate's FQDN.
Alternatively I could have added `127.0.0.1 mail.example.com` in my `/etc/hosts` file, but I preferred touching as few configuration files as possible in my setup process.
Now emails get correctly sent through Mailjet as a relayhost.

As a feedback for Addy.io, I found it a bit difficult to debug issues due to logs being scattered in multiple places.
What I collected so far is:
- `/var/log/mail.log`: Postfix logs
- `/var/log/mail.err`: Postfix errors - but not sure when it is used
- `/var/log/php8.2-fpm.log`: PHP logs
- `/var/log/nginx/access.log`: log of HTTP requests
- `/var/log/nginx/error.log`: NGINX errors
- `/var/log/supervisor/*.log`: Supervisor logs - other logs generated by PHP code
- `/var/www/anonaddy/storage/logs/laravel*.log`: PHP app logs
- `failed_jobs` table on DB: error logs generated by failed jobs (presumably those run by crontab)
- maybe also `failed_deliveries` table on DB

Maybe a documented list of places to look for relevant logs, and ideally what they contain, would help in such instances.

Anyway thank you so much @willbrowningme for pointing me to the right place! :-)
