### ISSUE TITLE
Stats Counter

### ISSUE THREAD

**Issue by philippzett** [anonaddy/anonaddy#586]
The forwarded mails are displayed incorrectly in the dashboard and under Alias. Too many forwarded mails are displayed.
![dashboard](https://github.com/anonaddy/anonaddy/assets/71732175/5d3a1e92-eccb-46e9-b7f3-68ed9af7e239)
![aliases](https://github.com/anonaddy/anonaddy/assets/71732175/28ec06bc-8054-40f6-bc36-fd54a4380bd2)

**Comment by willbrowningme** [comment]
The "Emails Forwarded" count includes deleted aliases. Please view the aliases including deleted ones (https://app.addy.io/aliases?deleted=with) and it should be correct.

**Comment by philippzett** [comment]
There are no deleted aliases.

**Comment by willbrowningme** [comment]
Please let me know your username (you can [send me an email](https://addy.io/contact/)) so I can check your account.
