### ISSUE TITLE
[Bug] Passkey creation on YubiKey with Chrome via Windows 10 fails

### ISSUE THREAD

**Issue by chstdu** [anonaddy/anonaddy#598]
Creating a PassKey for unbox.at on my YubiKey via Windows 10 fails. After entering the correct YubiKey PIN and touching the button on the YubiKey, I get following error:
![image](https://github.com/anonaddy/anonaddy/assets/1130593/896b6aef-3256-4d07-b8d5-240d0a53e664)

Passkeys work on other sites like Google, Microsoft or webauthn.io.

**Comment by chstdu** [comment]
Especially, they creation process does not fall back to variant 2 "Hardware Security Key (e.g. YubiKey, SoloKey, Nitrokey)". It would be clearer if you could select in advance whether to use variant 2 or variant 3 "Passkeys (which can be stored in a supported provider such as Bitwarden or 1Password)".

**Comment by willbrowningme** [comment]
Can this be replicated on the official instance? Also unbox.at must disclose their source code under the [AGPL-3.0 license terms](https://github.com/anonaddy/anonaddy/blob/master/LICENSE.md).

**Comment by chstdu** [comment]
Thank you for the quick reply. Now I tried it on addy.io again but the same error occurs. Check the attached screen recording.
[YubiKey failure.webm](https://github.com/anonaddy/anonaddy/assets/1130593/504a0531-3629-45e7-b41e-f3b92ba1361c)

**Comment by willbrowningme** [comment]
Could you try this demo application of the package I'm using to provide this - https://webauthn.asbin.net/

**Comment by chstdu** [comment]
Thanks for your investigations. The same error happens there too. See the attached screenshot. It seems that the issue was already reported under https://github.com/asbiin/laravel-webauthn/issues/438 in July 2023 but there is no response so far.

![image](https://github.com/anonaddy/anonaddy/assets/1130593/ef86e5e6-7630-45f3-8353-462d5efe625a)

**Comment by willbrowningme** [comment]
Closing this issue as it is with a package and not addy.io itself.
