### ISSUE TITLE
Make Redis actually optional

### ISSUE THREAD

**Issue by vensko** [anonaddy/anonaddy#6]
https://github.com/anonaddy/anonaddy/blob/2294f26926e7227b9dd73463c1b82ba2c5654a9c/app/Console/Commands/ReceiveEmail.php#L124

This method is hardcoded to use Redis, making Redis non-optional.

**Comment by anonaddy** [comment]
Thank you, I should not have said that Redis was optional in the readme file. I've just updated the [prerequisites section](https://github.com/anonaddy/anonaddy#prerequisites) to reflect this.

If you really do not want to use Redis then you can simply remove that line and the function from `ReceiveEmail.php` and also make sure your queue driver is set to something else (e.g. database).
