### ISSUE TITLE
Self Hosted | Email bounce when fowarded/Domain part missing

### ISSUE THREAD

**Issue by slurdge** [anonaddy/anonaddy#60]
When forwarding the mail, the sender is rewritten but it bounces like so:
```
status=bounced (host spool.mail.gandi.net[217.70.178.1] said: 504 5.5.2 <mailer+example=example.org>: Sender address rejected: need fully-qualified address (in reply to RCPT TO command))
```

My guess is that the domain part is missing and thus not added after the part that should be before the @.
Related to this, the new aliases miss the domain part too (but are active).
Could it come from the fact that
`ANONADDY_DOMAIN` and `ANONADDY_HOSTNAME` are the same domain ?

**Comment by slurdge** [comment]
To add to it, here is what i see when I have users.

![image](https://user-images.githubusercontent.com/1651201/90646573-a5258680-e237-11ea-9cad-c6e9b41364db.png)

I don't understand from the code where the domain part is populated from. Probably it's lost somewhere or there is a step that I missed.

**Comment by willbrowningme** [comment]
Have you populated the `ANONADDY_ALL_DOMAINS` .env variable? This is just a list of all the domains you are using and want to allow other users to be able to use too.

**Comment by willbrowningme** [comment]
It should be a comma separated list in your .env file like this:

`ANONADDY_ALL_DOMAINS=anonaddy.com,anonaddy.me`

**Comment by slurdge** [comment]
Yes that was it! I just tried and everything works as expected. I actually tried it while you commented, but I couldn't find it in the docs (apart from the .env.example file).
@crazy-max @willbrowningme Maybe we can derive this variable from the ANONADDY_DOMAIN variable if the ALL_DOMAINS one is empty ?

**Comment by crazy-max** [comment]
@slurdge 

> Maybe we can derive this variable from the ANONADDY_DOMAIN variable if the ALL_DOMAINS one is empty ?

I think this should be done directly through the app? WDYT @willbrowningme?

**Comment by willbrowningme** [comment]
Yes I think that would be best, the relevant code is line 328 of the User model. 

https://github.com/anonaddy/anonaddy/blob/master/app/User.php#L328

I'll push an update shortly.

**Comment by willbrowningme** [comment]
Updated in v0.2.10 - https://github.com/anonaddy/anonaddy/releases/tag/v0.2.10
