### ISSUE TITLE
[Bug] IDN domain names

### ISSUE THREAD

**Issue by afarrag** [anonaddy/anonaddy#600]
Hi,

I'm unable to add an Internationalized Domain Name. I receive the message ```Please enter a valid domain name```. Is there a workaround?

The domain looks something like ```ابجدهوز.مصر```
I also tried the punycode for it which is: ```xn--mgbcmmp9jh.xn--wgbh1c```
but I get the same error message

Thanks!

**Comment by afarrag** [comment]
PR #601 should fix it

**Comment by afarrag** [comment]
Also, it appears that [Postfix SMTPUTF8 support](https://www.postfix.org/SMTPUTF8_README.html) needs to be enabled to allow for Unicode localparts.

**Comment by willbrowningme** [comment]
Please could you try again now, the punycode version should work.

**Comment by afarrag** [comment]
Thanks @willbrowningme, it works perfectly! I'm very grateful

Now I'm getting a new error if I try to send to a Unicode alias:
`local-part of envelope RCPT address contains utf8 but remote server did not offer SMTPUTF8 `
Should I file it in a separate issue?

**Comment by willbrowningme** [comment]
The addy.io mail servers do not support SMTPUTF8 and non-ASCII characters in the local part are not accepted.
