### ISSUE TITLE
bulk change recipients?

### ISSUE THREAD

**Issue by CouldBeThis** [anonaddy/anonaddy#61]
Hello, 

I have decided to a new email address. Is there a way to change *all* the forwards to a given address to point somewhere else?  

cheers

**Comment by willbrowningme** [comment]
You can change the default recipient in your account settings. This will update where all emails (that don't have other recipents attached) will be forwarded.

If you have manually attached a recipent to a number of aliases and now want to change it, then this will have to be done individually at the moment I'm afraid.
