### ISSUE TITLE
[Error] ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by jia-ruey** [anonaddy/anonaddy#610]
Got this error message when I tried to access https://app.addy.io 😇

**Comment by willbrowningme** [comment]
What browser are you using? Are you able to show a screenshot.

**Comment by jia-ruey** [comment]
> What browser are you using? Are you able to show a screenshot.

![image](https://github.com/anonaddy/anonaddy/assets/127482794/924a0795-d709-43d6-aa2a-05c6cef03bc5)

**Comment by willbrowningme** [comment]
Closing this for now as I cannot find any issues after some checks, if it persists there is a chance your IP has been blocked, please send me an email and I will sort it for you.
