### ISSUE TITLE
Invalid MAC after updating

### ISSUE THREAD

**Issue by AdrianColaianni** [anonaddy/anonaddy#617]
I am experiencing a "500 | Service Error" when logging in after updating from v0.13.4 to v1.0.9.  Upon looking though logs I find the message "The MAC is invalid." from `Encrypter.php`.  I believe this is the same issue as [Issue 333](https://github.com/anonaddy/anonaddy/issues/333). However, my .env file hasn't changed since Feb 2023 so it is not possible that the APP_KEY changed.  When updating, I followed the instructions as they were outlined in `SELF_HOSTING.md` and did not accidentally run `php artisan key:generate`.

```
$ stat .env
  File: .env
  Size: 2738            Blocks: 8          IO Block: 4096   regular file
Device: fe01h/65025d    Inode: 2065397     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1001/johndoe)   Gid: ( 1003/johndoe)
Access: 2024-03-13 13:41:04.138259665 -0400
Modify: 2023-02-10 14:56:22.524674551 -0500
Change: 2023-02-10 14:56:22.524674551 -0500
 Birth: 2022-01-25 17:27:14.454660932 -0500
```

**Comment by willbrowningme** [comment]
What's the full stack trace of the error?

If it's the same as in #333 then it appears to be happening when trying to decrypt the `two_factor_secret` on the User model.

Do you have 2FA enabled?

**Comment by willbrowningme** [comment]
Could you try wrapping your `APP_KEY` in your `.env` file in double quotes.

```
APP_KEY="...."
```

**Comment by AdrianColaianni** [comment]
No effect, same error message.

**Comment by willbrowningme** [comment]
What if you add `BCRYPT_ROUNDS=10` to your `.env` file and then run:

```bash
php artisan clear-compiled
php artisan config:cache
php artisan view:cache
php artisan route:cache
php artisan event:cache
php artisan queue:restart
```

After that I honestly have no idea I'm afraid, comparing the two versions I cannot see any changes that could have caused this.

The `HasEncryptedAttributes.php` trait is the same - https://github.com/anonaddy/anonaddy/compare/v0.13.4...v1.0.9#diff-b6edb0729ca07e90af550e08b7605f809015a5ccc22c1a16f2e304fadbd787d6

**Comment by willbrowningme** [comment]
Any luck trying my previous suggestion?

**Comment by AdrianColaianni** [comment]
It unfortunately didn't fix the issue.  I tired reverting versions and that also did not fix it.

**Comment by AdrianColaianni** [comment]
I've nuked the database and effectively reinstalled to get it working (I took backups).  Is there a way to set a catch-all on my main domain as a way to get my aliases back?

**Comment by AdrianColaianni** [comment]
> I've nuked the database and effectively reinstalled to get it working (I took backups). Is there a way to set a catch-all on my main domain as a way to get my aliases back?

I solved this by setting `ANONADDY_ADMIN_USERNAME` to my username, and now any emails sent to non-existant aliases are sent to me.

**Comment by willbrowningme** [comment]
Set `ANONADDY_ADMIN_USERNAME=` to your account's username in your `.env` file.
