### ISSUE TITLE
Issue replying or sending from Custom Domain on primary email address

### ISSUE THREAD

**Issue by evannadeau** [anonaddy/anonaddy#620]
I'm working through an issue, and I thought it was related to me using an alias name for receiving initially.  Alias forwards were being sent to _name_+addyio@_domain_ and as expected that was not working, as my replies would come from _name_@_domain_ which was not a registered email at the time.

I have adjusted my account and default email address to _name_@_domain_. It has worked for replies to other aliases and even to some aliases under my custom domain, but not to a select few. Could this just be a timing issue, and I need to wait for this change to replicate between servers? Or maybe I should change my default email address to another address?

**Comment by evannadeau** [comment]
This continues to be very strange.  I made a new alias bob@domain.com, and it works fine receiving and responding from the default email.  I did a forget on the existing problem alias, and re-created it, leaving the default recipient address in place.  Sent a test, tried to respond, came right back to me.

I'm baffled.

**Comment by willbrowningme** [comment]
Please [send me an email](https://addy.io/contact/) with details of your domain and the actual alias "bob@domain.com".

**Comment by evannadeau** [comment]
Logs inspected by Will, and found that mail provider may be stripping out something.  However it is still only for two specific aliases.  Very strange.  Maybe someone else will find this helpful one day.

I did try switching to a different mail account with outlook.com, but was still doing it.  Used a gmail account for these two aliases and it was OK.  PITA, but gotta do what you gotta do.
