### ISSUE TITLE
[Feature Request] Store & display failed reply/send attempt + allow sending them manually

### ISSUE THREAD

**Issue by luckydonald** [anonaddy/anonaddy#627]
The situation is, for some unknown reason anonaddy suddenly dislikes my DNS records in place; SPF, DKIM and DMARC. Yesterday it did work fine. This suddenly makes it impossible for me to send mails.

I propose two additions:

1. _**Failed replies or sends get stored.**_
  The idea here is, it would be quite interesting to be able to actually investigate the incoming spoofed mail in detail, currently the only info available is email and subject, but no actual content.
   - (this would be quite similar to failed deliveries)
   
2. _**A button to send them anyway.**_
  Imagine I have an email I have to reply to urgently. Like in the next half an hour.
  But I just got anoaddy's automated rejection email, telling me it could be spoofed.
  This is not the perfect time to fondle with domain settings, trying to make it work, so I can send a mail out.
    - provide a button to ignore the warning and just send this one message
  
  
  Storing them that way also means your mail you spend an hour writing on, didn't just go poof, just because it couldn't be DNS verified.
I believe storing those mails is in the interest of a user, both for legitimate own mails as well as actual wrong ones,
but as storing such thing was a concern before, a setting to turn that off and an additional one to automatically delete them after e.g. 14 days would make sense.

**Comment by willbrowningme** [comment]
The message you spent an hour writing will not be lost as it will be saved in your email providers "Sent" items.

The authentication results are also shown in the notification email for you to investigate - https://github.com/anonaddy/anonaddy/blob/master/app/Console/Commands/ReceiveEmail.php#L195-L200

I don't currently have any plans to store these and allow manual re-sending from the web app.

**Comment by luckydonald** [comment]
@willbrowningme I don't see that information anywhere.
<img width="699" alt="Screenshot 2024-05-04 at 12 42 11" src="https://github.com/anonaddy/anonaddy/assets/2737108/0cd91462-e6e4-4969-8cab-5a2a841b55fc">

**Comment by willbrowningme** [comment]
Please [send me an email](https://addy.io/contact/) with a recent example so I can check the logs.

**Comment by luckydonald** [comment]
If I could send emails, I wouldn't  have opened this issue.

**Comment by willbrowningme** [comment]
I mean send me an email from your recipient email (not your alias) and let me know an alias that you recently tried with.
