### ISSUE TITLE
email filter not triggered by annonaddy... how to set up most reliably?

### ISSUE THREAD

**Issue by CouldBeThis** [anonaddy/anonaddy#63]
I was wondering if anyone else has problems making filters mails via anonaddy. (I admit that I do make filters complicated sometimes.) The mail server seems to have a difficult time recognizing the triggers to filter.  

It is an *extremely* tedious way to troubleshoot (see bottom of this post) so unfortunately I don't have as thorough information as I would like. 

## Goal: *consistently* filter incoming messages according to uuid

Ideally, I want to trigger the filter based on what unique uuid email address is used. In some cases, filtering based on what website sent it (I mean by domain name) would be acceptable. 

## looking for uuid in headers

I open the header on an email and I found the `uuid-xyz` in 3 places (I hope I transcribed correctly! sorry for any error):

### From

```
From: "Some Website 'noreply@somewebsite.com'"
  <uuid-xyz@@anonaddy.me>
```

This is what I would normally filter for. But I don't find it reliable at all. 

Maybe the fact that there are 2 email address in the same header confuses the filters? 

### Reply-To &  List-Unsubscribe

```
  Reply-To: uuid-xyz+noreply=somewebsite@@anonaddy.me
```

```
  List-Unsubscribe: <mailto:  uuid-xyz@unsubscribe.anonaddy.me?subject=unsubscribe>,
  <https://app.anonaddy.com/deactivate/xxxxxx-xxxxx-xxxxx
```

Filtering based on either these would be, frankly, a pain in the ass, because you have to go in to the advanced section and manually do it for each one. In tutanota I think it's impossible (that's mostly their fault of course).

## Attempts

For the above example I have tried triggering based on 
finding any or all of uuid-xyz@@anonaddy.me, noreply@somewebsite.com or @somewebsite.com in
`to`, 
`from`, 
`cc`, 
`body` (banner)

and the filter either doesn't work at all, works inconsistently, or works for a while then stops. 

(This is driving me totally nuts. I have spent *so much time* trying to make this simple thing work.  Sometimes I miss gmail, which because their business model involves surveilling users, has excellent searching technology. ;)  )

## Troubleshooting barriers (which are not annonaddy's fault)

I have accounts with tutanota and also traditional IMAP/SMTP accounts. If you haven't seen tutanota mail, they designed their own system from scratch. it offers only very basic, inflexible filtering. I wouldn't recommend it for this sort of use. 

On both servers there are some problems:

- hosts either do not keep logs of filters, or have no way/desire to share them with users, so when an email lands somewhere weird, there is not really any way to know what happened
- when a filter is modified/created, it cannot be run immediately on existing mail to see how it would work; it will only work on subsequent messages
- therefor you must wait (sometimes quite a while if the subject of the filter is not actively messaging) to see what happens
- in my case, I do not have capacity to closely monitor my mail all the time (that's why I want to set up filters to make it more efficient!) so by the time I get to sit down to fix the filters I don't know what I was thinking, what I tried before, etc. 
- I have been trying to make this work for ~6 months and I am close to conceding defeat.

## Please tell me how you have made this work

So I am hoping someone who has got this to work consistently could tell me what they do. 

I am sorry this is sort of confused. It is because I am confused.

**Comment by willbrowningme** [comment]
With the new updated "To:" header being set as the alias the email was originally sent to, are you able to now filter on that?

**Comment by willbrowningme** [comment]
Closing for now.

**Comment by CouldBeThis** [comment]
Sorry I am just going through my notifications as I seem to have missed some. 

Between the changes you made and the fact that I got a better email host, this problem is resolved. :)
