### ISSUE TITLE
No Support - so no AnonAddy for me

### ISSUE THREAD

**Issue by dec-mail** [anonaddy/anonaddy#636]
i checking here and see so many open Issue simply not replied to, let alone anything fixed.

so how can i rationally use an app like that

so so disappointing.

all hype.

**Comment by willbrowningme** [comment]
Support is not provided over GitHub.

**Comment by dec-mail** [comment]
> Support is not provided over GitHub.

Wow. So helpful. NOT. You say support provided here, although there is an obvious Issues function/tab; but you don't actually say WHERE your Support actually is then.

So helpful. Such great User Support.

**Comment by dec-mail** [comment]
And then you just Closed.

**Comment by dec-mail** [comment]
So my next action is to cancel Addy.io
