### ISSUE TITLE
[Bug(?)] Saving settings redirects to main page (unable to save 2fa recovery code)

### ISSUE THREAD

**Issue by Dich0tomy** [anonaddy/anonaddy#637]
I made an account on addy today. I wanted to configure 2FA and after each new settings change it redirected me to the dashboard - bit annoying, I said, but alright, I can live with that.

The problem is - I cannot save the 2FA recovery phrase. I paste the password, click "Generate new backup code" and it redirects me to the dashboard. A toast says "New recovery code created successfully", but the code is nowhere to be found, my guess is that it's supposed to be displayed right there in the settings panel, but that's not the case.

I considered upgrading immediately after setting it up, but I've withdrawn that decision since I'm not able to properly secure the account yet.

After each such change in the settings I get this in console:
```
Uncaught (in promise) 
Object { stack: "pn@https://app.addy.io/build/assets/app-BH5Einxe.js:21:7969\nrL@https://app.addy.io/build/assets/app-BH5Einxe.js:23:1038\nv@https://app.addy.io/build/assets/app-BH5Einxe.js:23:4237\n", message: "Request failed with status code 401", name: "AxiosError"
​
code: "ERR_BAD_REQUEST"
​
config: Object { timeout: 0, xsrfCookieName: "XSRF-TOKEN", xsrfHeaderName: "X-XSRF-TOKEN", … }
​
message: "Request failed with status code 401"
​
name: "AxiosError"
​
request: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
​
response: Object { data: {…}, status: 401, statusText: "", … }
​
stack: "pn@https://app.addy.io/build/assets/app-BH5Einxe.js:21:7969\nrL@https://app.addy.io/build/assets/app-BH5Einxe.js:23:1038\nv@https://app.addy.io/build/assets/app-BH5Einxe.js:23:4237\n"

```
```
{
  "data": {
    "message": "Unauthenticated."
  },
  "status": 401,
  "statusText": "",
  "headers": {
    "access-control-allow-origin": "*",
    "access-control-expose-headers": "Cache-Control, Content-Language, Content-Type, Expires, Last-Modified, Pragma",
    "cache-control": "no-cache, private",
    "content-type": "application/json",
    "date": "Sun, 12 May 2024 18:59:00 GMT",
    "server": "nginx",
    "x-firefox-spdy": "h2"
  },
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "adapter": [
      "xhr",
      "http"
    ],
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": null,
      "X-Requested-With": "XMLHttpRequest",
      "X-XSRF-TOKEN": "<redacted>"
    },
    "method": "get",
    "url": "/api/v1/chart-data"
  },
  "request": {}
}

```

I'm not entirely sure if it's related, since the endpoint is chart data, so it seems like the error is actually generated by the dashboard - but who knows, maybe it's related.

**Comment by willbrowningme** [comment]
Hmm, which browser are you using? Do you have any browser extensions that may be interfering with the requests?

It looks like the authentication cookie is not being passed to the chart-data end-point which is why it is returning "Unauthenticated".

I'm not able to reproduce this so can only assume that it must be a browser extension or something similar.

Could you try it in a private window with no extensions enabled?

**Comment by Dich0tomy** [comment]
Hello. My bad, I forgot to share browser information.

I'm using librewolf and it turns out it was in fact an extensions fault - chameleon - I could *swear* I had it disabled, but apparently I didn't, apologies for the trouble! I guess that's what happens when you do everything in a hurry :p
