### ISSUE TITLE
[Bug] `Bugzilla.Mozilla.org` disabled e-mail notifications due to rejection.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [anonaddy/anonaddy#639]
https://bugzilla.mozilla.org/bounced_emails/691781 states:

> Your Bugzilla account has been disabled due to issues delivering emails to your address.<br> <br> Your mail server said: (failed) x-unix; PHP Fatal error: Uncaught BadMethodCallException: Method Illuminate\Foundation\Application::configure does not exist. in /var/www/app.addy.io/html/releases/20240504-084339/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:86 Stack trace: #0 /var/www/app.addy.io/html/releases/20240504-084339/bootstrap/app.php(10): Illuminate\Foundation\Application::__callStatic() #1 /var/www/app.addy.io/html/releases/20240504-084339/artisan(12): require_once('...') #2 {main} thrown in /var/www/app.addy.io/html/releases/20240504-084339/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php on line 86<br>

I currently use https://app.addy.io/aliases/512baf97-e1fc-4c6a-ab4a-5dc1e3a1c0c7/edit, which isn't disabled.

**Comment by willbrowningme** [comment]
There was an error for a short amount of time when pushing a new release on 12th May. This was quickly resolved and there haven't been any issues since then. Your alias should be working as expected.

**Comment by RokeJulianLockhart** [comment]
Thanks, @willbrowningme.
