### ISSUE TITLE
Add manual rule for forwarding

### ISSUE THREAD

**Issue by slurdge** [anonaddy/anonaddy#64]
I would like to know where I should plug to add manual forwarding rules.
Let's say I have two domains configured with anonaddy: `example.com` and `example.net`
The default forwarding (with admin) etc. is fine, but i would like to have specific rules for example:
`hostmaster@example.com` -> `my@email.com`
or
`work@example.net`-> `work@gmail.com`

From what i understand, anonaddy is in charge of the virtual mapping. I'm not afraid to manually insert entries in the database with MySQL, but would that even be an option ?

**Comment by willbrowningme** [comment]
Have you tried adding virutal alias maps to your `/etc/postfix/main.cf` file? Like suggested in this article - https://electrictoolbox.com/update-postfix-virtual-alias-map/

**Comment by slurdge** [comment]
I use virtual alias on my others systems, but I was unsure on how it would interact with domains administered by anonaddy.

**Comment by slurdge** [comment]
I did it by auto-creating the user and making a rule to forward & remove the header. Closing.
