### ISSUE TITLE
I can't receive emails.

### ISSUE THREAD

**Issue by AlexMini2517** [anonaddy/anonaddy#641]
Hello, I have been using Addy for a month and it resetted the monthly bandwidth (now it's 0.15 MB of 10MB). There is only one problem: I can't receive emails. The aliases in question are all active.

Can you please help me?
Thanks in advance!

**Comment by willbrowningme** [comment]
Please [send me an email](https://addy.io/contact/) with details of your username.

**Comment by AlexMini2517** [comment]
sent.
