### ISSUE TITLE
Can't receive emails from docmorris.de or moddb.com

### ISSUE THREAD

**Issue by Just4Link** [anonaddy/anonaddy#643]
I have a problem with a few domain.

docmorris.de, moddb.com, hyperspin-fe.com

i forward all my aliases to proton mail. When i change the email directly to the proton mail i can receive mails again
like password reset etc.

i use a custom domain. i have over 100 aliases but there are like 5 or so domains what i dont get to work. there is not
even a error.

Can you assist me please?

**Comment by willbrowningme** [comment]
I cannot see any issues. Please [send me an email](https://addy.io/contact/) with details of an alias(es) that should have received a message from these senders in the last day or two but didn't.
