### ISSUE TITLE
[Feature Request] Allow a filter to automatically assign a receipient

### ISSUE THREAD

**Issue by yurividal** [anonaddy/anonaddy#644]
Hi. I would like to be able to create a filter that automatically picks a receipient based on the alias. I remember this feature being requested a while back, and it had been added to the roadmap.
Given this has not been implemented yet, is it still something in the pipeline? Or has the idea been abandoned?

This would be very useful

**Comment by willbrowningme** [comment]
This is now possible with Rules, you can select a recipient to forward to based on certain matched conditions.

**Comment by yurividal** [comment]
@willbrowningme thank you so much. I'll update and test as soon as the 1.2.1 docker image is released.
