### ISSUE TITLE
Re-entering password required after incorrect CAPTCHA on sign-up

### ISSUE THREAD

**Issue by maninthemiddle01** [anonaddy/anonaddy#645]
When I tried to sign up and solved the CAPTCHA incorrectly, I am prompted to solve the CAPTCHA again. However, in this process, the password input field is cleared, requiring the user to retype their password.

**Expected Behavior:**

When a user inputs an incorrect CAPTCHA during the sign-up process, the password input field should not be cleared and retain the previously entered password.

**Steps to reproduce:**

1. Visit Addy.io sign up page
2. Fill in the required information
3. Intentionally solve the CAPTCHA incorrectly
4. Observe that the password input field is cleared, requiring the user to retype their password

**Potential Solution:**

Retain the entered password in the input field even after an incorrect CAPTCHA submission, so the user only needs to correct the CAPTCHA and not retype their password.

**Comment by willbrowningme** [comment]
The password is not kept after a page refresh as you describe above by design. This is in order to keep sensitive data out of the session.

[https://laravel.com/docs/11.x/requests#old-input](https://laravel.com/docs/11.x/requests#old-input)
