### ISSUE TITLE
verification email is not being sent / AWS SES / Email is bouncing with "Email address is not verified" error

### ISSUE THREAD

**Issue by narainaDewasi** [anonaddy/anonaddy#647]
hello everyone, i know there is multiple issues already exist for this problem and i have already studied all. during this i saw that my issue is something similar to #584 this issue and i have already tried this solution . 
here is output of all logs file related to this issue

i am using AWS SES . i guess i am doing something wrong with configurations of postfix and aws ses but i dont know what. 

/var/log/mail.log
this is i got when verification mail has sent

``May 30 04:42:15 mail postfix/smtpd[1013881]: connect from mail.domain.com[127.0.0.1]
May 30 04:42:15 mail postfix/smtpd[1013881]: 246FE23EF5B: client=mail.domain.com[127.0.0.1]
May 30 04:42:15 mail postfix/cleanup[1013883]: 246FE23EF5B: message-id=<f8a01e8b323ae0658df12da41cbf3dd9@domain.com>
May 30 04:42:15 mail postfix/qmgr[854785]: 246FE23EF5B: from=<b_ofshc3dponygkn3xhbra_mm3dgojygeytg@domain.com>, size=14452, nrcpt=1 (queue active)
May 30 04:42:19 mail postfix/smtp[1013884]: 246FE23EF5B: to=<narayan.lal@slashash.co>, relay=xxx.amazonaws.com[54.157.237.25]:587, delay=4.2, delays=0.72/0.08/2.3/1, dsn=5.0.0, status=bounced (host xxxx.amazonaws.com[54.157.237.25] said: 554 Message rejected: Email address is not verified. The following identities failed the check in region US-EAST-1: b_ofshc3dponygkn3xhbra_mm3dgojygeytg@domain.com... (in reply to end of DATA command))
May 30 04:42:19 mail postfix/cleanup[1013883]: 4DDF224039C: message-id=<20240530044219.4DDF224039C@mail.domain.com>
May 30 04:42:19 mail postfix/bounce[1013888]: 246FE23EF5B: sender non-delivery notification: 4DDF224039C
May 30 04:42:19 mail postfix/qmgr[854785]: 4DDF224039C: from=<>, size=17792, nrcpt=1 (queue active)
May 30 04:42:19 mail postfix/qmgr[854785]: 246FE23EF5B: removed
May 30 04:42:19 mail postfix/pipe[1013889]: 4DDF224039C: to=<b_ofshc3dponygkn3xhbra_mm3dgojygeytg@domain.com>, relay=anonaddy, delay=0.26, delays=0/0.01/0/0.25, dsn=2.0.0, status=sent (delivered via anonaddy service)
May 30 04:42:19 mail postfix/qmgr[854785]: 4DDF224039C: removed``

/etc/postfix/main.cf

``smtpd_banner = $myhostname ESMTP
biff = no

# appending .domain is the MUA's job.
append_dot_mydomain = no

readme_directory = no

compatibility_level = 3.6

#mime_header_checks = regexp:/etc/postfix/header_checks
#header_checks = regexp:/etc/postfix/header_checks

# SMTPD
#smtpd_tls_cert_file=/etc/nginx/conf.d/domain.com.d/server.crt
#smtpd_tls_key_file=/etc/nginx/conf.d/domain.com.d/server.key
#smtpd_use_tls=yes
#smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
#smtpd_tls_CApath = /etc/ssl/certs
#smtpd_tls_security_level = may
#smtpd_tls_protocols = !SSLv2, !SSLv3, !TLSv1
#smtpd_tls_loglevel = 1
#smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
#smtpd_tls_mandatory_exclude_ciphers = MD5, DES, ADH, RC4, PSD, SRP, 3DES, eNULL, aNULL
#smtpd_tls_exclude_ciphers = MD5, DES, ADH, RC4, PSD, SRP, 3DES, eNULL, aNULL
#smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1
#smtpd_tls_mandatory_ciphers = high
#smtpd_tls_ciphers = high
#smtpd_tls_eecdh_grade = ultra
#tls_high_cipherlist=EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA+RC4:EECDH:EDH+aRSA:RC4:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS
#tls_preempt_cipherlist = yes
#tls_ssl_options = NO_COMPRESSION

# SMTP
#smtp_tls_CApath = /etc/ssl/certs
#smtp_use_tls=yes
#smtp_tls_loglevel = 1
#smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
#smtp_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1
#smtp_tls_protocols = !SSLv2, !SSLv3, !TLSv1
#smtp_tls_mandatory_ciphers = high
#smtp_tls_ciphers = high
#smtp_tls_mandatory_exclude_ciphers = MD5, DES, ADH, RC4, PSD, SRP, 3DES, eNULL, aNULL
#smtp_tls_exclude_ciphers = MD5, DES, ADH, RC4, PSD, SRP, 3DES, eNULL, aNULL
#smtp_tls_security_level = may

#smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
myhostname = mail.domain.com
mydomain = domain.com
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
myorigin = /etc/mailname

mydestination = localhost.$mydomain, localhost

virtual_transport = anonaddy:
virtual_mailbox_domains = $mydomain, unsubscribe.$mydomain, mysql:/etc/postfix/mysql-virtual-alias-domains-and-subdomains.cf

# AWS SES
relayhost = [xxx.amazonaws.com]:587
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtp_sasl_security_options = noanonymous
smtp_use_tls = yes
smtp_tls_security_level = encrypt
smtp_tls_note_starttls_offer = yes

#mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
mailbox_size_limit = 0
recipient_delimiter = +
inet_interfaces = all
inet_protocols = all

local_recipient_maps =

smtpd_helo_required = yes
smtpd_helo_restrictions =
    permit_mynetworks
    permit_sasl_authenticated
    reject_invalid_helo_hostname
    reject_non_fqdn_helo_hostname
    reject_unknown_helo_hostname

smtpd_sender_restrictions =
   permit_mynetworks
   permit_sasl_authenticated
   reject_non_fqdn_sender
   reject_unknown_sender_domain
   reject_unknown_reverse_client_hostname

smtpd_recipient_restrictions =
   permit_mynetworks,
   reject_unauth_destination,
   check_policy_service unix:private/policy,
   reject_rhsbl_helo dbl.spamhaus.org,
   reject_rhsbl_reverse_client dbl.spamhaus.org,
   reject_rhsbl_sender dbl.spamhaus.org,
   reject_rbl_client zen.spamhaus.org
   reject_rbl_client dul.dnsbl.sorbs.net

# Block clients that speak too early.
smtpd_data_restrictions = reject_unauth_pipelining

# Milter configuration
milter_default_action = accept
milter_protocol = 6
smtpd_milters = inet:localhost:11332
non_smtpd_milters = $smtpd_milters
milter_mail_macros =  i {mail_addr} {client_addr} {client_name} {auth_authen}

disable_vrfy_command = yes
strict_rfc821_envelopes = yes
smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt``

.env file
``# The from name to be used for outgoing email notifications from addy.io
MAIL_FROM_NAME=Onebuck
# The from address to be used for outgoing email notifications from addy.io
MAIL_FROM_ADDRESS=mailer@domain.com
MAIL_DRIVER=smtp
MAIL_HOST=mail.domain.com
MAIL_PORT=25
MAIL_ENCRYPTION=tls
MAIL_EHLO_DOMAIN=mail.domain.com
MAIL_VERIFY_PEER=true``

``# The SMTP FROM address to be used if the alias address cannot be, e.g. for a custom domain that is not verified for sending
ANONADDY_RETURN_PATH=mailer@domain.com
# This allows you to receive emails as a catch-all at the apex domain e.g. *@example.com
ANONADDY_ADMIN_USERNAME=ubuntu
ANONADDY_ENABLE_REGISTRATION=true
ANONADDY_DOMAIN=domain.com
ANONADDY_HOSTNAME=mail.domain.com
ANONADDY_DNS_RESOLVER=127.0.0.1
ANONADDY_ALL_DOMAINS=domain.com``

/var/www/anonaddy/storage/logs/laravel*.log

``()
#41 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#42 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#44 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#46 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#47 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#48 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#49 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#50 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#51 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#53 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#54 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#56 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#57 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#59 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#61 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#63 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#65 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#67 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#68 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1172): Illuminate\\Foundation\\Http\\Kernel->handle()
#69 /var/www/anonaddy/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest()
#70 {main}
"}
[2024-05-29 11:40:10] production.ERROR: The MAC is invalid. {"userId":"6b3a338a-e504-4104-8609-e41af890d1ea","exception":"[object] (Illuminate\\Contracts\\Encryption\\DecryptException(code: 0): The MAC is invalid. at /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:189)
[stacktrace]
#0 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(357): Illuminate\\Encryption\\Encrypter->decrypt()
#1 /var/www/anonaddy/app/Traits/HasEncryptedAttributes.php(14): Illuminate\\Support\\Facades\\Facade::__callStatic()
#2 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2232): App\\Models\\Recipient->getAttribute()
#3 /var/www/anonaddy/app/Models/User.php(112): Illuminate\\Database\\Eloquent\\Model->__get()
#4 [internal function]: App\\Models\\User->App\\Models\\{closure}()
#5 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(704): call_user_func()
#6 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(2209): Illuminate\\Database\\Eloquent\\Model->mutateAttributeMarkedAttribute()
#7 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(517): Illuminate\\Database\\Eloquent\\Model->transformModelValue()
#8 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(471): Illuminate\\Database\\Eloquent\\Model->getAttributeValue()
#9 /var/www/anonaddy/app/Traits/HasEncryptedAttributes.php(11): Illuminate\\Database\\Eloquent\\Model->getAttribute()
#10 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2232): App\\Models\\User->getAttribute()
#11 /var/www/anonaddy/app/Http/Middleware/HandleInertiaRequests.php(49): Illuminate\\Database\\Eloquent\\Model->__get()
#12 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Http\\Middleware\\HandleInertiaRequests->App\\Http\\Middleware\\{closure}()
#13 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure()
#15 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#16 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#17 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(357): Illuminate\\Container\\Container->call()
#18 /var/www/anonaddy/vendor/inertiajs/inertia-laravel/src/Response.php(200): Illuminate\\Support\\Facades\\Facade::__callStatic()
#19 /var/www/anonaddy/vendor/inertiajs/inertia-laravel/src/Response.php(132): Inertia\\Response->resolvePropertyInstances()
#20 /var/www/anonaddy/vendor/inertiajs/inertia-laravel/src/Response.php(93): Inertia\\Response->resolveProperties()
#21 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(900): Inertia\\Response->toResponse()
#22 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(885): Illuminate\\Routing\\Router::toResponse()
#23 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Routing\\Router->prepareResponse()
#24 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#25 /var/www/anonaddy/vendor/inertiajs/inertia-laravel/src/Middleware.php(96): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Inertia\\Middleware->handle()
#27 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#29 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#31 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(64): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#33 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#35 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#37 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#39 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#40 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#42 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#44 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#46 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#47 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#48 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#49 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#50 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#51 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#53 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#54 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#56 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#57 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#59 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#61 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#63 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#65 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#67 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#68 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1172): Illuminate\\Foundation\\Http\\Kernel->handle()
#69 /var/www/anonaddy/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest()
#70 {main}
"}``

supervisor logs  
 Today's logs :- 
sudo cat anonaddy_07-stdout---supervisor-8sx3av1n.log
  2024-05-30 04:42:14 App\Notifications\CustomVerifyEmail ............ RUNNING
  2024-05-30 04:42:15 App\Notifications\CustomVerifyEmail ............ 1s DONE

**Comment by narainaDewasi** [comment]
@willbrowningme can you plx tell me that how can i changed my from email as u see in this log

May 30 06:17:06 mail postfix/smtpd[1032343]: connect from mail.domain.com[127.0.0.1]
May 30 06:17:06 mail postfix/smtpd[1032343]: DDEC223EF5B: client=mail.domain.com[127.0.0.1]
May 30 06:17:06 mail postfix/cleanup[1032345]: DDEC223EF5B: message-id=<e502da895e4af1812fc6bb7a684909b1@domain.com>
May 30 06:17:07 mail postfix/qmgr[1025558]: DDEC223EF5B: from=**<b_nnqwq4tfmn3wi3lsmfwa_gvtgimrvmy4ta@domain.com>**, size=14452, nrcpt=1 (queue active)
May 30 06:17:10 mail postfix/smtp[1032346]: DDEC223EF5B: to=<narayan.lal@slashash.co>, relay=email-smtp.us-east-1.amazonaws.com[52.206.145.59]:587, delay=3.9, delays=0.52/0.08/2.3/1, dsn=5.0.0, status=bounced (host email-smtp.us-east-1.amazonaws.com[52.206.145.59] said: 554 Message rejected: Email address is not verified. The following identities failed the check in region US-EAST-1: b_nnqwq4tfmn3wi3lsmfwa_gvtgimrvmy4ta@domain.com... (in reply to end of DATA command))
May 30 06:17:10 mail postfix/cleanup[1032345]: D06FA24039C: message-id=<20240530061710.D06FA24039C@mail.domain.com>
May 30 06:17:10 mail postfix/bounce[1032389]: DDEC223EF5B: sender non-delivery notification: D06FA24039C
May 30 06:17:10 mail postfix/qmgr[1025558]: D06FA24039C: from=<>, size=17792, nrcpt=1 (queue active)
May 30 06:17:10 mail postfix/qmgr[1025558]: DDEC223EF5B: removed
May 30 06:17:11 mail postfix/pipe[1032390]: D06FA24039C: to=<b_nnqwq4tfmn3wi3lsmfwa_gvtgimrvmy4ta@domain.com>, relay=anonaddy, delay=0.26, delays=0/0.01/0/0.24, dsn=2.0.0, status=sent (delivered via anonaddy service)
May 30 06:17:11 mail postfix/qmgr[1025558]: D06FA24039C: removed


i want to change this with <b_nnqwq4tfmn3wi3lsmfwa_gvtgimrvmy4ta@mail.domain.com>  cause my verified domain with aws ses is mail.domain.com and its using the @domain.com .

i can not find the configuration for this .

**Comment by narainaDewasi** [comment]
its working when replace all domain.com with mail.domain.com in .env file

**Comment by willbrowningme** [comment]
Closing as I don't think this is related to the addy.io software.
