### ISSUE TITLE
UUID limit applied

### ISSUE THREAD

**Issue by mrx23dot** [anonaddy/anonaddy#648]
UUID aliases used to be unlimited for free accounts. What happen?
There is nothing about in documention/pricing page.

10MB Monthly Bandwidth Limit  is enough restriction already.

**Comment by willbrowningme** [comment]
UUID aliases at shared domains have never been unlimited on free accounts. Only aliases that use your own unique username subdomain `*@username.anonaddy.com` are unlimited.

**Comment by willbrowningme** [comment]
You can change the default alias domain in your account settings.
