### ISSUE TITLE
Bug: Some minutes delay when creating new alias on addy.io

### ISSUE THREAD

**Issue by therealmarv** [anonaddy/anonaddy#650]
I've created first one, then two, then 3 aliases in a row:

The reason for that was that they are not immediately visible.

It took several minutes (1-3 minutes, not sure) for them to show up on addy.io 

When I create a new alias it's important to be able to use it immediately (usually I'm creating one when I'm in the process to register on a new webpage).

**Comment by willbrowningme** [comment]
A large database migration was just running which temporarily slowed down queries. Everything should be back to normal now.
