### ISSUE TITLE
Using anonaddy with another MX server?

### ISSUE THREAD

**Issue by satoshinotdead** [anonaddy/anonaddy#652]
I'm curious if there's a way to utilize our current domain with an email provider to create aliases and activate standard email services within the same domain.

**Comment by willbrowningme** [comment]
[https://addy.io/faq/#can-i-add-a-domain-if-im-already-using-it-for-email-somewhere-else](https://addy.io/faq/#can-i-add-a-domain-if-im-already-using-it-for-email-somewhere-else)

**Comment by satoshinotdead** [comment]
> https://addy.io/faq/#can-i-add-a-domain-if-im-already-using-it-for-email-somewhere-else

Thanks, may I know your toughts (or can you share curated info) about exposing the IP address proxied when using MX subdomains?
