### ISSUE TITLE
Apple app not allowing access to emails

### ISSUE THREAD

**Issue by techtort** [anonaddy/anonaddy#656]
The app shows options of signing up for monthly or yrly fees but have fully paid up plan...just uninstall and redown load?

**Comment by willbrowningme** [comment]
That app was not created by myself and the subscription offered in the app is not connected to your addy.io account subscription in any way.

https://addy.io/faq/#is-there-an-ios-app

You do not need to pay for the subscription in order to use the majority of features in that app.

**Comment by techtort** [comment]
Thank u for the reply - so may uninstall app and see if reinstallation has same message or simply not use it on cell phone ☺️👍
