### ISSUE TITLE
Create custom alias on shared domain from UI

### ISSUE THREAD

**Issue by satoshinotdead** [anonaddy/anonaddy#658]
Hello, if that's possible?

I'm trying to recover a deleted alias on base subdomain (without user on address). I know I can try with API but I wonder if UI could be enough.

**Comment by willbrowningme** [comment]
Shared domain aliases (e.g. *@anonaddy.me) can only be randomly generated. You cannot choose the local part for them.

Please do not open issues just to ask a question.

**Comment by satoshinotdead** [comment]
Hello.

> Please do not open issues just to ask a question.

It's not a question, I need to create the same alias I deleted by mistake in order to recover an account, so my issue persists and won't supposed to be closed.

**Comment by willbrowningme** [comment]
If you've `deleted` the alias then you can restore it by finding it in your aliases list [https://app.addy.io/aliases?deleted=only](https://app.addy.io/aliases?deleted=only) selecting it and then clicking restore.

If you've `forgotten` the alias then it cannot be restored.

**Comment by satoshinotdead** [comment]
I forgotten the alias and I really need to restore it, so I'm OK on re-opening the issue and re-enabling anybody to help.

**Comment by willbrowningme** [comment]
As I said above, an alias that uses a shared domain that is `forgotten` cannot be recovered.

When forgetting the alias you are shown the warning:

> Are you sure you want to forget **alias@anonaddy.me**? Forgetting an alias will disassociate it from your account.
> **Note:** This alias uses a shared domain so it can **never be restored or used again** so make sure you are certain. Once forgotten, **alias@anonaddy.me** will reject any emails sent to it.

**Comment by satoshinotdead** [comment]
May I ask what's the point at blocking this action? It's an expected behavior?

I recovered everything but with my previous e-mail. I may have lost the access.
