### ISSUE TITLE
postfix config

### ISSUE THREAD

**Issue by netstat-peanut** [anonaddy/anonaddy#66]
hello,

disclaimer: this is not an anonaddy issue but its resolution may help others.

how can i configure postfix to accept email for user accounts on the anonaddy server using the configured domains? for instance, i have domain1.com and domain2.com working fine with anonaddy but i'm not sure how to allow mail delivery for  linuxuser1@domain1.com and linuxuser1@domain2.com.  this is definitely a postfix-related question but i'm not familiar enough with how the anonaddy config impacts this, hence my asking here.

thanks!

**Comment by netstat-peanut** [comment]
update: i believe this started working as intended though i'm not sure how.  it would still be good to know what the intended behavior of anonaddy is with respect to interaction/integration with machine accounts.

**Comment by willbrowningme** [comment]
Your domain on AnonAddy will behave as a catch-all address, so aliases will be created automatically as soon as they receive their first email. So once an email is sent to linuxuser1@domain1.com that alias will show up in your dashboard.

**Comment by netstat-peanut** [comment]
thanks @willbrowningme!  so if i understand you correctly, any _local system_ user, such as linuxuser1 theoretically found in /etc/passwd, will not receive email sent to linuxuser1@domain1.com unless he/she is also setup as the anonaddy "owner" of the custom domain domain1.com with forwarding configured as appropriate?

**Comment by willbrowningme** [comment]
When self-hosting AnonAddy it does not look at the sytem user accounts just whichever domains you've set up in `/etc/postifx/main.cf` and any custom domains that have been added by yourself or other users.

**Comment by netstat-peanut** [comment]
gotcha, thanks @willbrowningme!
