### ISSUE TITLE
DNS Verification Failing

### ISSUE THREAD

**Issue by nickrupert7** [anonaddy/anonaddy#662]
Hello, I have been using anonaddy/addy.io for over a year and a half now. Until recently, it has worked just fine, but now, I am suddenly receiving DNS verification errors on my custom domain with the following error messages:

`CNAME dk1._domainkey record not found. This could be due to DNS caching, please try again later.`

`CNAME dk2._domainkey record not found. This could be due to DNS caching, please try again later.`

The past few days, it's been on and off - One minute it will verify, then that evening, I'll get the email that verification is failing again, and when I manually recheck, it just keeps failing.

I did recently migrate my domain name registration and DNS to AWS Route 53, but this was over a week ago, and I can confirm that all of the correct records ARE in my Hosted Zone. 3rd party DNS query tools also always return the correct records. The TTL on the relevant records in both the old and new DNS were 300s (5 mins), so it really shouldn't be a caching issue several days later like this.

This same issue was also referenced in https://github.com/anonaddy/anonaddy/issues/491, but no solution was ever given because it seemingly resolved itself.

**Comment by willbrowningme** [comment]
Please could you [send me an email](https://addy.io/contact/) with details of your domain so that I can have a look into this?

**Comment by nickrupert7** [comment]
Email sent. Thanks!

**Comment by willbrowningme** [comment]
It seems this issue was caused by an incorrect DNSSEC configuration after recently changing DNS Providers.

**Comment by nickrupert7** [comment]
Confirming for future reference: Enabling DNSSEC on my domain did appear to resolve the issue. If you find yourself in the same boat as me, please try enabling DNSSEC and everything should validate correctly!

Thank you @willbrowningme !
