### ISSUE TITLE
Send an Email from Custom Domain Not Working

### ISSUE THREAD

**Issue by johnometalman** [anonaddy/anonaddy#667]
I already configured all records in my dns and I am able to receive emails. 

But when I try to send an email from an alias using a custom domain, my email provider rejects it! does not happen with aliases without custom domain.

**Comment by willbrowningme** [comment]
Have you recently moved your custom domain from your current email provider and could it still be listed there internally hence the rejection?

**Comment by willbrowningme** [comment]
If the issue still persists please [send me an email](https://addy.io/help/) with details of the domain so I can look into it.
