### ISSUE TITLE
Register page error

### ISSUE THREAD

**Issue by TronXYZ** [anonaddy/anonaddy#669]
![image](https://github.com/user-attachments/assets/9b278f79-8279-4ce0-9421-569f4d1c4165)

**Comment by willbrowningme** [comment]
Thanks, I've just fixed this now. It was caused by an error in a recently updated version of the Catpcha package addy.io uses - I've opened a PR to fix it there too https://github.com/mewebstudio/captcha/pull/297

**Comment by TronXYZ** [comment]
Thanks. That was fast!
