### ISSUE TITLE
Changing recipients on the free plan

### ISSUE THREAD

**Issue by BurnedOliveTree** [anonaddy/anonaddy#675]
Hi,
I don't know if this comes from my lack of knowledge, but I don't seem to be able to change the recipient of my aliases on the free plan - since I can't create a new recipient or edit the existing one. Am I missing something?

**Comment by willbrowningme** [comment]
You can edit your account's default recipient from the top of the [settings page](https://app.addy.io/settings) under "Update Email".

The Free plan is limited to 1 recipient as shown in the [pricing section](https://addy.io/#pricing).

**Comment by BurnedOliveTree** [comment]
I must've been blind, thank you so much!
