### ISSUE TITLE
add audio option to confirm captcha code

### ISSUE THREAD

**Issue by geazi-anc** [anonaddy/anonaddy#676]
In register page, is just possible create an account confirming captcha code, a text into an image.

However, this method is bad for people with visual impairment. A way for solve this problem is add an alternative captcha method using an audio option. With this solution, people with visual impairment are also able to create an account.

I am visual impaired. Any doubts, please contact me.

**Comment by willbrowningme** [comment]
I was previously using this package - https://github.com/mewebstudio/captcha for the Captcha.

I've just updated the site to use [Cloudflare Turnstile](https://www.cloudflare.com/en-gb/products/turnstile/) which is a privacy friendly captcha to protect those pages.

This should make for a much easier and smoother experience on those pages.
