### ISSUE TITLE
What DKIM selector is correct?

### ISSUE THREAD

**Issue by mzch** [anonaddy/anonaddy#68]
By default DKIM selector is `default` like `ANONADDY_DKIM_SELECTOR=default`, but I tried to add custome domains, then AnonAddy would instruct to put `dk1._domainkey CNAME dk1._domainkey.example.com` and `dk2._domainkey CNAME dk2._domainkey.example.com`.
What domainkey record should I put in DNS?

**Comment by netstat-peanut** [comment]
in my setup (which appears to be working correctly) i have custom domains set with TXT record of default._domainkey.domain.com and answer containing contents of /etc/opendkim/keys/domain.com/default.txt

**Comment by willbrowningme** [comment]
For self-hosting just use `default`, the `dk1` and `dk2` values are for users adding custom domains to the service and allow for easy DKIM key rotation. I need to update the popup for self-hosting.

**Comment by mzch** [comment]
@willbrowningme OK, thanks. I'm looking forward to update. :)

**Comment by willbrowningme** [comment]
Updated this now, will tag a new release shortly.
