### ISSUE TITLE
Invisible captcha when trying to login

### ISSUE THREAD

**Issue by studioph** [anonaddy/anonaddy#687]
Tried to login today and all of a sudden I'm getting an error "You must complete the captcha" except there's literally nothing there as shown in the screenshot:

![Screenshot_20241003_105015](https://github.com/user-attachments/assets/56476e33-7762-4f85-a2d6-329af96c402e)

Never had any issues in the ~3+ years I've been using the service.

- This is with Firefox 129.0.2 on Linux. 

- Yes I use uBlock, no it is not reporting blocking anything, and disabling does not change anything.

- DOM inspector shows Cloudflare turnstile elements but I have no idea why they're not displaying.

----

On a related note, as a (not long-term but several years) paying user, I'm _**extremely**_ disappointed to see this Cloudflare sh*t being added. They have a well-known history of discriminating against Firefox users, Linux users, and anyone who dares to harden their browser for security and privacy. They've made other services unusable for me and lost me as a customer due to endless redirect loops, captchas always failing no matter what, and more. I really hope that doesn't become the case here as I've been really happy with what you've been doing but I may have to consider moving somewhere else if this becomes too much of a PITA. As a service focusing on privacy I find this move incredibly offensive and hypocritial and makes me question the trust I've put into it.

**Comment by willbrowningme** [comment]
Thanks for the honest feedback.

I've removed the captcha from the login page now so there shouldn't be any further issues logging in.

The motivation for the change from the previous captcha that was being used (https://github.com/mewebstudio/captcha) was that the latest release completely broke all authentication flows, password resets and username reminders. It still has not yet been fixed.

I had also received a large number of complaints about that captcha being impossible to solve, unfriendly for those who are partially sighted and a pain to solve.

I agree that captchas are a pain, and in an ideal world I would not have any. Unfortunately bad actors and bots abuse authentication endpoints and I've found Turnstile to be the least intrusive out of the available options.

If you have any other captcha alternatives / solutions I'm open to hearing about them.

**Comment by studioph** [comment]
Wow, wasn't expecting such a quick response, or for you to change the live site just for 1 person, but it is appreciated!

I apologize for the bluntness of my last paragraph there - I may have had many negative experiences with certain entities but that shouldn't taint my tone when reporting things.
