### ISSUE TITLE
Can't use an email address containing `+` as the email destination

### ISSUE THREAD

**Issue by in-plaintext** [anonaddy/anonaddy#689]
I'm attempting to subscribe to a Google Group, executed by sending mail in the format of `group+subscribe@example.com` (for instance [the Firefox releases group](https://groups.google.com/a/mozilla.org/g/announce/)). The `app.addy.io/aliases` page in 'send from alias' does not allow the plus sign `+`. 

> Use this to automatically create the correct address to send an email to in order to send an **email from this alias**.

**Comment by willbrowningme** [comment]
I've just tested `group+subscribe@example.com` as the destination and it works as expected showing:

`alias+group+subscribe=example.com@anonaddy.com`

If you have any screenshots or a more detailed description just let me know.
