### ISSUE TITLE
"Reply to" function from admin user with default shared domain don't work

### ISSUE THREAD

**Issue by Dryusdan** [anonaddy/anonaddy#693]
Hello

I encounter a problem, but I don't remember if it's after an upgrade or not? I discover it later than the last update. 

So, I have a default and shared domain on my addyio instance. I have 4 users who use my instance. 

When I try to respond to an email through addyio, I receive my own (sended) mail. 
When I try with a custom domain or with another user with a custom domain too the mail was successfully send.

To illustrate : I have 4 domains : dryusdan.im : default shared domain, dryusdan.net : my custom domain and dryusdan.eu a custom domain on a new user and dryusdan.fr my own mail domain hosted on another server

When me, dryusdan (admin), send an email from example@dryusdan.fr to 45475ufdq@dryusdan.im I receive this email forwarded by 45475ufdq@dryusdan.im and when I try to respond to me, the To is 45475ufdq+example=dryusdan.fr@dryusdan.im but email was received by 45475ufdq@dryusdan.im

But, when I send an email to 879jf5@dryusdan.net from example@dryusdan.fr,  when I respond the `To header` is 879jf5+example=dryusdan.net and email was successfully send to example@dryusdan.fr

I search on all log and enable debug but I don't see anything :/

I reinstall addyio and reconfiguring postfix without any success :/ 

Can you help me ? :) 

Thank !

**Comment by willbrowningme** [comment]
Have you checked this FAQ item - [https://addy.io/faq/#im-trying-to-reply-send-from-an-alias-but-the-email-keeps-coming-back-to-me-whats-wrong](https://addy.io/faq/#im-trying-to-reply-send-from-an-alias-but-the-email-keeps-coming-back-to-me-whats-wrong)

**Comment by Dryusdan** [comment]
I totally forgot checking the FAQ... Sorry, I check this

**Comment by Dryusdan** [comment]
Yeah, that was the problem... I use a wildcard email so I didn't use the default email.

So is "fixed" 

Thank !
