### ISSUE TITLE
Addy + Sendgrid inbound email?

### ISSUE THREAD

**Issue by tearfulDalvik** [anonaddy/anonaddy#694]
I know https://github.com/anonaddy/anonaddy/issues/86, however, the answer is for outbound emails.

I'd like to know if there's a way to utilize SendGrid's Inbound Parse like https://www.twilio.com/docs/sendgrid/ui/account-and-settings/inbound-parse , so that I don't need to build my mail server at all.

Thanks

**Comment by willbrowningme** [comment]
That isn't relevant to the addy.io software, you can contact SendGrid for help on setting that up.
