### ISSUE TITLE
Self-Hosted - Email are still forwarded even when Inactive/deactivated

### ISSUE THREAD

**Issue by slurdge** [anonaddy/anonaddy#72]
Hello, not sure this is related to docker or not.

When I mark an alias as Inactive, the email is still forwarded by anonaddy.

Steps:

1. Create an alias
2. Mark it as unactive
3. Send an email to the alias

The email is still forwarded. I tried to manually call the block_alias stored procedure with the inactive alias, and it works correctly: it increases the blocked cound by one and answers "discard".

What could cause the email to pass through ? Is there any log that I should check ? @crazy-max is there any place where I can find the postfix trail ?

**Comment by willbrowningme** [comment]
Have you made sure your `/etc/postifx/main.cf` config is correct? Particularly this section:

```
smtpd_recipient_restrictions =
   permit_mynetworks,
   reject_unauth_destination,
   check_recipient_access mysql:/etc/postfix/mysql-recipient-access.cf, mysql:/etc/postfix/mysql-recipient-access-domains-and-additional-usernames.cf,
   check_policy_service unix:private/policyd-spf
   reject_rhsbl_helo dbl.spamhaus.org,
   reject_rhsbl_reverse_client dbl.spamhaus.org,
   reject_rhsbl_sender dbl.spamhaus.org,
   reject_rbl_client zen.spamhaus.org
   reject_rbl_client dul.dnsbl.sorbs.net
```

**Comment by crazy-max** [comment]
@willbrowningme 

Yes this is [implemented](https://github.com/anonaddy/docker/blob/master/rootfs/etc/cont-init.d/03-config.sh#L274) for our Docker image.

**Comment by slurdge** [comment]
Yes and I double checked it. That's why I don't understand how it can pass the filer, as the 3rd line should reject it.

**Comment by slurdge** [comment]
@crazy-max do you have hints on how I can see the postfix logs ?

**Comment by crazy-max** [comment]
@slurdge Postfix logs are visible within the container (`docker-compose logs -f`). You can set [`POSTFIX_DEBUG=true`](https://github.com/anonaddy/docker#postfix) to increase verbosity.

**Comment by slurdge** [comment]
Thanks, I missed the `POSTFIX_DEBUG=true` flag. I made some more tests and I think it's related to https://github.com/anonaddy/docker/issues/22 and it's fix, which is unfortunately not working as intended.

If you look at the `smtpd_recipient_restrictions`, you will see that the first line is `permit_mynetworks`:
```
smtpd_recipient_restrictions =
   permit_mynetworks,
   reject_unauth_destination,
   check_recipient_access mysql:/etc/postfix/mysql-recipient-access.cf, mysql:/etc/postfix/mysql-recipient-access-domains-and-additional-usernames.cf,```

But as we are flagging IP coming from docker as 'internal', email is forwarded directly because the `check_recipient_access` is not triggered. I think it comes from the fact that my server is ipv6 compatible and some senders (gmail and some others) are sending over ipv6 link. See https://github.com/robbertkl/docker-ipv6nat

I propose two solutions:

- @crazy-max Remove the local networks that were added to the docker image, and update instructions telling to people that they need to NAT or disable ipv6;
- @willbrowningme I tried on my side to remove `permit_mynetworks` from `smtpd_recipient_restrictions` and it seems everything is working, but I'm not completely sure. Do you know why this line is here (apart from being by default in postfix) ?

Thank you both for the time & help :-)

**Comment by willbrowningme** [comment]
@slurdge That is most likely the issue.

http://www.postfix.org/postconf.5.html#permit_mynetworks is there by default.

It should be okay to remove `permit_mynetworks` from `smtpd_recipient_restrictions` since it is already listed under:

`smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination`

per http://www.postfix.org/postconf.5.html#smtpd_relay_restrictions

**Comment by slurdge** [comment]
Great! I'll do it on my instance! I think we can change it for the docker-image and maybe put a note for self hosting users.

**Comment by crazy-max** [comment]
@slurdge @willbrowningme  Ok I will change this behavior in the Docker image. Thanks for your input guys!
