### ISSUE TITLE
Show original "from" name

### ISSUE THREAD

**Issue by erik-h** [anonaddy/anonaddy#8]
First of all I'd like to say that I'm loving AnonAddy so far, so thank you!

Would you support the idea of adding an option in the settings to set the "From" name of forwarded emails to the name of the original sender? After sending a couple of test emails I'm noticing it's hard to differentiate between senders forwarded through AnonAddy, since they're all from the same address.

**Comment by erik-h** [comment]
Ahh sorry, I realized that the reason I'm seeing "AnonAddy" as the "from" for every email is because I added mailer@anonaddy.com to my contacts. When I forwarded to another email account that doesn't have AnonAddy in its contacts I realized that the "from" address is already set to the real sender.

**Comment by erik-h** [comment]
FYI for anyone using ProtonMail: to get the result I wanted (adding AnonAddy to my contacts while still showing the original sender's name in the "from" field) I had to manually remove the "Name" field from my contacts entry. When I originally hit the "add to contacts" button it had set the Name to AnonAddy.

**Comment by anonaddy** [comment]
Thanks, yes you're right AnonAddy does currently set the sender's from name and from address in the From: header but obviously it still has to be sent from an AnonAddy domain e.g. anonaddy.me otherwise it would end up in spam for forging the From: header.
