### ISSUE TITLE
Class 'Redis' not found on 0.3.0

### ISSUE THREAD

**Issue by mzch** [anonaddy/anonaddy#81]
Updating to 0.3.0, the following error occurred.

```php
$ sudo -u www-data php artisan queue:restart

   Error

  Class 'Redis' not found

  at vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:75
     71▕      * @throws \LogicException
     72▕      */
     73▕     protected function createClient(array $config)
     74▕     {
  ➜  75▕         return tap(new Redis, function ($client) use ($config) {
     76▕             if ($client instanceof RedisFacade) {
     77▕                 throw new LogicException(
     78▕                     extension_loaded('redis')
     79▕                         ? 'Please remove or rename the Redis facade alias in your "app" configuration file in order to avoid collision with the PHP Redis extension.'

  • A class import is missing: You have a missing class import. Try importing this class: `Illuminate\Support\Facades\Redis`.

      +22 vendor frames
  23  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Comment by willbrowningme** [comment]
You need to make sure that you have installed the `php-redis` module as mentioned in the [release notes](https://github.com/anonaddy/anonaddy/releases/tag/v0.3.0).

This can usually be done by running `sudo apt install php-redis` or installing the extension via PECL.

From the Laravel [docs](https://laravel.com/docs/8.x/redis#introduction):

> Before using Redis with Laravel, we encourage you to install and use the [PhpRedis](https://github.com/phpredis/phpredis) PHP extension via PECL. The extension is more complex to install but may yield better performance for applications that make heavy use of Redis.

**Comment by mzch** [comment]
Oh, I failed to notice it. Thanks! 👍
