### ISSUE TITLE
update issues

### ISSUE THREAD

**Issue by sandikata** [anonaddy/anonaddy#83]
Regarding to this https://github.com/anonaddy/anonaddy/blob/master/SELF-HOSTING.md#updating

I tried to update my installation which always fails.

https://bpa.st/ER2A

All the steps.

**Comment by willbrowningme** [comment]
You need to install the `php-redis` moduel by running `sudo apt install php-redis` or by using PECL.

Please see this issue - https://github.com/anonaddy/anonaddy/issues/81
