### ISSUE TITLE
Anonaddy domains/aliases/users limit

### ISSUE THREAD

**Issue by sandikata** [anonaddy/anonaddy#84]
Hello!
Is it there any limitation about this for self hosted anonaddy? 
And if not limited, where i can change the settings?

**Comment by willbrowningme** [comment]
The domains, aliases and recipients do not have any limits when self-hosting AnonAddy.

Apart from the additional usernames which does have a limit that can be updated in your `.env` file

`ANONADDY_ADDITIONAL_USERNAME_LIMIT=3`

**Comment by sandikata** [comment]
Thank you for the info.
