### ISSUE TITLE
Anonaddy storage limits

### ISSUE THREAD

**Issue by sandikata** [anonaddy/anonaddy#85]
Hello!
Is it possible to raise up storage limit to 10GB per account ?

**Comment by willbrowningme** [comment]
There is no storage limit, just bandwidth.

This can be updated in your `.env` file:

`ANONADDY_BANDWIDTH_LIMIT=104857600`

It is set in bytes and in `.env.example` it is 100MB.

**Comment by sandikata** [comment]
Thank you! I'll check it right now.
