### ISSUE TITLE
Anonaddy + Sendgrid

### ISSUE THREAD

**Issue by sandikata** [anonaddy/anonaddy#86]
Hello!

Is it possible to use anonaddy via sendgrid and to close port 25 on my postfix server?

**Comment by willbrowningme** [comment]
You can use any mail driver that is compatible with Laravel to send email.

Please check the Laravel docs - https://laravel.com/docs/8.x/mail#driver-prerequisites

You'll have to find a third-party package that allows integration with sendgrid, e.g. https://github.com/s-ichikawa/laravel-sendgrid-driver

**Comment by sandikata** [comment]
Thank you!
