### ISSUE TITLE
domain verification failed.

### ISSUE THREAD

**Issue by sandikata** [anonaddy/anonaddy#87]
Hello again, this is last question (i hope so).

I have some issues while adding new domain, it fails with DNS records. But i cannot catch where it is.

![Снимка от 2020-10-06 15-13-04](https://user-images.githubusercontent.com/884699/95200252-c0982100-07e6-11eb-82c0-9f1decc613ce.png)

There's a screenshot.

**Comment by willbrowningme** [comment]
It looks like you are using an old version of AnonAddy that had the dk1 and dk2 records. Please update to the latest version where it instructs you to add the correct default._domainkey record - shown in the code here https://github.com/anonaddy/anonaddy/blob/master/resources/js/pages/Domains.vue#L276

Add a new CNAME record with host as default._domainkey and value as default._domainkey.perspecta.org.

Then it should work.

**Comment by sandikata** [comment]
Yep, it was. I've updated anonaddy to latest version, and it blowed this warning.

**Comment by sandikata** [comment]
I've changed it yesterday, but domain is still not verified. Still complain about dk. records, or i have to remove it completely and add it again?

**Comment by willbrowningme** [comment]
Could you send me an email so I can check each of your domain's records instead of posting them all publicly here?

**Comment by sandikata** [comment]
Hm, maybe dk1 dk2 still must be there as CNAME and to add a  new CNAME for default._domainkey ?

![Screenshot_2020-10-07 DNS getmefollowed com Account Cloudflare - Web Performance Security](https://user-images.githubusercontent.com/884699/95301025-b169af80-0888-11eb-89ce-0ce65ab95cbe.png)

**Comment by willbrowningme** [comment]
For self-hosting you do not need dk1 and dk2. You can find my email at the bottom of this page - https://anonaddy.com/help/

**Comment by sandikata** [comment]
email sent.
