### ISSUE TITLE
response to forwarded mail

### ISSUE THREAD

**Issue by sandikata** [anonaddy/anonaddy#88]
since latest update of anonaddy the clients couldn't respond to forwarded mails.
All I can see in postfix log is 

`Oct  7 08:49:29 mailforwarder postfix/smtp[2743]: 24A262A9: to=<mailer+rosen.aleksandrov.1988=mail.ru@example.com>, relay=none, delay=0.02, delays=0.01/0/0/0, dsn=5.1.0, status=bounced (Domain example.com does not accept mail (nullMX))`

From where it takes example.com ?

**Comment by willbrowningme** [comment]
Please check your `.env` file and make sure all your variables are correct. `ANONADDY_DOMAIN=` etc.

**Comment by sandikata** [comment]
Yep, i think i've caught it and cleaned the cache. Now i'll leave the postfix server to clean all the queue's. Thank you again.
