### ISSUE TITLE
Encoding issues?

### ISSUE THREAD

**Issue by stefanschramek** [anonaddy/anonaddy#89]
Hi,
as you can see in the screenshot there seems to be an issue with German characters.
The missing character in the subject was "ü"!
![image](https://user-images.githubusercontent.com/921342/97206820-899ba680-17b9-11eb-84e4-fea2f0bb583a.png)

Thanks
Stefan

**Comment by willbrowningme** [comment]
Hmm, I'll look into this and see what it might be. Have you noticed it before or with any other characters?

**Comment by stefanschramek** [comment]
Actually it was the first time I noticed such issues!

**Comment by stefanschramek** [comment]
I found another issues which seems to be related to encoding.

I can see the following in ProtonMail iOS app when received via AnonAddy:
![IMG_3972](https://user-images.githubusercontent.com/921342/98794019-deb9f800-2408-11eb-9c37-140a55c1d0f8.PNG)

I can see the following in ProtonMail iOS app when received without AnonAddy:
![IMG_3971](https://user-images.githubusercontent.com/921342/98793996-da8dda80-2408-11eb-925b-b6bde87351a1.PNG)

Strangely enough, when viewed in the ProtonMail web app there is no issue at all!

Thanks
Stefan

**Comment by willbrowningme** [comment]
Closing for now, please reopen if you notice any other issues.
