### ISSUE TITLE
Pricing chart more easily available

### ISSUE THREAD

**Issue by ItsExtra** [anonaddy/anonaddy#9]
The [subscription page](https://app.anonaddy.com/settings/subscription) should have the [pricing chart](https://anonaddy.com/#pricing), or at least a link to it. Probably the other pages should all have a link to this information, especially for those who haven't yet subscribed. 

I had to go hunting for it.. Just trying to prevent loss of customers. :)

**Comment by anonaddy** [comment]
Great idea, it's on my to do list, I'll update this issue soon once I've added it. Thanks!

**Comment by jeroen7s** [comment]
Tbh I'd get rid of the bandwidth limit for all users except for the free tier.
Would love to use it, but currently get emails with attachments you will start dropping emails fast.
If I have one of someone's anonaddy addresses, All I need to do is send 2 emails with 5 MB attachments for them to start dropping emails. (or 10 in case of the paid accounts)

**Comment by anonaddy** [comment]
@jeroen7s Interesting point, I'll have a think about that. So far no users have complained of anyone abusing their bandwidth in this way.

The pricing chart is now visible on the subscription page.

Thanks
