### ISSUE TITLE
Recipients' removal including their encryption

### ISSUE THREAD

**Issue by Copy1235** [anonaddy/anonaddy#91]
Whenever you remove an Email that has the same encryption key as another Email in your recipients, the key is removed from both of the recipients.

**Comment by willbrowningme** [comment]
The key is only removed from your other recipients if you are the owner of the key. 

I've just pushed an update to fix this. Now the key will only be removed from the keyring on the server if you are the owner and if there are no other recipients on your account using the same key.

So if you delete a recipient that is using the same key as one of your other recipients it will no longer remove the key from the other recipient.
