### ISSUE TITLE
Small lag when switching views via bottom navigation bar

### ISSUE THREAD

**Issue by T0M0F** [anonaddy/anonaddy#92]
When switching between different views via the bottom navigation bar, for example switching from *Home* to *Aliases*, a minor lag occurs before the view switches. Probably because there is something loading in the background and the ui is waiting for it to finish. Without this minor lag the transition between the view would look more smooth.      

Steps to reproduce:
1. press *Home* (bottom navigation bar)
2. lag occurs
3. view switches

**Comment by willbrowningme** [comment]
@T0M0F Are you referring to the the AnonAddy Android app here?

If so please could you open an issue on the repo for it here - https://gitlab.com/Stjin/anonaddy-android

This app was not developed by myself, it was created by a developer named Stjin.
