### ISSUE TITLE
"Check Records" says CNAME default._domainkey record not found

### ISSUE THREAD

**Issue by crazy-max** [anonaddy/anonaddy#96]
Hi,

When I want to "Check Records" I've got:

```
CNAME default._domainkey record not found. This could be due to DNS caching, please try again later.
```

But the record exists on Namecheap:

![image](https://user-images.githubusercontent.com/1951866/98542434-d2a72c80-2288-11eb-9df3-203cee8609cf.png)

Am I missing something?

**Comment by h-town** [comment]
Your DKIM should be configured as a TXT type record that returns a string of data led with _ v=DKIM1; k=rsa; p= _

**Comment by willbrowningme** [comment]
Is this for self-hosting or on app.anonaddy.com?

**Comment by crazy-max** [comment]
@willbrowningme Yes self-hosting

**Comment by willbrowningme** [comment]
@crazy-max do you have `config('anonaddy.domain')` set correctly?

```php
$def = collect(dns_get_record('default._domainkey.' . $this->domain . '.', DNS_CNAME))
    ->contains(function ($r) {
        return $r['target'] === 'default._domainkey.' . config('anonaddy.domain');
    });

if (!$def) {
    return response()->json([
        'success' => false,
        'message' => 'CNAME default._domainkey record not found. This could be due to DNS caching, please try again later.'
    ]);
}
```

Those are the lines that performs the check in the code.

**Comment by crazy-max** [comment]
@willbrowningme 

> do you have config('anonaddy.domain') set correctly?

Yes

> Those are the lines that performs the check in the code.

I think that's the issue. On Namecheap host and target cannot be the same for CNAME:

![image](https://user-images.githubusercontent.com/1951866/99680069-920f9600-2a74-11eb-8f66-565e8ba45c59.png)

So `default._domainkey` / `default._domainkey.example.com.` does not work.
That's why I've used `default._domainkey` / `example.com.`.

**Comment by willbrowningme** [comment]
@crazy-max is this issue still present?

**Comment by crazy-max** [comment]
@willbrowningme Yes (0.6.2):

![Image1](https://user-images.githubusercontent.com/1951866/103928884-5a3bdb00-5114-11eb-8622-bd1126c37325.jpg)

![image](https://user-images.githubusercontent.com/1951866/103928551-e8fc2800-5113-11eb-983f-0ac5a453bd23.png)

DNS records on Namecheap:

![Image2](https://user-images.githubusercontent.com/1951866/103928956-763f7c80-5114-11eb-8644-8a90dae71ead.jpg)

WDYT about what I said in https://github.com/anonaddy/anonaddy/issues/96#issuecomment-730417789?

**Comment by willbrowningme** [comment]
Thanks for the screenshots. Hmm, I've not used namecheap to set DNS records before.

Please could you try the following CNAME record:

Host: default._domainkey
Value: default._domainkey.yourdomain.com 

Notice the missing period (full-stop) for the value of the record.

I'm not sure why namecheap wouldn't allow that since the host and value are different.

**Comment by crazy-max** [comment]
@willbrowningme Like I said in https://github.com/anonaddy/anonaddy/issues/96#issuecomment-730417789, I can't:

![image](https://user-images.githubusercontent.com/1951866/103938463-2962a280-5122-11eb-949b-1d83545b4c9f.png)

`default._domainkey` = `default._domainkey.example.com.` does not work.
Only I can do is `default._domainkey` / `example.com.`.

**Comment by willbrowningme** [comment]
I just tried to add that record with a domain I have on namecheap and it seems to have worked.

![namecheap-record](https://user-images.githubusercontent.com/20662079/103939857-5ca63100-5124-11eb-9570-64508ea84a08.png)

**Comment by crazy-max** [comment]
With the same domain as the zone?

Zone: `example.com`
CNAME: `default._domainkey` = `default._domainkey.example.com.`

**Comment by willbrowningme** [comment]
Okay, I think I understand the issue now.

So let's say you are self-hosting AnonAddy on the domain `maindomain.com`.

This domain should have `default._domainkey` set with an actual DKIM value e.g. `"v=DKIM1;h=sha256;k=rsa;...."`

Then say you want to add a custom domain through the domains page called `customdomain.com`.

This `customdomain.com` should have a `default._domainkey` record of `default._domainkey.maindomain.com.` so that it uses the same signing key as the maindomain.

In your example above if you are trying to add `example.com` as a custom domain then the record should point to the `default._domainkey` on the main domain hosting AnonAddy.

**Comment by crazy-max** [comment]
Yes in my case I don't have a custom domain but only use the main domain and I have defined this main domain in the anonaddy interface. Maybe I should not?

![image](https://user-images.githubusercontent.com/1951866/104032463-186b6d00-51c6-11eb-8529-807a160567f0.png)

> This domain should have `default._domainkey` set with an actual DKIM value e.g. `"v=DKIM1;h=sha256;k=rsa;...."`

About that it should be defined as a TXT record right?:

`TXT` / `s1._domainkey` / `v=DKIM1;t=s;p=`

![image](https://user-images.githubusercontent.com/1951866/104030907-012b8000-51c4-11eb-9afe-9f5eb53e9563.png)

Is there something wrong here in my records?

**Comment by willbrowningme** [comment]
That's right, you do not need to add the domain AnonAddy is running on to the domains page as this is seen as the main domain. So if I was using `example.com` to host AnonAddy I would not add `example.com` to the domains page too as it will already have been setup in `/etc/postfix/main.cf` during installation.

You can add `ANONADDY_ADMIN_USERNAME=johndoe` or whatever your username is to your `.env` file and that will allow your main domain to act as a catch-all.

I'm not sure what your `_domainkey` record with a value of `t=y; o=-;` is?

**Comment by crazy-max** [comment]
> That's right, you do not need to add the domain AnonAddy is running on to the domains page as this is seen as the main domain.

Ok got it thanks

> I'm not sure what your _domainkey record with a value of t=y; o=-; is?

I'm currently in test mode for DKIM. I have to add support for it in our Docker image (anonaddy/docker#35).
