### ISSUE TITLE
Please make better renderings for fonts

### ISSUE THREAD

**Issue by grande-mephistopheles** [anonaddy/anonaddy#98]
Some of the fonts are not easy in the eyes. At a glance for someone like me who has poor eyesight it's difficult to identify the aliases by description. As there's no favicon system, it's crucial to be careful so I don't accidentally delete an alias.

Some examples in the image
![anonadyy](https://user-images.githubusercontent.com/58479925/99809575-63f48980-2b3a-11eb-9230-c1e32906ace7.jpg)

I'm sure these fonts also exists in other places in the web app. I just mentioned some that bothers me most.
Please make the fonts with better contrasts.

**Comment by willbrowningme** [comment]
Thanks, I'll increase the darkness of those greys and push an update shortly.

**Comment by willbrowningme** [comment]
I've made the greys slightly darker in the latest release, is it now easier to see?

**Comment by grande-mephistopheles** [comment]
> I've made the greys slightly darker in the latest release, is it now easier to see?

yep it's much better. a bit darker wouldn't hurt :smiley:

**Comment by willbrowningme** [comment]
Great, I'll get some more user feedback and go darker if needs be. Thanks again.
