### ISSUE TITLE
Shorter UUID aliases

### ISSUE THREAD

**Issue by TheLastGimbus** [anonaddy/anonaddy#99]
Hi there!
First of all, thank you so muuchhh for creating this - this is just _perfect_ for keeping my email clean and not being afraid of creating new accounts

But many times, I've got weird errors and bugs on many sites because of using so long so weird emails - my cellphone providers sent me 3 sim cards, and sent 12 identical emails about it :shrug: They said it's because my email broke their system or something :shrug: 

Maybe I have too long nickname and this gets me into trouble, but if you could also make UUID shorter, it would probably save some trouble

**Comment by oregonpillow** [comment]
I would second this. Would be nice to set the length of UUID.

**Comment by stefanschramek** [comment]
Actually there is no shorter version of UUID:
https://www.ietf.org/rfc/rfc4122.txt

Unfortunately I also have issues from time to time using UUID based email addresses.

**Comment by TheLastGimbus** [comment]
Just

```python
uuid = generate_uuid()
uuid = uuid[0:10]
```

**Comment by oregonpillow** [comment]
Ah, thanks @stefanschramek for pointing that out. I didn't know. @TheLastGimbus the simplest solution would be to simply link your own domain name (negligible cost) and get AnonAddy premium (negligible cost) and then set your own email aliases as needed <anything>@<yourdomain>

**Comment by stefanschramek** [comment]
> Just
> 
> ```python
> uuid = generate_uuid()
> uuid = uuid[0:10]
> ```

I think it would be better to let it generate a random string with given RegEx pattern, as the whole idea of UUID is not possible anymore.
So anybody could set up own patterns, he wants to use!

**Comment by willbrowningme** [comment]
I'll add a new format soon that will be a shorter random string of alpha numberic characters, probably 8 long or so.

For example: `7dab4cpz@anonaddy.me`

What do you think?

**Comment by TheLastGimbus** [comment]
That would be great - this should actually *replace* UUID if you ask me - for now, I am pretty much always using custom words...

**Comment by willbrowningme** [comment]
I will likely keep the UUID format as there are still those that like using it but will move it down the list order and mainly focus on the new random string format.

With a string length of 8 and an alphabet of all lowercase letters and numbers (36) then there are about 2.8 trillion possible combinations which should be plenty of entropy.

**Comment by willbrowningme** [comment]
I've just added a new "Random Characters" alias format that allows you to create aliases where the local part is an alphanumeric string of length 8.

This is avilable on the free plan too so you can use this instead of the UUID aliases now.

**Comment by TheLastGimbus** [comment]
Thanks so much! Waiting to see this in browser extension as well!

**Comment by willbrowningme** [comment]
@TheLastGimbus will update it as soon as I can, it's long overdue a complete makeover to be honest, lot's of features I need to add.
